# SWIFT Examples Notebook

In [1]:
import swift_app as swift

## Getting the WRIS data
This can be done either using the generic fetch() method or the wris.download() method.

### WRIS time series data download using fetch()

In [4]:
# The list of basins or stations can be queried from the WRIS database using the wris.basins() or wris.stations() methods.
# This list can then be passed on to the fetch() to download the time series data.
basins_wris = swift.wris.basins(variable=["sediment", 'water_level']) # Returns a pandas Dataframe with the basins and their WRIS IDs for sediment data. You can specify other variables as needed.
basins_wris

SWIFT Table
Rows: 34 | Columns: 3
----------------------------------------
    id                                              basin     variable
0    1                              Brahmani and Baitarni     sediment
1    1                              Brahmani and Baitarni  water_level
2    2                                            Cauvery     sediment
3    2                                            Cauvery  water_level
4    3    East flowing rivers between Mahanadi and Pennar     sediment
5    3    East flowing rivers between Mahanadi and Pennar  water_level
6    4  East flowing rivers between Pennar and Kanyaku...     sediment
7    4  East flowing rivers between Pennar and Kanyaku...  water_level
8    5                                           Godavari     sediment
9    5                                           Godavari  water_level
10   6                                            Krishna     sediment
11   6                                            Krishna  water_level
12   7                                           Mahanadi     sediment
13   7                                           Mahanadi  water_level
14   8                                               Mahi     sediment
15   8                                               Mahi  water_level
16   9  Minor rivers draining into Myanmar and Bangladesh     sediment
17   9  Minor rivers draining into Myanmar and Bangladesh  water_level
18  10                                            Narmada     sediment
19  10                                            Narmada  water_level
20  11                                             Pennar     sediment
21  11                                             Pennar  water_level
22  12                                          Sabarmati     sediment
23  12                                          Sabarmati  water_level
24  13                                       Subernarekha     sediment
25  13                                       Subernarekha  water_level
26  14                                               Tapi     sediment
27  14                                               Tapi  water_level
28  15      West flowing rivers from Tadri to Kanyakumari     sediment
29  15      West flowing rivers from Tadri to Kanyakumari  water_level
30  16             West flowing rivers from Tapi to Tadri     sediment
31  16             West flowing rivers from Tapi to Tadri  water_level
32  17  West flowing rivers of Kutch and Saurashtra in...     sediment
33  17  West flowing rivers of Kutch and Saurashtra in...  water_level

In [5]:
# If needed, we can subset the returned dataframe containing the basins before downloading the data. 
# For example, if we are only interested in the sediment and water level data for the basins Cauvery and Godavari, 
# we can filter the dataframe as follows:
basins_wris_subset = basins_wris[basins_wris['basin'].isin(['Cauvery', 'Godavari'])]
basins_wris_subset

SWIFT Table
Rows: 4 | Columns: 3
----------------------------------------
  id     basin     variable
2  2   Cauvery     sediment
3  2   Cauvery  water_level
8  5  Godavari     sediment
9  5  Godavari  water_level

In [6]:
# Then we pass this subset table to the fetch function to download the data for these basins.
# Test fetch() from CWC basin table

gdf_wris = swift.fetch(
    basins_wris_subset,# the subset dataframe containing the basins and their WRIS IDs for sediment and water level data.
    output_dir="data_fetch_wris", #location where the downloaded files will be saved.
    start_date="2024-04-01",
    end_date="2024-06-07",
    merge=True, # merges and returns all the downloaded files as a geodataframe.
    plot=True, # plots the station-wise time series of the downloaded data.
    quiet=False, # prints the progress of the download and any warnings or errors encountered during the download process.
    overwrite=True # overwrites any existing files in the output directory with the same name as the downloaded files.
)

# gdf_wris will contain the merged geodataframe of the downloaded data for the specified basins and variables.

Starting fetch for stations table (rows=4) from 2024-04-01 to 2024-06-07...

/tmp/ipykernel_1677063/2194716967.py:4: UserWarning: Fetching WRIS data for basin-level input. Dispatching 4 basin-variable combinations; this may take a long time...
  gdf_wris = swift.fetch(

Searching WRIS database for basin='Cauvery', Variables=sediment from 2024-04-01 to 2024-06-07...This might take a while...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 18/18 [00:08<00:00,  2.07station/s]

Saved GeoPackage: data_fetch_wris/wris/cauvery/cauvery_sediment_2024-04-01_2024-06-07.gpkg (688 rows)

sediment downloaded in 8.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
sediment          18        18         15          0        3            8.8
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/cauvery
-------------------------------------------------------------
Searching WRIS database for basin='Cauvery', Variables=water_level from 2024-04-01 to 2024-06-07...This might take a while...

Dataset: water_level
Using cached station discovery

water_level:   3%|▎         | 1/36 [00:01<00:55,  1.57s/station]

WRIS API is busy right now... hang on, retrying (1/3)

water_level: 100%|██████████| 36/36 [00:32<00:00,  1.10station/s]

Saved GeoPackage: data_fetch_wris/wris/cauvery/cauvery_water_level_2024-04-01_2024-06-07.gpkg (38141 rows)

water_level downloaded in 33.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       36        36         36          0        0            33.2
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/cauvery
-------------------------------------------------------------
Searching WRIS database for basin='Godavari', Variables=sediment from 2024-04-01 to 2024-06-07...This might take a while...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:07<00:00,  1.77s/station]

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
sediment          4         4          0           0        4            7.1
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------
Searching WRIS database for basin='Godavari', Variables=water_level from 2024-04-01 to 2024-06-07...This might take a while...

Dataset: water_level
Using cached station discovery

water_level: 100%|██████████| 50/50 [00:22<00:00,  2.18station/s]

Saved GeoPackage: data_fetch_wris/wris/godavari/godavari_water_level_2024-04-01_2024-06-07.gpkg (23123 rows)

water_level downloaded in 23.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       50        50         32          0        18           23.2
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------

In [6]:
# gdf_wris will contain the merged geodataframe of the downloaded data for the specified basins and variables.
gdf_wris

,station_code,time,sed,lat,lon,geometry,basin,variable,wl
0,003-SRDCBE,2024-04-01 08:00:00,0.0,11.8406,77.4628,POINT (77.4628 11.8406),Cauvery,sediment,NaN
1,003-SRDCBE,2024-04-02 08:00:00,0.0,11.8406,77.4628,POINT (77.4628 11.8406),Cauvery,sediment,NaN
2,003-SRDCBE,2024-04-03 08:00:00,0.0,11.8406,77.4628,POINT (77.4628 11.8406),Cauvery,sediment,NaN
3,003-SRDCBE,2024-04-04 08:00:00,0.0,11.8406,77.4628,POINT (77.4628 11.8406),Cauvery,sediment,NaN
4,003-SRDCBE,2024-04-05 08:00:00,0.0,11.8406,77.4628,POINT (77.4628 11.8406),Cauvery,sediment,NaN
...,...,...,...,...,...,...,...,...,...
61947,NAG001,2024-06-07 20:00:00,NaN,18.2892,79.4739,POINT (79.4739 18.2892),Godavari,water_level,0.0
61948,NAG001,2024-06-07 21:00:00,NaN,18.2892,79.4739,POINT (79.4739 18.2892),Godavari,water_level,0.0
61949,NAG001,2024-06-07 22:00:00,NaN,18.2892,79.4739,POINT (79.4739 18.2892),Godavari,water_level,0.0
61950,NAG001,2024-06-07 23:00:00,NaN,18.2892,79.4739,POINT (79.4739 18.2892),Godavari,water_level,0.0
61951,NAG001,2024-06-08 00:00:00,NaN,18.2892,79.4739,POINT (79.4739 18.2892),Godavari,water_level,0.0

We can also use the fetch () function to donwload the WRIS time series data by passing the stations table returned from wris.stations()

In [8]:
stations = swift.wris.stations(basin=["Godavari", "Narmada"], variable=["solar", "sediment"])
stations

Searching the WRIS database... This might take a while...
WRIS API is busy right now... hang on, retrying (1/3)
WRIS API is busy right now... hang on, retrying (2/3)
The station list returned does not guarantee time series data availability for all time periods.

,station_code,station_name,latitude,longitude,river,basin,variable
0,007-ugdhyd,Pachegaon,19.5353,74.8336,Pravara,Godavari,sediment
1,017-ugdhyd,Saigaon,18.0500,77.0497,Manjira,Godavari,sediment
2,020-ugdhyd,Degloor,18.5456,77.5775,Manjira,Godavari,sediment
3,031-ugdhyd,Saloora,18.7033,77.7958,Manjira,Godavari,sediment
4,7D8FED08,Kovvada kalva reservoir,17.2067,81.5142,Kovvadakalva,Godavari,solar
5,7D901252,Vuyyuru,16.3814,80.8530,Seethapalli Vagu,Godavari,solar
6,7D903A6C,Dowlaiswaram,16.9361,81.7850,Gowthami,Godavari,solar
7,004-NDBHP,Chhidgaon,22.4012,77.3086,Ganjal,Narmada,sediment
8,006-TDSURAT,CHANWADA,22.0500,73.4653,Orsang,Narmada,sediment
9,009-ndbhp,Manot,22.7358,80.5131,Narmada,Narmada,sediment
10,01 02 17 002,Tapi at Burhanpur,21.2994,76.2354,Tapi,Narmada,sediment
11,013 NDBHP,Sandia,22.9167,78.3500,Narmada,Narmada,sediment
12,016-NDBHP,Narmadapuram,22.7560,77.7330,Narmada,Narmada,sediment

In [ ]:
# fetch() also works with WRIS station table; if for the requested time period,
# the data for a station is not available, it will be skipped 
# and the download will continue for the other stations.
gdf_wris_1 =swift.fetch(
    stations,
    output_dir="data_fetch_wris",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)
gdf_wris_1 
# The returned geodataframe (gdf_wris_1 in this case) will contain the merged data 
# for the stations and variables for which data was available for the specified time period.

Starting fetch for stations table (rows=13) from 2024-04-01 to 2024-05-07...
Searching WRIS database for basin='Godavari', Variables=sediment from 2024-04-01 to 2024-05-07...This might take a while...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:07<00:00,  1.76s/station]

No stations found with data in the requested time period; skipping merge for this dataset.

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
sediment          4         4          0           0        4            7.0
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------
Searching WRIS database for basin='Godavari', Variables=solar from 2024-04-01 to 2024-05-07...This might take a while...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:01<00:00,  2.88station/s]

Saved GeoPackage: data_fetch_wris/wris/godavari/stations_7d8fed08_7d901252_7d903a6c_solar_radiation_2024-04-01_2024-05-07.gpkg (3942 rows)

solar_radiation downloaded in 1.1 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
solar_radiation   3         3          3           0        0            1.1
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------
Searching WRIS database for basin='Narmada', Variables=sediment from 2024-04-01 to 2024-05-07...This might take a while...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 6/6 [00:07<00:00,  1.19s/station]

Saved GeoPackage: data_fetch_wris/wris/narmada/stations_004-ndbhp_006-tdsurat_009-ndbhp_plus3_sediment_2024-04-01_2024-05-07.gpkg (111 rows)

sediment downloaded in 7.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
sediment          6         6          3           0        3            7.2
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/narmada
-------------------------------------------------------------

,station_code,time,solar,lat,lon,geometry,basin,variable,sed
0,7D8FED08,2024-04-01 00:00:00,0.0,17.2067,81.5142,POINT (81.5142 17.2067),Godavari,solar,NaN
1,7D8FED08,2024-04-01 01:00:00,0.0,17.2067,81.5142,POINT (81.5142 17.2067),Godavari,solar,NaN
2,7D8FED08,2024-04-01 02:00:00,0.0,17.2067,81.5142,POINT (81.5142 17.2067),Godavari,solar,NaN
3,7D8FED08,2024-04-01 03:00:00,0.0,17.2067,81.5142,POINT (81.5142 17.2067),Godavari,solar,NaN
4,7D8FED08,2024-04-01 04:00:00,0.0,17.2067,81.5142,POINT (81.5142 17.2067),Godavari,solar,NaN
...,...,...,...,...,...,...,...,...,...
4048,013 NDBHP,2024-05-03 09:00:00,NaN,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,0.075
4049,013 NDBHP,2024-05-04 09:00:00,NaN,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,0.070
4050,013 NDBHP,2024-05-05 09:00:00,NaN,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,0.074
4051,013 NDBHP,2024-05-06 09:00:00,NaN,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,0.056
4052,013 NDBHP,2024-05-07 09:00:00,NaN,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,0.079

### Using the wris.download() method - By passing a list of basins and variables

In [16]:
gdf_wris_2 = swift.wris.download(
    basin=['Krishna', 'Tapi'], # basins for which the data needs to be downloaded
    variable=['discharge','solar'], # variables for which the data needs to be downloaded; can specify one or more variables as needed
    output_dir="data_download_wris", # folder where the downloaded data will be saved
    start_date='2024-01-01',
    end_date='2024-02-07',
    merge=True, # returns a geodataframe (gdf_wris_2) with the merged data for all the downloaded files; 
    overwrite=True,
    plot=True,
    quiet=False
)

Searching WRIS database for basin='Krishna', Variables=discharge, solar from 2024-01-01 to 2024-02-07...This might take a while...

Dataset: discharge
Using cached station discovery
WRIS API is busy right now... hang on, retrying (1/3)
WRIS API is busy right now... hang on, retrying (1/3)
WRIS API is busy right now... hang on, retrying (1/3)

discharge: 100%|██████████| 30/30 [00:15<00:00,  1.97station/s]

Saved GeoPackage: data_download_wris/wris/krishna/krishna_discharge_2024-01-01_2024-02-07.gpkg (715 rows)

discharge downloaded in 15.3 seconds

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:01<00:00,  4.23station/s]

Saved GeoPackage: data_download_wris/wris/krishna/krishna_solar_radiation_2024-01-01_2024-02-07.gpkg (6813 rows)

solar_radiation downloaded in 1.3 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
discharge         30        30         19          0        11           15.3
solar_radiation   5         5          5           0        0            1.3
-------------------------------------------------------------
Output directory: data_download_wris/wris/krishna
-------------------------------------------------------------
Searching WRIS database for basin='Tapi', Variables=discharge, solar from 2024-01-01 to 2024-02-07...This might take a while...

Dataset: discharge
Using cached station discovery

discharge: 100%|██████████| 21/21 [00:21<00:00,  1.01s/station]

Saved GeoPackage: data_download_wris/wris/tapi/tapi_discharge_2024-01-01_2024-02-07.gpkg (30 rows)

discharge downloaded in 21.3 seconds

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:06<00:00,  1.35s/station]

Saved GeoPackage: data_download_wris/wris/tapi/tapi_solar_radiation_2024-01-01_2024-02-07.gpkg (3730 rows)

solar_radiation downloaded in 6.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
discharge         21        21         1           0        20           21.3
solar_radiation   5         5          3           0        2            6.8
-------------------------------------------------------------
Output directory: data_download_wris/wris/tapi
-------------------------------------------------------------

In [17]:
gdf_wris_2

,station_code,time,q,lat,lon,geometry,basin,variable,solar
0,002-UKDPUNE,2024-01-01 08:00:00,0.0,17.2728,74.1647,POINT (74.1647 17.2728),Krishna,discharge,NaN
1,002-UKDPUNE,2024-01-02 08:00:00,0.0,17.2728,74.1647,POINT (74.1647 17.2728),Krishna,discharge,NaN
2,002-UKDPUNE,2024-01-03 08:00:00,0.0,17.2728,74.1647,POINT (74.1647 17.2728),Krishna,discharge,NaN
3,002-UKDPUNE,2024-01-04 08:00:00,0.0,17.2728,74.1647,POINT (74.1647 17.2728),Krishna,discharge,NaN
4,002-UKDPUNE,2024-01-05 08:00:00,0.0,17.2728,74.1647,POINT (74.1647 17.2728),Krishna,discharge,NaN
...,...,...,...,...,...,...,...,...,...
11283,GJSW0045,2024-02-07 15:00:00,NaN,21.3925,73.3858,POINT (73.3858 21.3925),Tapi,solar,354.0
11284,GJSW0045,2024-02-07 16:00:00,NaN,21.3925,73.3858,POINT (73.3858 21.3925),Tapi,solar,234.0
11285,GJSW0045,2024-02-07 17:00:00,NaN,21.3925,73.3858,POINT (73.3858 21.3925),Tapi,solar,112.0
11286,GJSW0045,2024-02-07 18:00:00,NaN,21.3925,73.3858,POINT (73.3858 21.3925),Tapi,solar,20.0
11287,GJSW0045,2024-02-07 19:00:00,NaN,21.3925,73.3858,POINT (73.3858 21.3925),Tapi,solar,0.0

# Getting the CWC data
- This can be done either using the generic fetch() method or the cwc.download() method.

- CWC only provides the near real-time water level data at gauge stations

### CWC time series data (only water level) using fetch()
- The list of basins or stations can be queried from the CWC database using the cwc.basins() or cwc.stations() methods.

- This list can then be passed on to the fetch() to get the water level time series data.

In [19]:

basins_cwc = swift.cwc.basins() # Returns a pandas Dataframe with the basins and their CWC IDs.
basins_cwc

SWIFT Table
Rows: 22 | Columns: 2
----------------------------------------
                                                basin  station_count
0                                    Barak and Others             42
1                               Brahmani and Baitarni             21
2                                         Brahmaputra            139
3                                             Cauvery             53
4     East flowing rivers between Mahanadi and Pennar             21
5   East flowing rivers between Pennar and Kanyaku...             39
6                                               Ganga            537
7                                            Godavari             90
8                                               Indus             18
9                                             Krishna             85
10                                           Mahanadi             60
11                                               Mahi             12
12  Minor rivers draining into Myanmar and Bangladesh              4
13                                            Narmada             26
14                                             Pennar             13
15                                          Sabarmati              6
16                                       Subernarekha             20
17                                               Tapi             25
18      West flowing rivers from Tadri to Kanyakumari             33
19             West flowing rivers from Tapi to Tadri             26
20  West flowing rivers of Kutch and Saurashtra in...             10
21                                       Yamuna Basin              1

In [5]:
# If needed, we can subset the returned dataframe containing the basins before downloading the data. 
# For example, if we are only interested in the sediment and water level data for the basins Cauvery and Godavari, 
# we can filter the dataframe as follows:
basins_cwc_subset = basins_cwc[basins_cwc['basin'].isin(['Narmada', 'Tapi'])]
basins_cwc_subset

SWIFT Table
Rows: 2 | Columns: 2
----------------------------------------
      basin  station_count
13  Narmada             26
17     Tapi             25

In [6]:
# Then we pass this subset table to the fetch function to download the data for these basins.

gdf_cwc = swift.fetch(
    basins_cwc_subset,# the subset dataframe containing the basins and their CWC IDs.
    output_dir="data_fetch_cwc", #location where the downloaded files will be saved.
    start_date="2024-04-01",
    end_date="2024-06-07",
    merge=True, # merges and returns all the downloaded files as a geodataframe.
    plot=True, # plots the station-wise time series of the downloaded data.
    quiet=False, # prints the progress of the download and any warnings or errors encountered during the download process.
    overwrite=True # overwrites any existing files in the output directory with the same name as the downloaded files.
)

# gdf_cwc will contain the merged geodataframe of the downloaded data for the specified basins and variables.

Starting fetch for stations table (rows=2) from 2024-04-01 to 2024-06-07...
Starting CWC download for station=['001-NDBHP', '001-TDSURAT', '002-NDBHP', '002-TDSURAT', '003-NDBHP', '003-TDSURAT', '004-NDBHP', '004-TDSURAT', '005-NDBHP', '005-TDSURAT', '006-NDBHP', '006-TDSURAT', '007-NDBHP', '008-NDBHP', '009-ndbhp', '010-NDBHP', '012-NDBHP', '014-NDBHP', '015-NDBHP', '016-NDBHP', '017-NDBHP', '018-ndbhp', '019-NDBHP', '020-NDBHP', '021-NDBHP', '033-TDSURAT'] from 2024-04-01 to 2024-06-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 26 | Format: CSV | Time range: 2024–2024
Basin filter: Narmada
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

/tmp/ipykernel_1655880/3938853363.py:3: UserWarning: Fetching CWC data for basin-level input. Dispatching 2 basins; this might take a while...
  gdf_cwc = swift.fetch(
water_level: 100%|██████████| 26/26 [00:00<00:00, 27947.69station/s]
Plotting:   4%|▍         | 1/26 [00:00<00:14,  1.76plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_005-NDBHP_pati.png

Plotting:   8%|▊         | 2/26 [00:01<00:12,  1.96plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_008-NDBHP_dindori.png

Plotting:  12%|█▏        | 3/26 [00:01<00:11,  2.00plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_001-TDSURAT_bodeli.png

Plotting:  15%|█▌        | 4/26 [00:02<00:10,  2.03plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_003-NDBHP_mohgaon.png

Plotting:  19%|█▉        | 5/26 [00:02<00:10,  1.99plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_014-NDBHP_handia.png

Plotting:  23%|██▎       | 6/26 [00:03<00:10,  1.97plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_003-TDSURAT_garudeshwar.png

Plotting:  27%|██▋       | 7/26 [00:03<00:09,  1.95plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_015-NDBHP_tawa_reservoir.png

Plotting:  31%|███       | 8/26 [00:04<00:08,  2.01plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_006-TDSURAT_chanwada.png

Plotting:  35%|███▍      | 9/26 [00:04<00:08,  2.01plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_018-ndbhp_mortakka.png

Plotting:  38%|███▊      | 10/26 [00:04<00:07,  2.07plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_006-NDBHP_patan.png

Plotting:  42%|████▏     | 11/26 [00:05<00:07,  2.04plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_004-TDSURAT_bharuch.png

Plotting:  46%|████▌     | 12/26 [00:05<00:06,  2.05plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_001-NDBHP_mukki.png

Plotting:  50%|█████     | 13/26 [00:06<00:06,  2.08plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_012-NDBHP_barmanghat.png

Plotting:  54%|█████▍    | 14/26 [00:06<00:05,  2.04plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_021-NDBHP_dhulsar.png

Plotting:  58%|█████▊    | 15/26 [00:07<00:05,  1.93plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_020-NDBHP_belkhedi.png

Plotting:  62%|██████▏   | 16/26 [00:07<00:05,  1.99plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_004-NDBHP_chhidgaon.png

Plotting:  65%|██████▌   | 17/26 [00:08<00:04,  2.01plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_033-TDSURAT_pingalwada.png

Plotting:  69%|██████▉   | 18/26 [00:08<00:03,  2.04plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_010-NDBHP_mandla.png

Plotting:  73%|███████▎  | 19/26 [00:09<00:03,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_009-ndbhp_manot.png

Plotting:  77%|███████▋  | 20/26 [00:09<00:02,  2.11plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_019-NDBHP_gadarwara.png

Plotting:  81%|████████  | 21/26 [00:10<00:02,  2.18plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_002-NDBHP_bamni.png

Plotting:  85%|████████▍ | 22/26 [00:10<00:01,  2.17plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_017-NDBHP_mandleshwar.png

Plotting:  88%|████████▊ | 23/26 [00:11<00:01,  2.17plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_016-NDBHP_narmadapuram.png

Plotting:  92%|█████████▏| 24/26 [00:11<00:00,  2.18plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_002-TDSURAT_rajpipla.png

Plotting:  96%|█████████▌| 25/26 [00:12<00:00,  2.16plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_007-NDBHP_kogaon.png

Plotting: 100%|██████████| 26/26 [00:12<00:00,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_005-TDSURAT_motinaroli.png
Plots generated: 26

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_narmada_2024-04-01_2024-06-07.gpkg (8194 rows)

water_level downloaded in 18.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       26        26         26          0        0            18.6
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------
Starting CWC download for station=['005-SWRDKOCHI', '008-TDSURAT', '010-TDSURAT', '011-TDSURAT', '012-TDSURAT', '013-SWRDKOCHI', '013-TDSURAT', '013-ukdpune', '014-SWRDKOCHI', '014-TDSURAT', '014-ukdpune', '015-SWRDKOCHI', '015-TDSURAT', '015-ukdpune', '016-TDSURAT', '017-TDSURAT', '017-ukdpune', '018-SWRDKOCHI', '020-TDSURAT', '021-TDSURAT', '021-ukdpune', '022-TDSURAT', '022-ukdpune', '023-TDSURAT', '023-ukdpune', '024-TDSURAT', '025-SWRDKOCHI', '026--ukdpune', '027-TDSURAT', '027-ukdpune', '028-SWRDKOCHI', '028-TDSURAT', '031-TDSURAT', '032-TDSURAT', '034-TDSURAT', '035-SWRDKOCHI', '035-TDSURAT', '036-TDSURAT', '037-TDSURAT', '038-SWRDKOCHI', '038-TDSURAT', '039-TDSURAT', '040-TDSURAT', '041-TDSURAT', '041-ukdpune', '042-TDSURAT', '043-TDSURAT', '050-TDSURAT', '057-TDSURAT', '058-TDSURAT', '061-TDSURAT'] from 2024-04-01 to 2024-06-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 51 | Format: CSV | Time range: 2024–2024
Basin filter: Tapi
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 51/51 [00:00<00:00, 27501.86station/s]
Plotting:   2%|▏         | 1/50 [00:00<00:23,  2.12plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_013-ukdpune_anjanari.png

Plotting:   4%|▍         | 2/50 [00:01<00:24,  1.95plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_024-TDSURAT_gadat.png

Plotting:   6%|▌         | 3/50 [00:01<00:23,  1.97plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_018-SWRDKOCHI_malakkara.png

Plotting:   8%|▊         | 4/50 [00:02<00:23,  1.98plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_041-ukdpune_muradpur.png

Plotting:  10%|█         | 5/50 [00:02<00:22,  1.97plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_032-TDSURAT_daman.png

Plotting:  12%|█▏        | 6/50 [00:03<00:22,  2.00plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_013-SWRDKOCHI_kalampur.png

Plotting:  14%|█▍        | 7/50 [00:03<00:21,  2.01plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_028-SWRDKOCHI_kalathukadavu.png

Plotting:  16%|█▌        | 8/50 [00:03<00:20,  2.02plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_014-SWRDKOCHI_ramamangalam.png

Plotting:  18%|█▊        | 9/50 [00:04<00:20,  2.01plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_014-ukdpune_badlapur.png

Plotting:  20%|██        | 10/50 [00:04<00:19,  2.02plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_025-SWRDKOCHI_peruvampadam.png

Plotting:  22%|██▏       | 11/50 [00:05<00:19,  2.02plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_021-ukdpune_mangaon.png

Plotting:  24%|██▍       | 12/50 [00:05<00:18,  2.01plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_015-ukdpune_belne_bridge.png

Plotting:  26%|██▌       | 13/50 [00:06<00:18,  2.05plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_005-SWRDKOCHI_kuniyil.png

Plotting:  28%|██▊       | 14/50 [00:06<00:17,  2.07plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_022-ukdpune_nagothane.png

Plotting:  30%|███       | 15/50 [00:07<00:16,  2.08plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_015-SWRDKOCHI_kidangoor.png

Plotting:  32%|███▏      | 16/50 [00:07<00:16,  2.08plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_027-TDSURAT_ozerkheda.png

Plotting:  34%|███▍      | 17/50 [00:08<00:15,  2.16plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_027-ukdpune_collem.png

Plotting:  36%|███▌      | 18/50 [00:08<00:15,  2.10plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_026--ukdpune_ganjem.png

Plotting:  38%|███▊      | 19/50 [00:09<00:15,  2.06plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_023-ukdpune_niivali.png

Plotting:  40%|████      | 20/50 [00:09<00:14,  2.05plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_035-TDSURAT_durvesh.png

Plotting:  42%|████▏     | 21/50 [00:10<00:14,  2.00plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_038-SWRDKOCHI_madamon.png

Plotting:  44%|████▍     | 22/50 [00:10<00:14,  2.00plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_028-TDSURAT_madhuban_dam.png

Plotting:  46%|████▌     | 23/50 [00:11<00:13,  2.02plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_035-SWRDKOCHI_pullakkayar.png

Plotting:  48%|████▊     | 24/50 [00:11<00:12,  2.02plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_034-TDSURAT_mahuwa.png

Plotting:  50%|█████     | 25/50 [00:12<00:12,  2.00plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_031-TDSURAT_vapi.png

Plotting:  52%|█████▏    | 26/50 [00:12<00:11,  2.03plot/s]

Saved: data_fetch_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_017-ukdpune_mahad.png

Plotting:  54%|█████▍    | 27/50 [00:13<00:11,  2.04plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_043-TDSURAT_nawtha.png

Plotting:  56%|█████▌    | 28/50 [00:13<00:10,  2.09plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_020-TDSURAT_sarangkheda.png

Plotting:  58%|█████▊    | 29/50 [00:14<00:10,  2.08plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_017-TDSURAT_bhusawal.png

Plotting:  60%|██████    | 30/50 [00:14<00:09,  2.16plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_036-TDSURAT_lohara.png

Plotting:  62%|██████▏   | 31/50 [00:15<00:08,  2.12plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_040-TDSURAT_pimpri.png

Plotting:  64%|██████▍   | 32/50 [00:15<00:08,  2.09plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_022-TDSURAT_ghala.png

Plotting:  66%|██████▌   | 33/50 [00:16<00:08,  2.12plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_037-TDSURAT_akola.png

Plotting:  68%|██████▊   | 34/50 [00:16<00:07,  2.12plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_021-TDSURAT_ukai_reservoir.png

Plotting:  70%|███████   | 35/50 [00:17<00:07,  2.11plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_013-TDSURAT_teska.png

Plotting:  72%|███████▏  | 36/50 [00:17<00:06,  2.11plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_014-TDSURAT_dedtalai.png

Plotting:  74%|███████▍  | 37/50 [00:18<00:06,  2.09plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_016-TDSURAT_hathnur.png

Plotting:  76%|███████▌  | 38/50 [00:18<00:06,  1.97plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_010-TDSURAT_lakhpuri.png

Plotting:  78%|███████▊  | 39/50 [00:19<00:05,  2.03plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_041-TDSURAT_talaswada.png

Plotting:  80%|████████  | 40/50 [00:19<00:04,  2.05plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_011-TDSURAT_gopalkheda.png

Plotting:  82%|████████▏ | 41/50 [00:20<00:04,  2.04plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_023-TDSURAT_surat.png

Plotting:  84%|████████▍ | 42/50 [00:20<00:03,  2.07plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_039-TDSURAT_wankhed.png

Plotting:  86%|████████▌ | 43/50 [00:20<00:03,  2.11plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_012-TDSURAT_yerli.png

Plotting:  88%|████████▊ | 44/50 [00:21<00:02,  2.12plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_042-TDSURAT_dhupeshwar.png

Plotting:  90%|█████████ | 45/50 [00:21<00:02,  2.12plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_038-TDSURAT_kurankheda.png

Plotting:  92%|█████████▏| 46/50 [00:22<00:01,  2.11plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_058-TDSURAT_velda.png

Plotting:  94%|█████████▍| 47/50 [00:22<00:01,  2.16plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_050-TDSURAT_shirpur.png

Plotting:  96%|█████████▌| 48/50 [00:23<00:00,  2.13plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_061-TDSURAT_kholwadkathore.png

Plotting:  98%|█████████▊| 49/50 [00:23<00:00,  2.09plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_008-TDSURAT_dahigaon.png

Plotting: 100%|██████████| 50/50 [00:24<00:00,  2.06plot/s]

Saved: data_fetch_cwc/cwc/tapi/images/CWC_015-TDSURAT_burhanpur.png
Plots generated: 50

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_tapi_2024-04-01_2024-06-07.gpkg (14757 rows)

water_level downloaded in 40.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       51        51         50          0        1            40.4
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------
CWC basin-dispatch summary: 2 basins, 77 stations targeted in total.
Note: per-basin download tables report stations with data in the requested period, so they can be lower than targeted station counts.

#### We can also query the available stations filtered by basin and state names using cwc.stations()

In [2]:
stations_cwc = swift.cwc.stations(basin=['Narmada', 'Tapi'], state=['Gujarat', 'Maharashtra']) # Returns a pandas Dataframe with the stations and their CWC IDs.
stations_cwc

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,001-TDSURAT,BODELI,Orsang,Narmada,Gujarat,Vadodara,"Executive Engineer, Tapi Division, Surat",22.265000,73.727222,68.000,NaN,76.800,80.900,NaN
1,002-TDSURAT,RAJPIPLA,Karjan,Narmada,Gujarat,Narmada,"Executive Engineer, Tapi Division, Surat",21.877778,73.466111,17.000,NaN,26.800,30.300,1994-09-07
2,003-TDSURAT,Garudeshwar,Narmada,Narmada,Gujarat,Narmada,"Executive Engineer, Tapi Division, Surat",21.890000,73.650000,10.000,30.480,31.090,41.645,1970-09-06
3,004-TDSURAT,Bharuch,Narmada,Narmada,Gujarat,Bharuch,"Executive Engineer, Tapi Division, Surat",21.700000,73.000000,0.000,6.705,7.315,12.645,1970-09-06
4,005-TDSURAT,MOTINAROLI,Kim,Narmada,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.237778,72.963333,5.000,NaN,NaN,18.225,2019-08-05
5,006-TDSURAT,CHANWADA,Orsang,Narmada,Gujarat,Vadodara,"Executive Engineer, Tapi Division, Surat",22.050000,73.465278,15.000,NaN,NaN,33.550,NaN
6,008-TDSURAT,DAHIGAON,Girna,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",20.833611,75.423889,215.798,NaN,NaN,222.100,2006-08-08
7,010-TDSURAT,LAKHPURI,Purna,Tapi,Maharashtra,Amravati,"Executive Engineer, Tapi Division, Surat",20.845556,77.360556,259.000,NaN,NaN,271.015,1979-08-10
8,011-TDSURAT,GOPALKHEDA,Purna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.874167,76.991389,236.000,245.000,NaN,252.450,2015-08-06
9,012-TDSURAT,YERLI,Purna,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.936389,76.474167,213.000,221.000,223.000,233.700,2006-08-07
10,013-ukdpune,Anjanari,Kajvi,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Cauvery Division, Bangaluru",16.934722,73.514167,11.000,16.500,17.500,20.500,2019-08-05
11,014-ukdpune,Badlapur,Ulhas,West flowing rivers from Tapi to Tadri,Maharashtra,Thane,"Upper Krishna Division(UKD), Pune",19.162222,73.254167,9.017,16.500,17.500,26.162,2005-07-26
12,015-ukdpune,Belne Bridge,Gad,West flowing rivers from Tapi to Tadri,Maharashtra,Sindudurg,"Cauvery Division, Bangaluru",16.220833,73.594722,8.500,15.500,16.500,20.010,2021-07-23
13,016-TDSURAT,HATHNUR,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.070000,75.950000,207.000,212.000,214.000,NaN,NaN
14,017-TDSURAT,BHUSAWAL,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.068333,75.780278,174.000,NaN,185.320,184.900,NaN
15,017-ukdpune,Mahad,Savitri,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.092222,73.460278,1.000,10.000,11.000,13.800,2021-07-23
16,020-TDSURAT,SARANGKHEDA,Tapi,Tapi,Maharashtra,Nandurbar,"Executive Engineer, Tapi Division, Surat",21.428333,74.527222,108.000,132.050,132.500,127.080,2006-08-08
17,021-TDSURAT,Ukai Reservoir,Tapi,Tapi,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.250000,73.590000,47.853,103.320,105.150,NaN,NaN
18,021-ukdpune,Mangaon,Kal,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.231389,73.283056,3.905,9.255,10.255,10.565,2015-06-15
19,022-TDSURAT,GHALA,Tapi,Tapi,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.297222,73.025278,1.870,NaN,NaN,20.960,2006-08-08
20,022-ukdpune,Nagothane,Amba,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.518889,73.156389,2.000,9.255,10.255,13.750,2005-07-25
21,023-TDSURAT,Surat,Tapi,Tapi,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.200000,72.820000,5.000,8.500,9.500,12.500,2006-08-06
22,023-ukdpune,Niivali,Bav,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Upper Krishna Division(UKD), Pune",17.066944,73.450833,0.455,9.400,11.000,15.155,2021-07-23
23,024-TDSURAT,GADAT,Ambika,West flowing rivers from Tapi to Tadri,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",20.856111,72.984722,1.500,NaN,NaN,13.985,1994-06-16
24,027-TDSURAT,OZERKHEDA,Wagh,West flowing rivers from Tapi to Tadri,Maharashtra,Nashik,"Executive Engineer, Tapi Division, Surat",20.100278,73.271111,80.100,NaN,NaN,96.100,2004-08-04
25,028-TDSURAT,MADHUBAN DAM,Daman Ganga,West flowing rivers from Tapi to Tadri,Gujarat,Valsad,"Executive Engineer, Tapi Division, Surat",20.190000,73.060000,41.000,NaN,NaN,NaN,NaN
26,031-TDSURAT,VAPI,Daman Ganga,West flowing rivers from Tapi to Tadri,Gujarat,Valsad,"Executive Engineer, Tapi Division, Surat",20.370000,72.880000,13.720,18.200,19.200,23.760,2004-08-03
27,033-TDSURAT,PINGALWADA,Dhadhar,Narmada,Gujarat,Vadodara,"Executive Engineer, Tapi Division, Surat",22.110833,73.078611,2.000,NaN,NaN,19.250,NaN
28,034-TDSURAT,MAHUWA,Purna,West flowing rivers from Tapi to Tadri,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.014444,73.140278,9.000,16.000,18.000,24.800,1994-06-16
29,035-TDSURAT,DURVESH,Vaitarna,West flowing rivers from Tapi to Tadri,Maharashtra,Thane,"Executive Engineer, Tapi Division, Surat",19.712500,72.930556,0.000,NaN,NaN,16.130,NaN
30,036-TDSURAT,LOHARA,Mun,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.816389,76.763889,0.000,241.400,243.000,242.750,2019-09-17
31,037-TDSURAT,AKOLA,Morna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.708056,76.993056,269.000,279.500,282.450,282.450,NaN
32,038-TDSURAT,KURANKHEDA,Katepurna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.703056,77.242778,276.000,NaN,NaN,282.900,2022-08-09
33,039-TDSURAT,WANKHED,Tapi,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.988333,76.716667,251.000,253.750,254.900,257.200,2019-08-09
34,040-TDSURAT,PIMPRI,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.128333,75.667222,0.000,NaN,NaN,174.000,NaN
35,041-TDSURAT,TALASWADA,Nalganaga,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.946667,76.203056,0.000,NaN,NaN,227.300,2023-07-19
36,041-ukdpune,Muradpur,Vashisti,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Upper Krishna Division(UKD), Pune",17.539722,73.523889,-5.000,5.000,7.000,8.400,2021-07-23
37,042-TDSURAT,DHUPESHWAR,Purna,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.957500,76.279167,203.000,220.500,222.000,220.400,2023-07-22
38,050-TDSURAT,SHIRPUR,Arunawati,Tapi,Maharashtra,Dhule,"Executive Engineer, Tapi Division, Surat",21.339444,74.890000,141.000,NaN,NaN,149.800,2019-08-09
39,057-TDSURAT,SAGBARA,Tapi,Tapi,Gujarat,Narmada,"Executive Engineer, Tapi Division, Surat",21.543056,73.795000,0.000,NaN,NaN,NaN,NaN
40,058-TDSURAT,VELDA,Tapi,Tapi,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.479167,74.143611,106.000,NaN,NaN,110.000,2019-08-09
41,061-TDSURAT,KHOLWAD(KATHORE),Tapi,Tapi,Gujarat,Surat,"Executive Engineer, Tapi Division, Surat",21.284722,72.950556,0.000,NaN,NaN,13.020,2023-09-18

In [12]:
# We can subset the stations table as well if we are only interested in a few stations for downloading the data.
stations_cwc_subset = stations_cwc[stations_cwc['name'].isin(['BODELI', 'Bharuch'])]
stations_cwc_subset

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,001-TDSURAT,BODELI,Orsang,Narmada,Gujarat,Vadodara,"Executive Engineer, Tapi Division, Surat",22.265,73.727222,68.0,NaN,76.800,80.900,NaN
3,004-TDSURAT,Bharuch,Narmada,Narmada,Gujarat,Bharuch,"Executive Engineer, Tapi Division, Surat",21.700,73.000000,0.0,6.705,7.315,12.645,1970-09-06

In [14]:
# Then we pass this subset table (or the full table) to the fetch function to download the data for these basins.

gdf_cwc = swift.fetch(
    stations_cwc_subset,# the subset dataframe containing the basins and their CWC IDs.
    output_dir="data_fetch_cwc", #location where the downloaded files will be saved.
    start_date="2024-04-01",
    end_date="2024-06-07",
    merge=True, # merges and returns all the downloaded files as a geodataframe.
    plot=True, # plots the station-wise time series of the downloaded data.
    quiet=False, # prints the progress of the download and any warnings or errors encountered during the download process.
    overwrite=True # overwrites any existing files in the output directory with the same name as the downloaded files.
)

# gdf_cwc will contain the merged geodataframe of the downloaded data for the specified basins and variables.

Starting fetch for stations table (rows=2) from 2024-04-01 to 2024-06-07...
Starting CWC download for station=['001-TDSURAT', '004-TDSURAT'] from 2024-04-01 to 2024-06-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 2 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 2/2 [00:00<00:00, 5249.44station/s]
Plotting:   4%|▍         | 1/26 [00:00<00:13,  1.86plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_005-NDBHP_pati.png

Plotting:   8%|▊         | 2/26 [00:01<00:12,  1.95plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_008-NDBHP_dindori.png

Plotting:  12%|█▏        | 3/26 [00:01<00:11,  2.01plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_001-TDSURAT_bodeli.png

Plotting:  15%|█▌        | 4/26 [00:01<00:10,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_003-NDBHP_mohgaon.png

Plotting:  19%|█▉        | 5/26 [00:02<00:10,  1.91plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_014-NDBHP_handia.png

Plotting:  23%|██▎       | 6/26 [00:03<00:10,  1.95plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_003-TDSURAT_garudeshwar.png

Plotting:  27%|██▋       | 7/26 [00:03<00:09,  2.03plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_015-NDBHP_tawa_reservoir.png

Plotting:  31%|███       | 8/26 [00:03<00:08,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_006-TDSURAT_chanwada.png

Plotting:  35%|███▍      | 9/26 [00:04<00:08,  2.07plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_018-ndbhp_mortakka.png

Plotting:  38%|███▊      | 10/26 [00:04<00:07,  2.10plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_006-NDBHP_patan.png

Plotting:  42%|████▏     | 11/26 [00:05<00:07,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_004-TDSURAT_bharuch.png

Plotting:  46%|████▌     | 12/26 [00:05<00:06,  2.03plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_001-NDBHP_mukki.png

Plotting:  50%|█████     | 13/26 [00:06<00:06,  2.04plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_012-NDBHP_barmanghat.png

Plotting:  54%|█████▍    | 14/26 [00:06<00:05,  2.07plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_021-NDBHP_dhulsar.png

Plotting:  58%|█████▊    | 15/26 [00:07<00:05,  2.09plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_020-NDBHP_belkhedi.png

Plotting:  62%|██████▏   | 16/26 [00:07<00:04,  2.09plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_004-NDBHP_chhidgaon.png

Plotting:  65%|██████▌   | 17/26 [00:08<00:04,  2.07plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_033-TDSURAT_pingalwada.png

Plotting:  69%|██████▉   | 18/26 [00:08<00:03,  2.09plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_010-NDBHP_mandla.png

Plotting:  73%|███████▎  | 19/26 [00:09<00:03,  2.05plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_009-ndbhp_manot.png

Plotting:  77%|███████▋  | 20/26 [00:09<00:02,  2.07plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_019-NDBHP_gadarwara.png

Plotting:  81%|████████  | 21/26 [00:10<00:02,  2.13plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_002-NDBHP_bamni.png

Plotting:  85%|████████▍ | 22/26 [00:10<00:01,  2.13plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_017-NDBHP_mandleshwar.png

Plotting:  88%|████████▊ | 23/26 [00:11<00:01,  2.13plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_016-NDBHP_narmadapuram.png

Plotting:  92%|█████████▏| 24/26 [00:11<00:00,  2.12plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_002-TDSURAT_rajpipla.png

Plotting:  96%|█████████▌| 25/26 [00:12<00:00,  2.08plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_007-NDBHP_kogaon.png

Plotting: 100%|██████████| 26/26 [00:12<00:00,  2.06plot/s]

Saved: data_fetch_cwc/cwc/narmada/images/CWC_005-TDSURAT_motinaroli.png
Plots generated: 26
Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_narmada_gujarat_2024-04-01_2024-06-07.gpkg (555 rows)

water_level downloaded in 13.5 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       2         2          2           0        0            13.5
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------

### Using cwc.download()

In [18]:
gdf_cwc = swift.cwc.download(
    basin=['Narmada',  'Tapi'],# basins for which the data needs to be downloaded    
    # stations=['BODELI', 'Bharuch'], 
    # # if the basin is not specified, the stations for which the data needs to be downloaded;
    # # if not specified, data for all stations in the specified basins will be downloaded
    start_date='2024-01-01',
    end_date='2024-01-07',
    merge=True,
    plot=True,
    quiet=False,
    overwrite=True
)
gdf_cwc.head()

Starting CWC download for station=None from 2024-01-01 to 2024-01-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 77 | Format: CSV | Time range: 2024–2024
Basin filter: Narmada, Tapi
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 77/77 [00:07<00:00,  9.78station/s]
Plotting:   1%|▏         | 1/74 [00:05<07:12,  5.93s/plot]

Saved: output/cwc/tapi/images/CWC_043-TDSURAT_nawtha.png

Plotting:   3%|▎         | 2/74 [00:06<03:36,  3.00s/plot]

Saved: output/cwc/tapi/images/CWC_020-TDSURAT_sarangkheda.png

Plotting:   4%|▍         | 3/74 [00:07<02:12,  1.86s/plot]

Saved: output/cwc/tapi/images/CWC_017-TDSURAT_bhusawal.png

Plotting:   5%|▌         | 4/74 [00:08<01:53,  1.63s/plot]

Saved: output/cwc/tapi/images/CWC_036-TDSURAT_lohara.png

Plotting:   7%|▋         | 5/74 [00:09<01:24,  1.23s/plot]

Saved: output/cwc/tapi/images/CWC_040-TDSURAT_pimpri.png
Skipping (missing columns): 022-TDSURAT_ghala.csv

Plotting:   9%|▉         | 7/74 [00:09<00:51,  1.30plot/s]

Saved: output/cwc/tapi/images/CWC_037-TDSURAT_akola.png

Plotting:  11%|█         | 8/74 [00:10<00:48,  1.36plot/s]

Saved: output/cwc/tapi/images/CWC_021-TDSURAT_ukai_reservoir.png
Skipping (missing columns): 013-TDSURAT_teska.csv

Plotting:  14%|█▎        | 10/74 [00:10<00:33,  1.91plot/s]

Saved: output/cwc/tapi/images/CWC_014-TDSURAT_dedtalai.png

Plotting:  15%|█▍        | 11/74 [00:11<00:33,  1.87plot/s]

Saved: output/cwc/tapi/images/CWC_016-TDSURAT_hathnur.png

Plotting:  16%|█▌        | 12/74 [00:12<00:34,  1.82plot/s]

Saved: output/cwc/tapi/images/CWC_010-TDSURAT_lakhpuri.png

Plotting:  18%|█▊        | 13/74 [00:12<00:32,  1.86plot/s]

Saved: output/cwc/tapi/images/CWC_041-TDSURAT_talaswada.png
Skipping (missing columns): 011-TDSURAT_gopalkheda.csv

Plotting:  20%|██        | 15/74 [00:13<00:26,  2.26plot/s]

Saved: output/cwc/tapi/images/CWC_023-TDSURAT_surat.png

Plotting:  22%|██▏       | 16/74 [00:13<00:26,  2.15plot/s]

Saved: output/cwc/tapi/images/CWC_039-TDSURAT_wankhed.png
Skipping (missing columns): 012-TDSURAT_yerli.csv

Plotting:  24%|██▍       | 18/74 [00:14<00:21,  2.60plot/s]

Saved: output/cwc/tapi/images/CWC_042-TDSURAT_dhupeshwar.png

Plotting:  26%|██▌       | 19/74 [00:14<00:23,  2.36plot/s]

Saved: output/cwc/tapi/images/CWC_038-TDSURAT_kurankheda.png

Plotting:  27%|██▋       | 20/74 [00:15<00:24,  2.22plot/s]

Saved: output/cwc/tapi/images/CWC_058-TDSURAT_velda.png

Plotting:  28%|██▊       | 21/74 [00:15<00:25,  2.10plot/s]

Saved: output/cwc/tapi/images/CWC_050-TDSURAT_shirpur.png
Skipping (missing columns): 008-TDSURAT_dahigaon.csv

Plotting:  31%|███       | 23/74 [00:16<00:19,  2.55plot/s]

Saved: output/cwc/tapi/images/CWC_015-TDSURAT_burhanpur.png

Plotting:  32%|███▏      | 24/74 [00:17<00:21,  2.37plot/s]

Saved: output/cwc/narmada/images/CWC_005-NDBHP_pati.png

Plotting:  34%|███▍      | 25/74 [00:17<00:23,  2.09plot/s]

Saved: output/cwc/narmada/images/CWC_008-NDBHP_dindori.png

Plotting:  35%|███▌      | 26/74 [00:18<00:23,  2.08plot/s]

Saved: output/cwc/narmada/images/CWC_001-TDSURAT_bodeli.png

Plotting:  36%|███▋      | 27/74 [00:18<00:23,  2.04plot/s]

Saved: output/cwc/narmada/images/CWC_003-NDBHP_mohgaon.png

Plotting:  38%|███▊      | 28/74 [00:19<00:22,  2.04plot/s]

Saved: output/cwc/narmada/images/CWC_014-NDBHP_handia.png

Plotting:  39%|███▉      | 29/74 [00:19<00:22,  2.03plot/s]

Saved: output/cwc/narmada/images/CWC_003-TDSURAT_garudeshwar.png

Plotting:  41%|████      | 30/74 [00:20<00:22,  1.95plot/s]

Saved: output/cwc/narmada/images/CWC_015-NDBHP_tawa_reservoir.png

Plotting:  42%|████▏     | 31/74 [00:20<00:21,  1.98plot/s]

Saved: output/cwc/narmada/images/CWC_006-TDSURAT_chanwada.png

Plotting:  43%|████▎     | 32/74 [00:21<00:23,  1.82plot/s]

Saved: output/cwc/narmada/images/CWC_018-ndbhp_mortakka.png

Plotting:  45%|████▍     | 33/74 [00:21<00:21,  1.87plot/s]

Saved: output/cwc/narmada/images/CWC_006-NDBHP_patan.png

Plotting:  46%|████▌     | 34/74 [00:22<00:22,  1.74plot/s]

Saved: output/cwc/narmada/images/CWC_004-TDSURAT_bharuch.png

Plotting:  47%|████▋     | 35/74 [00:22<00:20,  1.89plot/s]

Saved: output/cwc/narmada/images/CWC_001-NDBHP_mukki.png

Plotting:  49%|████▊     | 36/74 [00:23<00:19,  1.94plot/s]

Saved: output/cwc/narmada/images/CWC_012-NDBHP_barmanghat.png

Plotting:  50%|█████     | 37/74 [00:23<00:18,  1.98plot/s]

Saved: output/cwc/narmada/images/CWC_021-NDBHP_dhulsar.png

Plotting:  51%|█████▏    | 38/74 [00:24<00:18,  1.96plot/s]

Saved: output/cwc/narmada/images/CWC_020-NDBHP_belkhedi.png

Plotting:  53%|█████▎    | 39/74 [00:24<00:17,  1.97plot/s]

Saved: output/cwc/narmada/images/CWC_004-NDBHP_chhidgaon.png

Plotting:  54%|█████▍    | 40/74 [00:25<00:18,  1.88plot/s]

Saved: output/cwc/narmada/images/CWC_033-TDSURAT_pingalwada.png

Plotting:  55%|█████▌    | 41/74 [00:26<00:18,  1.77plot/s]

Saved: output/cwc/narmada/images/CWC_010-NDBHP_mandla.png

Plotting:  57%|█████▋    | 42/74 [00:26<00:17,  1.83plot/s]

Saved: output/cwc/narmada/images/CWC_009-ndbhp_manot.png

Plotting:  58%|█████▊    | 43/74 [00:27<00:16,  1.90plot/s]

Saved: output/cwc/narmada/images/CWC_019-NDBHP_gadarwara.png

Plotting:  59%|█████▉    | 44/74 [00:27<00:15,  1.95plot/s]

Saved: output/cwc/narmada/images/CWC_002-NDBHP_bamni.png

Plotting:  61%|██████    | 45/74 [00:28<00:15,  1.93plot/s]

Saved: output/cwc/narmada/images/CWC_017-NDBHP_mandleshwar.png

Plotting:  62%|██████▏   | 46/74 [00:28<00:15,  1.84plot/s]

Saved: output/cwc/narmada/images/CWC_016-NDBHP_narmadapuram.png

Plotting:  64%|██████▎   | 47/74 [00:29<00:14,  1.88plot/s]

Saved: output/cwc/narmada/images/CWC_002-TDSURAT_rajpipla.png

Plotting:  65%|██████▍   | 48/74 [00:29<00:13,  1.93plot/s]

Saved: output/cwc/narmada/images/CWC_007-NDBHP_kogaon.png

Plotting:  66%|██████▌   | 49/74 [00:30<00:12,  1.98plot/s]

Saved: output/cwc/narmada/images/CWC_005-TDSURAT_motinaroli.png

Plotting:  68%|██████▊   | 50/74 [00:30<00:13,  1.84plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_013-ukdpune_anjanari.png
Skipping (missing columns): 024-TDSURAT_gadat.csv

Plotting:  70%|███████   | 52/74 [00:31<00:11,  2.00plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_018-SWRDKOCHI_malakkara.png

Plotting:  72%|███████▏  | 53/74 [00:32<00:11,  1.89plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_041-ukdpune_muradpur.png

Plotting:  73%|███████▎  | 54/74 [00:33<00:11,  1.68plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_013-SWRDKOCHI_kalampur.png

Plotting:  74%|███████▍  | 55/74 [00:33<00:10,  1.76plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_028-SWRDKOCHI_kalathukadavu.png

Plotting:  76%|███████▌  | 56/74 [00:34<00:09,  1.84plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_014-SWRDKOCHI_ramamangalam.png

Plotting:  77%|███████▋  | 57/74 [00:34<00:09,  1.88plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_014-ukdpune_badlapur.png

Plotting:  78%|███████▊  | 58/74 [00:35<00:08,  1.88plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_025-SWRDKOCHI_peruvampadam.png

Plotting:  82%|████████▏ | 61/74 [00:35<00:04,  3.15plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_021-ukdpune_mangaon.png
Skipping (missing columns): 015-ukdpune_belne_bridge.csv
Skipping (missing columns): 005-SWRDKOCHI_kuniyil.csv

Plotting:  84%|████████▍ | 62/74 [00:36<00:04,  2.49plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_022-ukdpune_nagothane.png

Plotting:  85%|████████▌ | 63/74 [00:37<00:05,  2.19plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_015-SWRDKOCHI_kidangoor.png

Plotting:  86%|████████▋ | 64/74 [00:37<00:04,  2.03plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_027-TDSURAT_ozerkheda.png

Plotting:  88%|████████▊ | 65/74 [00:38<00:04,  1.93plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_027-ukdpune_collem.png

Plotting:  89%|████████▉ | 66/74 [00:38<00:04,  1.88plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_026--ukdpune_ganjem.png

Plotting:  91%|█████████ | 67/74 [00:39<00:03,  1.86plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_023-ukdpune_niivali.png

Plotting:  92%|█████████▏| 68/74 [00:39<00:03,  1.84plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_035-TDSURAT_durvesh.png

Plotting:  93%|█████████▎| 69/74 [00:40<00:02,  1.88plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_038-SWRDKOCHI_madamon.png

Plotting:  95%|█████████▍| 70/74 [00:41<00:02,  1.81plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_028-TDSURAT_madhuban_dam.png

Plotting:  96%|█████████▌| 71/74 [00:41<00:01,  1.71plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_035-SWRDKOCHI_pullakkayar.png

Plotting:  97%|█████████▋| 72/74 [00:42<00:01,  1.76plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_034-TDSURAT_mahuwa.png

Plotting:  99%|█████████▊| 73/74 [00:42<00:00,  1.74plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_031-TDSURAT_vapi.png

Plotting: 100%|██████████| 74/74 [00:43<00:00,  1.70plot/s]

Saved: output/cwc/west_flowing_rivers_from_tapi_to_tadri/images/CWC_017-ukdpune_mahad.png
Plots generated: 74

Saved GeoPackage: output/cwc/cwc_waterlevel_all_stations_2024-01-01_2024-01-07.gpkg (1532799 rows)

water_level downloaded in 94.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Selected  Attempted  Downloaded  Skipped  NoData/Fail  Time(s)
-------------------------------------------------------------
water_level       77        77         71          0        6            94.6
-------------------------------------------------------------
Output directory: output/cwc
-------------------------------------------------------------

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,020-NDBHP,2012-05-31 14:00:00,342.45,2.4499999999999886,m,22.928,79.34,POINT (79.34 22.928),all_stations
1,020-NDBHP,2016-06-01 00:00:00,341.04,1.0400000000000205,m,22.928,79.34,POINT (79.34 22.928),all_stations
2,020-NDBHP,2016-06-01 01:00:00,341.04,1.0400000000000205,m,22.928,79.34,POINT (79.34 22.928),all_stations
3,020-NDBHP,2016-06-01 02:00:00,341.04,1.0400000000000205,m,22.928,79.34,POINT (79.34 22.928),all_stations
4,020-NDBHP,2016-06-01 03:00:00,341.04,1.0400000000000205,m,22.928,79.34,POINT (79.34 22.928),all_stations

# Merging into a Geopackage (.gpkg)
- If we set merge = False while fetching the data, we can later use merge_only() to generate the merged geopackage.

- The input_dir in this case would be the folder where the previously downloaded csv/xlsx files are present.

In [ ]:
dg = swift.merge_only(
    mode='cwc', # mode = 'cwc' when merging cwc data 
    input_dir="data_fetch_cwc", 
    output_dir='merged_cwc') 

# the merged geopackage file will be saved in the output directory specified (merged_cwc in this case) 
# and a geodataframe containing the merged data will be returned.
dg

Saved GeoPackage: merged_cwc/cwc/cwc_waterlevel_tapi.gpkg (6637 rows)
Saved GeoPackage: merged_cwc/cwc/cwc_waterlevel_narmada.gpkg (8194 rows)
Saved GeoPackage: merged_cwc/cwc/cwc_waterlevel_west_flowing_rivers_from_tapi_to_tadri.gpkg (8120 rows)

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,043-TDSURAT,2024-04-02 08:00:00,236.540,9.540,m,21.432500,76.437778,POINT (76.43778 21.4325),None
1,043-TDSURAT,2024-04-02 13:00:00,236.540,9.540,m,21.432500,76.437778,POINT (76.43778 21.4325),None
2,043-TDSURAT,2024-04-02 18:00:00,236.540,9.540,m,21.432500,76.437778,POINT (76.43778 21.4325),None
3,043-TDSURAT,2024-04-03 08:00:00,236.540,9.540,m,21.432500,76.437778,POINT (76.43778 21.4325),None
4,043-TDSURAT,2024-04-03 13:00:00,236.540,9.540,m,21.432500,76.437778,POINT (76.43778 21.4325),None
...,...,...,...,...,...,...,...,...,...
22946,017-ukdpune,2024-06-06 20:00:00,2.845,1.845,m,18.092222,73.460278,POINT (73.46028 18.09222),west_flowing_rivers_from_tapi_to_tadri
22947,017-ukdpune,2024-06-06 21:00:00,2.845,1.845,m,18.092222,73.460278,POINT (73.46028 18.09222),west_flowing_rivers_from_tapi_to_tadri
22948,017-ukdpune,2024-06-06 22:00:00,2.845,1.845,m,18.092222,73.460278,POINT (73.46028 18.09222),west_flowing_rivers_from_tapi_to_tadri
22949,017-ukdpune,2024-06-06 23:00:00,2.845,1.845,m,18.092222,73.460278,POINT (73.46028 18.09222),west_flowing_rivers_from_tapi_to_tadri
22950,017-ukdpune,2024-06-07 00:00:00,2.845,1.845,m,18.092222,73.460278,POINT (73.46028 18.09222),west_flowing_rivers_from_tapi_to_tadri

In [2]:
dh = swift.merge_only(mode='wris', # mode = 'wris' when merging wris data 
 input_dir="data_fetch_wris",
 output_dir='merged_wris', 
 variable=['sediment', 'water_level']) # If variable is not specified, all variables in the downloaded files will be merged and returned in the geodataframe.


# the merged geopackage file will be saved in the output directory specified (merged_wris in this case) 
# and a geodataframe containing the merged data will be returned.
dh

Saved GeoPackage: merged_wris/wris/godavari_water_level.gpkg (23123 rows)
No station files found: data_fetch_wris/wris/godavari/sediment
Saved GeoPackage: merged_wris/wris/cauvery_water_level.gpkg (38141 rows)
Saved GeoPackage: merged_wris/wris/cauvery_sediment.gpkg (688 rows)

,station_code,time,wl,lat,lon,geometry,basin,variable,sed
0,020-ugdhyd,2024-04-01 08:00:00,352.619995,18.5456,77.5775,POINT (77.5775 18.5456),godavari,water_level,NaN
1,020-ugdhyd,2024-04-01 13:00:00,352.619995,18.5456,77.5775,POINT (77.5775 18.5456),godavari,water_level,NaN
2,020-ugdhyd,2024-04-01 18:00:00,352.619995,18.5456,77.5775,POINT (77.5775 18.5456),godavari,water_level,NaN
3,020-ugdhyd,2024-04-02 08:00:00,352.619995,18.5456,77.5775,POINT (77.5775 18.5456),godavari,water_level,NaN
4,020-ugdhyd,2024-04-02 13:00:00,352.619995,18.5456,77.5775,POINT (77.5775 18.5456),godavari,water_level,NaN
...,...,...,...,...,...,...,...,...,...
61947,020-CDBNG,2024-06-07 20:00:00,0.450000,12.4119,77.1928,POINT (77.1928 12.4119),cauvery,water_level,NaN
61948,020-CDBNG,2024-06-07 21:00:00,0.450000,12.4119,77.1928,POINT (77.1928 12.4119),cauvery,water_level,NaN
61949,020-CDBNG,2024-06-07 22:00:00,0.450000,12.4119,77.1928,POINT (77.1928 12.4119),cauvery,water_level,NaN
61950,020-CDBNG,2024-06-07 23:00:00,0.450000,12.4119,77.1928,POINT (77.1928 12.4119),cauvery,water_level,NaN
61951,020-CDBNG,2024-06-08 00:00:00,0.450000,12.4119,77.1928,POINT (77.1928 12.4119),cauvery,water_level,NaN

# Generating Time series Plots

- If we set plot = False while fetching the data, we can later use plot_only() to generate the merged geopackage.

- The input_dir in this case would be the folder where the previously downloaded csv/xlsx files are present.

- plot_only()

In [ ]:
swift.plot_only (mode='cwc', # mode = 'cwc' when plotting cwc data
 input_dir='data_fetch_cwc',
 output_dir='plots_cwc',
    variable=['water_level'], # in cwc mode the variable argument will be ignored.
    plot_svg=True ,#svg file can also be generated
    moving_average=True # adds a moving-average overlay to the plot
    )

/tmp/ipykernel_1681460/1662655967.py:1: UserWarning: swift.plot_only(mode='cwc', ...) ignores variable; CWC data only has water levels.
  swift.plot_only (mode='cwc', # mode = 'cwc' when plotting cwc data

Plot-only mode enabled.

Scanning CWC stations: 76
Saved: plots_cwc/cwc/tapi/CWC_043-TDSURAT_nawtha.png
Saved: plots_cwc/cwc/tapi/CWC_020-TDSURAT_sarangkheda.png
Saved: plots_cwc/cwc/tapi/CWC_017-TDSURAT_bhusawal.png
Saved: plots_cwc/cwc/tapi/CWC_036-TDSURAT_lohara.png
Saved: plots_cwc/cwc/tapi/CWC_040-TDSURAT_pimpri.png
Saved: plots_cwc/cwc/tapi/CWC_022-TDSURAT_ghala.png
Saved: plots_cwc/cwc/tapi/CWC_037-TDSURAT_akola.png
Saved: plots_cwc/cwc/tapi/CWC_021-TDSURAT_ukai_reservoir.png
Saved: plots_cwc/cwc/tapi/CWC_013-TDSURAT_teska.png
Saved: plots_cwc/cwc/tapi/CWC_014-TDSURAT_dedtalai.png
Saved: plots_cwc/cwc/tapi/CWC_016-TDSURAT_hathnur.png
Saved: plots_cwc/cwc/tapi/CWC_010-TDSURAT_lakhpuri.png
Saved: plots_cwc/cwc/tapi/CWC_041-TDSURAT_talaswada.png
Saved: plots_cwc/cwc/tapi/CWC_011-TDSURAT_gopalkheda.png
Saved: plots_cwc/cwc/tapi/CWC_023-TDSURAT_surat.png
Saved: plots_cwc/cwc/tapi/CWC_039-TDSURAT_wankhed.png
Saved: plots_cwc/cwc/tapi/CWC_012-TDSURAT_yerli.png
Saved: plots_cwc/cwc/tapi/CWC_042-TDSURAT_dhupeshwar.png
Saved: plots_cwc/cwc/tapi/CWC_038-TDSURAT_kurankheda.png
Saved: plots_cwc/cwc/tapi/CWC_058-TDSURAT_velda.png
Saved: plots_cwc/cwc/tapi/CWC_050-TDSURAT_shirpur.png
Saved: plots_cwc/cwc/tapi/CWC_061-TDSURAT_kholwadkathore.png
Saved: plots_cwc/cwc/tapi/CWC_008-TDSURAT_dahigaon.png
Saved: plots_cwc/cwc/tapi/CWC_015-TDSURAT_burhanpur.png
Saved: plots_cwc/cwc/narmada/CWC_005-NDBHP_pati.png
Saved: plots_cwc/cwc/narmada/CWC_008-NDBHP_dindori.png
Saved: plots_cwc/cwc/narmada/CWC_001-TDSURAT_bodeli.png
Saved: plots_cwc/cwc/narmada/CWC_003-NDBHP_mohgaon.png
Saved: plots_cwc/cwc/narmada/CWC_014-NDBHP_handia.png
Saved: plots_cwc/cwc/narmada/CWC_003-TDSURAT_garudeshwar.png
Saved: plots_cwc/cwc/narmada/CWC_015-NDBHP_tawa_reservoir.png
Saved: plots_cwc/cwc/narmada/CWC_006-TDSURAT_chanwada.png
Saved: plots_cwc/cwc/narmada/CWC_018-ndbhp_mortakka.png
Saved: plots_cwc/cwc/narmada/CWC_006-NDBHP_patan.png
Saved: plots_cwc/cwc/narmada/CWC_004-TDSURAT_bharuch.png
Saved: plots_cwc/cwc/narmada/CWC_001-NDBHP_mukki.png
Saved: plots_cwc/cwc/narmada/CWC_012-NDBHP_barmanghat.png
Saved: plots_cwc/cwc/narmada/CWC_021-NDBHP_dhulsar.png
Saved: plots_cwc/cwc/narmada/CWC_020-NDBHP_belkhedi.png
Saved: plots_cwc/cwc/narmada/CWC_004-NDBHP_chhidgaon.png
Saved: plots_cwc/cwc/narmada/CWC_033-TDSURAT_pingalwada.png
Saved: plots_cwc/cwc/narmada/CWC_010-NDBHP_mandla.png
Saved: plots_cwc/cwc/narmada/CWC_009-ndbhp_manot.png
Saved: plots_cwc/cwc/narmada/CWC_019-NDBHP_gadarwara.png
Saved: plots_cwc/cwc/narmada/CWC_002-NDBHP_bamni.png
Saved: plots_cwc/cwc/narmada/CWC_017-NDBHP_mandleshwar.png
Saved: plots_cwc/cwc/narmada/CWC_016-NDBHP_narmadapuram.png
Saved: plots_cwc/cwc/narmada/CWC_002-TDSURAT_rajpipla.png
Saved: plots_cwc/cwc/narmada/CWC_007-NDBHP_kogaon.png
Saved: plots_cwc/cwc/narmada/CWC_005-TDSURAT_motinaroli.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_013-ukdpune_anjanari.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_024-TDSURAT_gadat.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_018-SWRDKOCHI_malakkara.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_041-ukdpune_muradpur.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_032-TDSURAT_daman.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_013-SWRDKOCHI_kalampur.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_028-SWRDKOCHI_kalathukadavu.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_014-SWRDKOCHI_ramamangalam.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_014-ukdpune_badlapur.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_025-SWRDKOCHI_peruvampadam.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_021-ukdpune_mangaon.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_015-ukdpune_belne_bridge.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_005-SWRDKOCHI_kuniyil.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_022-ukdpune_nagothane.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_015-SWRDKOCHI_kidangoor.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_027-TDSURAT_ozerkheda.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_027-ukdpune_collem.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_026--ukdpune_ganjem.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_023-ukdpune_niivali.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_035-TDSURAT_durvesh.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_038-SWRDKOCHI_madamon.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_028-TDSURAT_madhuban_dam.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_035-SWRDKOCHI_pullakkayar.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_034-TDSURAT_mahuwa.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_031-TDSURAT_vapi.png
Saved: plots_cwc/cwc/west_flowing_rivers_from_tapi_to_tadri/CWC_017-ukdpune_mahad.png

Plots generated: 76

In [6]:
swift.plot_only (mode='wris', # mode = 'cwc' when plotting cwc data
 input_dir='data_fetch_wris',
 output_dir='plots_wris',
    variable=['sediment','water_level'], # in cwc mode the variable argument will be ignored.
    plot_svg=True ,#svg file can also be generated
    moving_average=True ,
    window=30 # adds a moving-average overlay to the plot
    )

TypeError: plot_only() got an unexpected keyword argument 'window'

In [9]:
# Display all unique station names to help select the correct ones for subsetting.
print(stations_cwc['name'].unique())

<StringArray>
[          'BODELI',         'RAJPIPLA',      'Garudeshwar',
          'Bharuch',       'MOTINAROLI',         'CHANWADA',
         'DAHIGAON',         'LAKHPURI',       'GOPALKHEDA',
            'YERLI',         'Anjanari',         'Badlapur',
     'Belne Bridge',          'HATHNUR',         'BHUSAWAL',
            'Mahad',      'SARANGKHEDA',   'Ukai Reservoir',
          'Mangaon',            'GHALA',        'Nagothane',
            'Surat',          'Niivali',            'GADAT',
        'OZERKHEDA',     'MADHUBAN DAM',             'VAPI',
       'PINGALWADA',           'MAHUWA',          'DURVESH',
           'LOHARA',            'AKOLA',       'KURANKHEDA',
          'WANKHED',           'PIMPRI',        'TALASWADA',
         'Muradpur',       'DHUPESHWAR',          'SHIRPUR',
          'SAGBARA',            'VELDA', 'KHOLWAD(KATHORE)']
Length: 42, dtype: str