In [30]:
import swift_app as swift
import pandas as pd
import glob

In [31]:
import importlib
import swift_app.api as _api
importlib.reload(_api)
importlib.reload(swift)

In [9]:
basins = swift.wris.basins(variable="sediment")
basins

SWIFT Table
Rows: 17 | Columns: 3
----------------------------------------
    id                                              basin  variable
0    1                              Brahmani and Baitarni  sediment
1    2                                            Cauvery  sediment
2    3    East flowing rivers between Mahanadi and Pennar  sediment
3    4  East flowing rivers between Pennar and Kanyaku...  sediment
4    5                                           Godavari  sediment
5    6                                            Krishna  sediment
6    7                                           Mahanadi  sediment
7    8                                               Mahi  sediment
8    9  Minor rivers draining into Myanmar and Bangladesh  sediment
9   10                                            Narmada  sediment
10  11                                             Pennar  sediment
11  12                                          Sabarmati  sediment
12  13                                       Subernarekha  sediment
13  14                                               Tapi  sediment
14  15      West flowing rivers from Tadri to Kanyakumari  sediment
15  16             West flowing rivers from Tapi to Tadri  sediment
16  17  West flowing rivers of Kutch and Saurashtra in...  sediment

In [33]:
basins = swift.cwc.basins()
basins

SWIFT Table
Rows: 22 | Columns: 2
----------------------------------------
                                                basin  station_count
0                                    Barak and Others             42
1                               Brahmani and Baitarni             21
2                                         Brahmaputra            139
3                                             Cauvery             53
4     East flowing rivers between Mahanadi and Pennar             21
5   East flowing rivers between Pennar and Kanyaku...             39
6                                               Ganga            537
7                                            Godavari             90
8                                               Indus             18
9                                             Krishna             85
10                                           Mahanadi             60
11                                               Mahi             12
12  Minor rivers draining into Myanmar and Bangladesh              4
13                                            Narmada             26
14                                             Pennar             13
15                                          Sabarmati              6
16                                       Subernarekha             20
17                                               Tapi             25
18      West flowing rivers from Tadri to Kanyakumari             33
19             West flowing rivers from Tapi to Tadri             26
20  West flowing rivers of Kutch and Saurashtra in...             10
21                                       Yamuna Basin              1

In [27]:
print(basins.attrs)
print(basins.columns)

{'source': 'cwc', 'fetch_source': 'cwc', 'type': 'basins', 'basin': ['Barak and Others', 'Brahmani and Baitarni', 'Brahmaputra', 'Cauvery', 'East flowing rivers between Mahanadi and Pennar', 'East flowing rivers between Pennar and Kanyakumari', 'Ganga', 'Godavari', 'Indus', 'Krishna', 'Mahanadi', 'Mahi', 'Minor rivers draining into Myanmar and Bangladesh', 'Narmada', 'Pennar', 'Sabarmati', 'Subernarekha', 'Tapi', 'West flowing rivers from Tadri to Kanyakumari', 'West flowing rivers from Tapi to Tadri', 'West flowing rivers of Kutch and Saurashtra including Luni', 'Yamuna Basin']}
Index(['basin', 'station_count'], dtype='str')

In [ ]:
basins[0]

KeyError: 0

In [ ]:
# Test fetch() from CWC station table
swift.fetch(
    basins,
    output_dir="data_fetch_cwc",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

In [13]:
stations = swift.wris.stations(basin=["Godavari", "Narmada"], variable=["solar", "sediment"])
stations

Searching the WRIS database... This might take some time.
The station list returned does not guarantee time series data availability for all time periods.

,station_code,station_name,latitude,longitude,river,basin,variable
0,007-ugdhyd,Pachegaon,19.5353,74.8336,Pravara,Godavari,sediment
1,017-ugdhyd,Saigaon,18.0500,77.0497,Manjira,Godavari,sediment
2,020-ugdhyd,Degloor,18.5456,77.5775,Manjira,Godavari,sediment
3,031-ugdhyd,Saloora,18.7033,77.7958,Manjira,Godavari,sediment
4,7D8FED08,Kovvada kalva reservoir,17.2067,81.5142,Kovvadakalva,Godavari,solar
5,7D901252,Vuyyuru,16.3814,80.8530,Seethapalli Vagu,Godavari,solar
6,7D903A6C,Dowlaiswaram,16.9361,81.7850,Gowthami,Godavari,solar
7,004-NDBHP,Chhidgaon,22.4012,77.3086,Ganjal,Narmada,sediment
8,006-TDSURAT,CHANWADA,22.0500,73.4653,Orsang,Narmada,sediment
9,009-ndbhp,Manot,22.7358,80.5131,Narmada,Narmada,sediment
10,01 02 17 002,Tapi at Burhanpur,21.2994,76.2354,Tapi,Narmada,sediment
11,013 NDBHP,Sandia,22.9167,78.3500,Narmada,Narmada,sediment
12,016-NDBHP,Narmadapuram,22.7560,77.7330,Narmada,Narmada,sediment

In [5]:
# Test fetch() from CWC station table
swift.fetch(
    stations,
    output_dir="data_fetch_wris",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:06<00:00,  1.68s/station]

Saved GeoPackage: data_fetch_wris/wris/godavari/Godavari_sediment_2024-04-01_2025-05-07.gpkg (38 rows)

sediment downloaded in 6.7 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          1           1           0           6.7
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------

Plot-only mode enabled.

Plotting godavari / sediment (1 stations)
Saved: data_fetch_wris/wris/godavari/images/sediment/007-ugdhyd_Pachegaon_SEDIM.png

Plots generated: 1

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:04<00:00,  1.41s/station]

Saved GeoPackage: data_fetch_wris/wris/godavari/Godavari_solar_radiation_2024-04-01_2025-05-07.gpkg (37991 rows)

solar_radiation downloaded in 4.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           4.4
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plots generated: 3

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 6/6 [00:06<00:00,  1.13s/station]

Saved GeoPackage: data_fetch_wris/wris/narmada/Narmada_sediment_2024-04-01_2025-05-07.gpkg (1305 rows)

sediment downloaded in 6.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          4           4           0           6.8
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/narmada
-------------------------------------------------------------

Plot-only mode enabled.

Plotting narmada / sediment (4 stations)
Saved: data_fetch_wris/wris/narmada/images/sediment/009-ndbhp_Manot_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/016-NDBHP_Narmadapuram_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/006-TDSURAT_CHANWADA_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/013 NDBHP_ Sandia_SEDIM.png

Plots generated: 4

In [16]:
cwc_for_fetch = swift.cwc.stations(basin=["Godavari", "Krishna"], state = ["Telangana", "Maharashtra"])
cwc_for_fetch

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,001-UKDPUNE,Karad,Krishna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.293611,74.190000,549.915,563.41,567.04,567.162,1976-06-07
1,001-lgdhyd,Somanpally(Seasonal),Maner,Godavari,Telangana,KARIMNAGAR,"Upper Godavari Division(UGD), Hyderabad",18.616667,79.800000,121.000,NaN,NaN,129.020,2023-07-27
2,002-LGDHYD,Kaleswaram,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.820000,79.910000,91.290,103.50,104.75,108.190,2022-07-15
3,002-UKDPUNE,Warunji,Koyna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.272778,74.164722,549.437,562.80,565.20,568.047,1976-06-06
4,003-UKDPUNE,Samdoli (Seasonal),Warna,Krishna,Maharashtra,Sangli,"Upper Krishna Division(UKD), Pune",16.856389,74.496667,528.594,541.95,543.15,546.994,2019-08-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,040-UKDPUNE,Targaon,Krishna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.517778,74.146111,584.000,593.00,594.00,594.850,2019-08-07
83,042-UKD PUNE,NANDRE,Yerala,Krishna,Maharashtra,Sangli,"Upper Krishna Division(UKD), Pune",16.949167,74.529722,532.500,540.17,542.21,548.445,2019-08-08
84,043-UKDPUNE,Rahu,Mula-Mutha,Krishna,Maharashtra,Pune,"Upper Krishna Division(UKD), Pune",18.572222,74.273611,507.000,517.50,518.50,519.550,NaN
85,049-ugdhyd,LAXMI BARRAGE,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.703889,80.089167,0.000,NaN,NaN,NaN,NaN
86,053-UGDHYD,MID MANAIR DAM,Maner,Godavari,Telangana,RAJANNA SIRCILLA,"Upper Godavari Division(UGD), Hyderabad",18.392778,78.961111,0.000,NaN,NaN,NaN,NaN

In [15]:
print(cwc_for_fetch.attrs)

{'source': 'cwc', 'fetch_source': 'cwc', 'basin': ['Godavari', 'Krishna'], 'state': ['Telangana', 'Maharashtra']}

In [4]:
# Test fetch() from CWC station table
swift.fetch(
    cwc_for_fetch,
    output_dir="data_fetch_cwc",
    start_date="2024-01-01",
    end_date="2024-04-01",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Dataset: water_level (CWC)
Mode: CWC download | Stations: 56 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 56/56 [00:00<00:00, 49500.74station/s]
Plotting:   4%|▍         | 2/52 [00:00<00:08,  5.80plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_002-LGDHYD_kaleswaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-WGDNGP_bamni_ballarsha.png

Plotting:   8%|▊         | 4/52 [00:00<00:07,  6.41plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-LGDHYD_sangam_kinnerasani.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-WGDNGP_satrapur.png

Plotting:  12%|█▏        | 6/52 [00:00<00:07,  5.96plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-LGDHYD_dummagudem.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-UGDHYD_mancherial.png

Plotting:  15%|█▌        | 8/52 [00:01<00:06,  6.50plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-WGDNGP_salebardi.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-WGDNGP_mangrul.png

Plotting:  19%|█▉        | 10/52 [00:01<00:06,  6.79plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_007-ugdhyd_pachegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_030-UGDHYD_jannepally.png

Plotting:  23%|██▎       | 12/52 [00:01<00:05,  6.93plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-LGDHYD_eturunagaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_003-ugdhyd_nasik.png

Plotting:  27%|██▋       | 14/52 [00:02<00:05,  7.03plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-ugdhyd_dhalegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_023-UGDHYD_sriram_sagar_reservoir.png

Plotting:  31%|███       | 16/52 [00:02<00:05,  6.95plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-UGDHYD_gangakhed_w-l_station.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-wgdngp_wairagarh.png

Plotting:  35%|███▍      | 18/52 [00:02<00:04,  6.98plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-UGDHYD_kopergaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-UGDHYD_betmogra.png

Plotting:  38%|███▊      | 20/52 [00:02<00:04,  6.97plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_035-UGDHYD_manjlegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-WGDNGP_p.g._bridge.png

Plotting:  42%|████▏     | 22/52 [00:03<00:04,  7.00plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-wgdngp_nandgaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-ugdhyd_kaddam_dam.png

Plotting:  46%|████▌     | 24/52 [00:03<00:04,  6.89plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-WGDNGP_kanhargaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-UGDHYD_nizamsagar_reservoir.png

Plotting:  50%|█████     | 26/52 [00:03<00:03,  6.99plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-ugdhyd_nmd-weir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-wgdngp_ashti.png

Plotting:  54%|█████▍    | 28/52 [00:04<00:03,  6.96plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_036-UGDHYD_yeldari_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-wgdngp_bhatpalli.png

Plotting:  58%|█████▊    | 30/52 [00:04<00:03,  7.03plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_001-lgdhyd_somanpallyseasonal.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-WGDNGP_pauni.png

Plotting:  62%|██████▏   | 32/52 [00:04<00:02,  6.97plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-UGDHYD_gandlapet.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-wgdngp_sitekasa.png

Plotting:  65%|██████▌   | 34/52 [00:04<00:02,  6.99plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-WGDNGP_bhandara.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-lgdhyd_sangam_murredu.png

Plotting:  69%|██████▉   | 36/52 [00:05<00:02,  6.36plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-ugdhyd_purna.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_032-wgdngp_gosikhurd_dam.png

Plotting:  73%|███████▎  | 38/52 [00:05<00:02,  6.74plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-ugdhyd_lasur.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-ugdhyd_bhainsastate_govt._site.png

Plotting:  75%|███████▌  | 39/52 [00:05<00:01,  6.87plot/s]/home/carbform/swift/swift_app/plot_station_timeseries.py:215: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())
Plotting:  77%|███████▋  | 40/52 [00:05<00:01,  6.94plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-UGDHYD_nanded.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_028-wgdngp_sirpur_town.png

Plotting:  81%|████████  | 42/52 [00:06<00:01,  6.89plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_011-WGDNGP_hivra.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-UGDHYD_singur_reservoir.png

Plotting:  85%|████████▍ | 44/52 [00:06<00:01,  6.99plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_034-UGDHYD_mula_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-wgdngp_ghugus.png

Plotting:  88%|████████▊ | 46/52 [00:06<00:00,  7.04plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-UGDHYD_jaikwadi_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-LGDHYD_bhadrachalam.png

Plotting:  92%|█████████▏| 48/52 [00:07<00:00,  6.99plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-wgdngp_mirdapalli.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-WGDNGP_sakmur.png

Plotting:  96%|█████████▌| 50/52 [00:07<00:00,  6.80plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-wgdngp_rajoli.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-ugdhyd_degloor.png

Plotting: 100%|██████████| 52/52 [00:07<00:00,  6.80plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-lgdhyd_perur.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-UGDHYD_zari.png
Plots generated: 52

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_godavari_2024-01-01_2024-04-01.gpkg (12314 rows)

water_level downloaded in 25.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       52          52          0           25.4
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/godavari/stations
-------------------------------------------------------------

Dataset: water_level (CWC)
Mode: CWC download | Stations: 31 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 31/31 [00:00<00:00, 40708.65station/s]
Plotting:   7%|▋         | 2/29 [00:00<00:04,  6.18plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_015-lkdhyd_k._agraharam.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_002-UKDPUNE_warunji.png

Plotting:  14%|█▍        | 4/29 [00:00<00:03,  6.56plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_012-UKDPUNE_wadakbal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_040-UKDPUNE_targaon.png

Plotting:  21%|██        | 6/29 [00:00<00:03,  6.70plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_009-lkdhyd_p.d._jurala.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_001-UKDPUNE_karad.png

Plotting:  28%|██▊       | 8/29 [00:01<00:03,  6.71plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_018-LKDHYD_wadenepally.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_033-UKDPUNE_veer_dam.png

Plotting:  34%|███▍      | 10/29 [00:01<00:02,  7.16plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_017-lkdhyd_nagarjuna_sagar_dam.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_034-LKDHYD_anantharam.png

Plotting:  41%|████▏     | 12/29 [00:01<00:02,  6.78plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_022-LKDHYD_madhira.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_004-UKDPUNE_arjunwad_seasonal.png

Plotting:  48%|████▊     | 14/29 [00:02<00:02,  6.85plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_016-ukdpune_dhond.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_035-UKDPUNE_ujjani_reservoir.png

Plotting:  55%|█████▌    | 16/29 [00:02<00:01,  6.75plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_042-UKD PUNE_nandre.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_040-LKDHYD_valigonda.png

Plotting:  62%|██████▏   | 18/29 [00:02<00:01,  6.75plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_025-ukdpune_phulgaon.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_043-UKDPUNE_rahu.png

Plotting:  69%|██████▉   | 20/29 [00:02<00:01,  6.88plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_029-ukdpune_paragaon.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_005-UKDPUNE_kurundwad.png

Plotting:  76%|███████▌  | 22/29 [00:03<00:00,  7.01plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_003-UKDPUNE_samdoli_seasonal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_026-LKDHYD_halia.png

Plotting:  83%|████████▎ | 24/29 [00:03<00:00,  6.91plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_029-LKDHYD_suddakal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_006-UKDPUNE_terwad_seasonal.png

Plotting:  90%|████████▉ | 26/29 [00:03<00:00,  6.92plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_028-ukdpune_sarati.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_010-ukdpune_narsingpur.png

Plotting:  97%|█████████▋| 28/29 [00:04<00:00,  7.02plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_006-LKDHYD_jewangi.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_019-LKDHYD_dameracherla.png

Plotting: 100%|██████████| 29/29 [00:04<00:00,  6.85plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_011-ukdpune_takli.png
Plots generated: 29
Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_krishna_2024-01-01_2024-04-01.gpkg (7604 rows)

water_level downloaded in 19.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       29          29          0           19.6
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/krishna/stations
-------------------------------------------------------------

In [18]:
dg = swift.merge_only(mode='cwc',input_dir="data_fetch_cwc/", output_dir='test_merge')

Saved GeoPackage: test_merge/cwc/cwc_waterlevel_godavari.gpkg (12314 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_brahmani_and_baitarni.gpkg (56603 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_krishna.gpkg (7604 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_barak_and_others.gpkg (185566 rows)

In [41]:
dg

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,026-LKDHYD,2024-01-01 08:00:00,128.34,0.44,m,16.788056,79.339722,POINT (79.33972 16.78806),None
1,026-LKDHYD,2024-01-01 13:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
2,026-LKDHYD,2024-01-01 18:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
3,026-LKDHYD,2024-01-02 08:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
4,026-LKDHYD,2024-01-02 13:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
...,...,...,...,...,...,...,...,...,...
262082,009-WGDNGP,2024-03-30 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262083,009-WGDNGP,2024-03-30 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262084,009-WGDNGP,2024-03-31 08:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262085,009-WGDNGP,2024-03-31 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262086,009-WGDNGP,2024-03-31 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None

In [6]:
swift.merge_only(mode= 'cwc', input_dir="data_fetch_cwc", variable=["solar"], output_dir='test_merge')

/tmp/ipykernel_1297630/2378545228.py:1: UserWarning: swift.merge_only(mode='cwc', ...) ignores variable; CWC data only has water levels.
  swift.merge_only(mode= 'cwc', input_dir="data_fetch_cwc", variable=["solar"], output_dir='test_merge')

Saved GeoPackage: test_merge/cwc/cwc_waterlevel_godavari.gpkg (12314 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_krishna.gpkg (7604 rows)

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,026-LKDHYD,2024-01-01 08:00:00,128.34,0.44,m,16.788056,79.339722,POINT (79.33972 16.78806),None
1,026-LKDHYD,2024-01-01 13:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
2,026-LKDHYD,2024-01-01 18:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
3,026-LKDHYD,2024-01-02 08:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
4,026-LKDHYD,2024-01-02 13:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
...,...,...,...,...,...,...,...,...,...
19913,009-WGDNGP,2024-03-30 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19914,009-WGDNGP,2024-03-30 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19915,009-WGDNGP,2024-03-31 08:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19916,009-WGDNGP,2024-03-31 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19917,009-WGDNGP,2024-03-31 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None

In [42]:
dh = swift.merge_only(mode= 'wris', input_dir="data_fetch_wris/", variable=["solar", "sediment"], output_dir='test_merge')
dh

Saved GeoPackage: test_merge/wris/godavari_solar_radiation.gpkg (37991 rows)
Saved GeoPackage: test_merge/wris/godavari_sediment.gpkg (38 rows)
Dataset 'solar_radiation' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'sediment' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'solar_radiation' not found in basin: narmada
Saved GeoPackage: test_merge/wris/narmada_sediment.gpkg (1305 rows)
Dataset 'solar_radiation' not found in basin: cauvery
Saved GeoPackage: test_merge/wris/cauvery_sediment.gpkg (4321 rows)
Dataset 'solar_radiation' not found in basin: brahmani and baitarni
Saved GeoPackage: test_merge/wris/brahmani and baitarni_sediment.gpkg (122 rows)

,station_code,time,sed,lat,lon,geometry,basin,variable,solar,unit
0,018-ERDBWN,2024-04-01 08:00:00,0.0870,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
1,018-ERDBWN,2024-07-01 08:00:00,0.0570,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
2,018-ERDBWN,2024-07-02 08:00:00,0.0550,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
3,018-ERDBWN,2024-07-03 08:00:00,0.0610,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
4,018-ERDBWN,2024-07-04 08:00:00,0.0510,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43772,006-TDSURAT,2024-10-27 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43773,006-TDSURAT,2024-10-28 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43774,006-TDSURAT,2024-10-29 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43775,006-TDSURAT,2024-10-30 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43776,006-TDSURAT,2024-10-31 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L

In [22]:
swift.plot_only(mode = 'wris', input_dir="data_fetch_wris/", variable=["solar", 'sediment'], output_dir='test_plot')

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: test_plot/wris/godavari/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plotting godavari / sediment (1 stations)
Saved: test_plot/wris/godavari/sediment/007-ugdhyd_Pachegaon_SEDIM.png
Dataset 'solar_radiation' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'sediment' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'solar_radiation' not found in basin: narmada

Plotting narmada / sediment (4 stations)
Saved: test_plot/wris/narmada/sediment/013 NDBHP_ Sandia_SEDIM.png
Saved: test_plot/wris/narmada/sediment/016-NDBHP_Narmadapuram_SEDIM.png
Saved: test_plot/wris/narmada/sediment/009-ndbhp_Manot_SEDIM.png
Saved: test_plot/wris/narmada/sediment/006-TDSURAT_CHANWADA_SEDIM.png
Dataset 'solar_radiation' not found in basin: cauvery

Plotting cauvery / sediment (17 stations)
Saved: test_plot/wris/cauvery/sediment/014-srdcbe_NALLAMARANPATTY_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/020-CDBNG_T.K.HALLI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png
Dataset 'solar_radiation' not found in basin: brahmani and baitarni

Plotting brahmani and baitarni / sediment (1 stations)
Saved: test_plot/wris/brahmani and baitarni/sediment/018-ERDBWN_Altuma_SEDIM.png

Plots generated: 26

In [23]:
swift.plot_only(mode = 'cwc', input_dir="data_fetch_cwc/", variable=["solar", 'sediment'], output_dir='test_plot')

Saved: test_plot/cwc/barak_and_others/CWC_017-MDSIL_muhammedpur.png
Saved: test_plot/cwc/barak_and_others/CWC_022-MBDGHY_manughat.png
Saved: test_plot/cwc/barak_and_others/CWC_019-MDSIL_patharkandi.png
Saved: test_plot/cwc/barak_and_others/CWC_024- MDSIL_chiripool.png
Saved: test_plot/cwc/barak_and_others/CWC_012-MDSIL_sonamura.png
Saved: test_plot/cwc/barak_and_others/CWC_005-mdsil_haora.png
Saved: test_plot/cwc/barak_and_others/CWC_022-MDSIL_sonamura-ii.png
Saved: test_plot/cwc/barak_and_others/CWC_016-MDSIL_borkhola.png
Saved: test_plot/cwc/barak_and_others/CWC_021-MDSIL_kaliganj.png
Saved: test_plot/cwc/barak_and_others/CWC_028- MDSIL_neairgram.png
Saved: test_plot/cwc/barak_and_others/CWC_002-MDSIL_kamalpur.png
Saved: test_plot/cwc/barak_and_others/CWC_021-MBDGHY_karimganj.png
Saved: test_plot/cwc/barak_and_others/CWC_014-MDSIL_kailashahar_gdsq_site.png
Saved: test_plot/cwc/barak_and_others/CWC_013-MDSIL_belonia.png
Saved: test_plot/cwc/barak_and_others/CWC_004-mdsil_khowai.png
Saved: test_plot/cwc/barak_and_others/CWC_006-MDSIL_gajaria.png
Saved: test_plot/cwc/barak_and_others/CWC_008-MDSIL_anipur.png

Plots generated: 137

In [24]:
# Sanity check: public Python API surface
import swift_app as swift

public_attrs = [
    "wris",
    "cwc",
    "fetch",
    "merge_only",
    "plot_only",
    "datasets",
    "basins",
    "cite",
    "coffee",
]

api_flags = {name: hasattr(swift, name) for name in public_attrs}
api_flags

{'wris': True,
 'cwc': True,
 'fetch': True,
 'merge_only': True,
 'plot_only': True,
 'datasets': False,
 'basins': False,
 'cite': True,
 'coffee': True}

In [14]:
# Test CWC download via public namespace API
swift.wris.download(
    basin="Krishna",
    variable=["solar", "discharge"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_wris_download",
    format="xlsx",
    overwrite=False,
    merge=True,
    plot=True,
    quiet=False,
)

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:00<00:00,  6.39station/s]

Saved GeoPackage: data_wris_download/wris/krishna/Krishna_solar_radiation_2024-01-01_2024-01-07.gpkg (1344 rows)

solar_radiation downloaded in 0.9 seconds

Dataset: discharge
Using cached station discovery

discharge: 100%|██████████| 30/30 [00:14<00:00,  2.13station/s]

Saved GeoPackage: data_wris_download/wris/krishna/Krishna_discharge_2024-01-01_2024-01-07.gpkg (132 rows)

discharge downloaded in 14.1 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   5           5           0           0.9
discharge         19          19          0           14.1
-------------------------------------------------------------
Output directory: data_wris_download/wris/krishna
-------------------------------------------------------------

Plot-only mode enabled.

Plotting krishna / discharge (19 stations)
Saved: data_wris_download/wris/krishna/images/discharge/034-LKDHYD_Anantharam_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/021-LKDHYD_Keesara_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/042-UKD PUNE_NANDRE_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/026-LKDHYD_Halia_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/023-LKDHYD_Paleru Bridge_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/036-LKDHYD_Vikkiralapeta_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/043-UKDPUNE_Rahu_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/006-UKDPUNE_Terwad (Seasonal)_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/002-UKDPUNE_Warunji_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/029-LKDHYD_Suddakal_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/022-LKDHYD_Madhira_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/033-LKDHYD_Munugodu_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/003-UKDPUNE_Samdoli (Seasonal)_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/LKDHYD039_Penuganchi prolu_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/019-LKDHYD_Dameracherla_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/049-CDBNG_LAKKAVALLI_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/032-LKDHYD_VEERLAPALEM_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/040-LKDHYD_VALIGONDA_DISCHARG.png
Saved: data_wris_download/wris/krishna/images/discharge/028-LKDHYD_Doddipadu_DISCHARG.png

Plotting krishna / solar_radiation (5 stations)
Saved: data_wris_download/wris/krishna/images/solar_radiation/KK3GMNB291_Deodurga_SOLAR_RD.png
Saved: data_wris_download/wris/krishna/images/solar_radiation/7D90291A_Prakasam Barrage APSW_SOLAR_RD.png
Saved: data_wris_download/wris/krishna/images/solar_radiation/Patryachiwad_Patryachiwadi_SOLAR_RD.png
Saved: data_wris_download/wris/krishna/images/solar_radiation/KK3GMNB353_Sindhanur_SOLAR_RD.png
Saved: data_wris_download/wris/krishna/images/solar_radiation/Rukadi_Rukadi_SOLAR_RD.png

Plots generated: 24

In [13]:
# Test CWC download via public namespace API
swift.cwc.download(
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_cwc",
    format="csv",
    overwrite=False,
    merge=False,
    plot=False,
    quiet=False,
)

Dataset: water_level (CWC)
Mode: CWC download | Stations: 1284 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 1284/1284 [00:00<00:00, 60600.96station/s]

water_level downloaded in 101.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       1099        1099        0           101.4
-------------------------------------------------------------
Output directory: data_cwc/cwc/stations
-------------------------------------------------------------

In [ ]:
stations_for_fetch = swift.wris.stations(basin="Krishna", variable="solar")
stations_for_fetch

SWIFT Table
Rows: 5 | Columns: 5
----------------------------------------
   station_code           station_name  latitude  longitude          river
0      7D90291A  Prakasam Barrage APSW   16.5061    80.6047  Lower Krishna
1    KK3GMNB291               Deodurga   16.4172    76.9281  Lower Krishna
2    KK3GMNB353              Sindhanur   15.7714    76.7578  Lower Krishna
3  Patryachiwad          Patryachiwadi   16.6161    73.9917     Panchganga
4        Rukadi                 Rukadi   16.7200    74.3556     Panchganga

In [5]:
# Test fetch() from WRIS station table
stations_for_fetch = swift.wris.stations(basin="Krishna", variable="solar")
swift.fetch(
    stations_for_fetch,
    output_dir="data_fetch_wris",
    start_date="2024-01-01",
    end_date="2024-01-07",
    merge=True,
    plot=True,
    quiet=False,
)

Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Dataset: solar_radiation
Using cached station discovery
Stations skipped (already downloaded): 5
Tip: use --overwrite to refresh data.
All stations already downloaded — skipping download step.
Saved GeoPackage: data_fetch_wris/wris/krishna/Krishna_solar_radiation.gpkg (1344 rows)

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   5           0           5           0.1
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/krishna
-------------------------------------------------------------

Plot-only mode enabled.

Plotting krishna / solar_radiation (5 stations)
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/KK3GMNB291_Deodurga_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/Patryachiwad_Patryachiwadi_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/Rukadi_Rukadi_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/7D90291A_Prakasam Barrage APSW_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/KK3GMNB353_Sindhanur_SOLAR_RD.png

Plots generated: 5

In [4]:
cwc_for_fetch.attrs

{'source': 'cwc', 'basin': 'Godavari', 'state': 'Telangana'}

# test gdf returns

In [1]:
import swift_app as swift
import pandas as pd
import glob

In [4]:
gdf = swift.wris.download(
    basin=["Krishna", "Godavari"],
    variable=["solar", "sediment"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir= 'test_gdf',
    plot=False, overwrite=True, merge=True
)

# gdf is a GeoDataFrame with the merged timeseries

Starting WRIS download for basin='Krishna', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:01<00:00,  4.95station/s]

Saved GeoPackage: test_gdf/wris/krishna/Krishna_solar_radiation_2024-01-01_2024-01-07.gpkg (1344 rows)

solar_radiation downloaded in 1.0 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 20/20 [00:14<00:00,  1.41station/s]

Saved GeoPackage: test_gdf/wris/krishna/Krishna_sediment_2024-01-01_2024-01-07.gpkg (17 rows)

sediment downloaded in 14.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   5           5           0           1.0
sediment          5           5           0           14.2
-------------------------------------------------------------
Output directory: test_gdf/wris/krishna
-------------------------------------------------------------
Starting WRIS download for basin='Godavari', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:00<00:00,  3.03station/s]

Saved GeoPackage: test_gdf/wris/godavari/Godavari_solar_radiation_2024-01-01_2024-01-07.gpkg (748 rows)

solar_radiation downloaded in 1.0 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:06<00:00,  1.71s/station]

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           1.0
sediment          0           0           0           6.9
-------------------------------------------------------------
Output directory: test_gdf/wris/godavari
-------------------------------------------------------------

In [5]:
gdf

,station_code,time,solar,lat,lon,geometry,basin,variable,sed
0,Rukadi,2024-01-01 00:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
1,Rukadi,2024-01-01 01:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
2,Rukadi,2024-01-01 02:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
3,Rukadi,2024-01-01 03:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
4,Rukadi,2024-01-01 04:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
...,...,...,...,...,...,...,...,...,...
2104,7D901252,2024-01-07 18:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2105,7D901252,2024-01-07 19:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2106,7D901252,2024-01-07 20:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2107,7D901252,2024-01-07 21:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2108,7D901252,2024-01-08 00:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN

In [ ]:
gdf = swift.merge_only(mode = 'wris', input_dir="output", variable=["solar", "sediment"])

{('Krishna',
  'solar'):       station_code                 time  solar     unit      lat      lon  \
 0           Rukadi  2024-01-01 00:30:00    0.0  watt/m2  16.7200  74.3556
 1           Rukadi  2024-01-01 01:30:00    0.0  watt/m2  16.7200  74.3556
 2           Rukadi  2024-01-01 02:30:00    0.0  watt/m2  16.7200  74.3556
 3           Rukadi  2024-01-01 03:30:00    0.0  watt/m2  16.7200  74.3556
 4           Rukadi  2024-01-01 04:30:00    0.0  watt/m2  16.7200  74.3556
 ...            ...                  ...    ...      ...      ...      ...
 1339  Patryachiwad  2024-01-07 23:00:00    1.0  watt/m2  16.6161  73.9917
 1340  Patryachiwad  2024-01-07 23:15:00    1.0  watt/m2  16.6161  73.9917
 1341  Patryachiwad  2024-01-07 23:30:00    2.0  watt/m2  16.6161  73.9917
 1342  Patryachiwad  2024-01-07 23:45:00    0.0  watt/m2  16.6161  73.9917
 1343  Patryachiwad  2024-01-08 00:00:00    5.0  watt/m2  16.6161  73.9917

                      geometry
 0       POINT (74.3556 16.72)
 1       POINT (74.3556 16.72)
 2       POINT (74.3556 16.72)
 3       POINT (74.3556 16.72)
 4       POINT (74.3556 16.72)
 ...                       ...
 1339  POINT (73.9917 16.6161)
 1340  POINT (73.9917 16.6161)
 1341  POINT (73.9917 16.6161)
 1342  POINT (73.9917 16.6161)
 1343  POINT (73.9917 16.6161)

 [1344 rows x 7 columns],
 ('Krishna',
  'sediment'):     station_code                 time    sed unit      lat      lon  \
 0    003-UKDPUNE  2024-01-01 08:00:00  0.000  g/L  16.8564  74.4967
 1    003-UKDPUNE  2024-01-02 08:00:00  0.000  g/L  16.8564  74.4967
 2    003-UKDPUNE  2024-01-03 08:00:00  0.000  g/L  16.8564  74.4967
 3    003-UKDPUNE  2024-01-04 08:00:00  0.000  g/L  16.8564  74.4967
 4    003-UKDPUNE  2024-01-05 08:00:00  0.000  g/L  16.8564  74.4967
 5    003-UKDPUNE  2024-01-06 08:00:00  0.000  g/L  16.8564  74.4967
 6    003-UKDPUNE  2024-01-07 08:00:00  0.000  g/L  16.8564  74.4967
 7    002-UKDPUNE  2024-01-01 08:00:00  0.000  g/L  17.2728  74.1647
 8    002-UKDPUNE  2024-01-02 08:00:00  0.000  g/L  17.2728  74.1647
 9    002-UKDPUNE  2024-01-03 08:00:00  0.000  g/L  17.2728  74.1647
 10   002-UKDPUNE  2024-01-04 08:00:00  0.000  g/L  17.2728  74.1647
 11   002-UKDPUNE  2024-01-05 08:00:00  0.000  g/L  17.2728  74.1647
 12   002-UKDPUNE  2024-01-06 08:00:00  0.000  g/L  17.2728  74.1647
 13   002-UKDPUNE  2024-01-07 08:00:00  0.000  g/L  17.2728  74.1647
 14     011-cdbmg  2024-01-01 09:00:00  0.013  g/L  13.5225  75.3036
 15    022-LKDHYD  2024-01-01 08:00:00  0.000  g/L  16.9181  80.3589
 16  042-UKD PUNE  2024-01-01 08:00:00  0.000  g/L  16.9492  74.5297

                    geometry
 0   POINT (74.4967 16.8564)
 1   POINT (74.4967 16.8564)
 2   POINT (74.4967 16.8564)
 3   POINT (74.4967 16.8564)
 4   POINT (74.4967 16.8564)
 5   POINT (74.4967 16.8564)
 6   POINT (74.4967 16.8564)
 7   POINT (74.1647 17.2728)
 8   POINT (74.1647 17.2728)
 9   POINT (74.1647 17.2728)
 10  POINT (74.1647 17.2728)
 11  POINT (74.1647 17.2728)
 12  POINT (74.1647 17.2728)
 13  POINT (74.1647 17.2728)
 14  POINT (75.3036 13.5225)
 15  POINT (80.3589 16.9181)
 16  POINT (74.5297 16.9492)  ,
 ('Godavari',
  ('solar',
   'sediment')):     station_code                 time  solar     unit      lat      lon  \
 0       7D8FED08  2024-01-01 00:00:00    0.0  watt/m2  17.2067  81.5142
 1       7D8FED08  2024-01-01 01:00:00    0.0  watt/m2  17.2067  81.5142
 2       7D8FED08  2024-01-01 02:00:00    0.0  watt/m2  17.2067  81.5142
 3       7D8FED08  2024-01-01 03:00:00    0.0  watt/m2  17.2067  81.5142
 4       7D8FED08  2024-01-01 04:00:00    0.0  watt/m2  17.2067  81.5142
 ..           ...                  ...    ...      ...      ...      ...
 743     7D901252  2024-01-07 18:00:00    0.0  watt/m2  16.3814  80.8530
 744     7D901252  2024-01-07 19:00:00    0.0  watt/m2  16.3814  80.8530
 745     7D901252  2024-01-07 20:00:00    0.0  watt/m2  16.3814  80.8530
 746     7D901252  2024-01-07 21:00:00    0.0  watt/m2  16.3814  80.8530
 747     7D901252  2024-01-08 00:00:00    0.0  watt/m2  16.3814  80.8530

                     geometry
 0    POINT (81.5142 17.2067)
 1    POINT (81.5142 17.2067)
 2    POINT (81.5142 17.2067)
 3    POINT (81.5142 17.2067)
 4    POINT (81.5142 17.2067)
 ..                       ...
 743   POINT (80.853 16.3814)
 744   POINT (80.853 16.3814)
 745   POINT (80.853 16.3814)
 746   POINT (80.853 16.3814)
 747   POINT (80.853 16.3814)

 [748 rows x 7 columns]}

In [ ]:
# Test merge_only() with mode-based API (requires existing WRIS output)
from pathlib import Path

if Path("output").exists():
    swift.merge_only(mode="wris", input_dir="output", output_dir="output_merged")
else:
    print("output/ not found; run a WRIS download cell first.")

In [ ]:
# Test plot_only() with mode-based API (requires existing WRIS output)
from pathlib import Path

if Path("output").exists():
    swift.plot_only(mode="wris", input_dir="output", output_dir="output")
else:
    print("output/ not found; run a WRIS download cell first.")

In [3]:
# Test cite() and coffee() helpers (side-effect: print to stdout)
import swift_app as swift

swift.cite()
swift.coffee()

====================================================================

SWIFT — Simple Water Information Fetch Tool
Carbform • carbform.github.io

Version: 1.0.0 — Arctic Amsterdam


   ███████╗██╗    ██╗██╗███████╗████████╗
   ██╔════╝██║    ██║██║██╔════╝╚══██╔══╝
   ███████╗██║ █╗ ██║██║█████╗     ██║
   ╚════██║██║███╗██║██║██╔══╝     ██║
   ███████║╚███╔███╔╝██║██║        ██║
   ╚══════╝ ╚══╝╚══╝ ╚═╝╚═╝        ╚═╝


====================================================================

    If you use SWIFT in your research, please cite:

    Sarat, C., Dash, D., & Kumar, A. (2026).
    SWIFT: Automated Retrieval of Hydrological Station Data
    from India-WRIS and CWC Portals.
    Journal of Open Source Software.

    Repository:
    https://github.com/carbform/swift


        ( (
        ) )
        ........
        |      |]
        \      /
        `----'
        TIME FOR A COFFEE BREAK

Many kinds of monkeys have a strong taste for tea, coffee and spirituous liqueurs. - Charles Darwin

In [25]:
swift.help()

SWIFT Python API help
=====================

Namespaces
----------
- swift.wris.download(basin, variable, ...)
- swift.wris.stations(basin, variable, delay=0.25)
- swift.cwc.download(station=None, ...)
- swift.cwc.stations(station=None, basin=None, river=None, state=None, refresh=False)

Core helpers
------------
- swift.fetch(stations_df, ...)
- swift.merge_only(input_dir=None, output_dir=None, mode=None, variable=None)
- swift.plot_only(input_dir=None, output_dir=None, cwc=False, mode=None, variable=None)

Backward-compatible aliases
---------------------------
- swift.merge(...)
- swift.plot(...)

Utility helpers
---------------
- swift.cite()
- swift.coffee()
- swift.wris.variables()  (WRIS variable table)
- swift.wris.basins(variable=...)  (WRIS basin table; optionally expanded by variable)
- swift.cwc.basins()      (CWC basin table from station metadata)

Quick examples
--------------
1) Download WRIS discharge for Krishna:
    swift.wris.download(basin="Krishna", variable="discharge")

2) Query stations then fetch:
    stations = swift.wris.stations(basin=["Godavari", "Krishna"], variable=["solar", "sediment"])
    swift.fetch(stations, output_dir="output", merge=True, plot=True)

3) Download CWC data:
    swift.cwc.download(station=["040-CDJAPR"], start_date="2024-01-01", end_date="2024-01-07")

Need CLI help instead?
----------------------
Use: swift.cli_help()   # equivalent to `swift -h`

In [43]:
import geopandas as gpd
# Let's check dh since we ran merge_only on WRIS
try:
    print("dh columns:", dh.columns)
    print("dg columns:", dg.columns)
except:
    pass

dh columns: Index(['station_code', 'time', 'sed', 'lat', 'lon', 'geometry', 'basin',
       'variable', 'solar', 'unit'],
      dtype='str')
dg columns: Index(['station_code', 'time', 'wse', 'water_depth', 'unit', 'lat', 'lon',
       'geometry', 'basin'],
      dtype='str')