In [6]:
import swift_app as swift
import pandas as pd
import glob

In [7]:
import importlib
import swift_app.api as _api
importlib.reload(_api)
importlib.reload(swift)

In [3]:
basins_wris = swift.wris.basins(variable="sediment")
basins_wris

SWIFT Table
Rows: 17 | Columns: 3
----------------------------------------
    id                                              basin  variable
0    1                              Brahmani and Baitarni  sediment
1    2                                            Cauvery  sediment
2    3    East flowing rivers between Mahanadi and Pennar  sediment
3    4  East flowing rivers between Pennar and Kanyaku...  sediment
4    5                                           Godavari  sediment
5    6                                            Krishna  sediment
6    7                                           Mahanadi  sediment
7    8                                               Mahi  sediment
8    9  Minor rivers draining into Myanmar and Bangladesh  sediment
9   10                                            Narmada  sediment
10  11                                             Pennar  sediment
11  12                                          Sabarmati  sediment
12  13                                       Subernarekha  sediment
13  14                                               Tapi  sediment
14  15      West flowing rivers from Tadri to Kanyakumari  sediment
15  16             West flowing rivers from Tapi to Tadri  sediment
16  17  West flowing rivers of Kutch and Saurashtra in...  sediment

In [4]:
basins_wris[0:3]

SWIFT Table
Rows: 3 | Columns: 3
----------------------------------------
  id                                            basin  variable
0  1                            Brahmani and Baitarni  sediment
1  2                                          Cauvery  sediment
2  3  East flowing rivers between Mahanadi and Pennar  sediment

In [5]:
basins_cwc = swift.cwc.basins()
basins_cwc

SWIFT Table
Rows: 22 | Columns: 2
----------------------------------------
                                                basin  station_count
0                                    Barak and Others             42
1                               Brahmani and Baitarni             21
2                                         Brahmaputra            139
3                                             Cauvery             53
4     East flowing rivers between Mahanadi and Pennar             21
5   East flowing rivers between Pennar and Kanyaku...             39
6                                               Ganga            537
7                                            Godavari             90
8                                               Indus             18
9                                             Krishna             85
10                                           Mahanadi             60
11                                               Mahi             12
12  Minor rivers draining into Myanmar and Bangladesh              4
13                                            Narmada             26
14                                             Pennar             13
15                                          Sabarmati              6
16                                       Subernarekha             20
17                                               Tapi             25
18      West flowing rivers from Tadri to Kanyakumari             33
19             West flowing rivers from Tapi to Tadri             26
20  West flowing rivers of Kutch and Saurashtra in...             10
21                                       Yamuna Basin              1

In [6]:
basins_cwc[0:3]

SWIFT Table
Rows: 3 | Columns: 2
----------------------------------------
                   basin  station_count
0       Barak and Others             42
1  Brahmani and Baitarni             21
2            Brahmaputra            139

In [55]:
# Test fetch() from CWC basin table
swift.fetch(
    basins_cwc[0:3],
    output_dir="data_fetch_cwc",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Starting fetch for stations table (rows=3) from 2024-04-01 to 2025-05-07...
Starting CWC download for station=['001-MDSIL', '001-MIDSHL', '002-MDSIL', '002-midshl', '003-MDSIL', '004-mdsil', '005-mdsil', '006-MDSIL', '007-MDSIL', '008-MDSIL', '009-MBDGHY', '009-mdsil', '010-MBDGHY', '010-mdsil', '011-MBDGHY', '011-mdsil', '012-MBDGHY', '012-MDSIL', '013-MBDGHY', '013-MDSIL', '014-MDSIL', '015-MBDGHY', '015-MDSIL', '016-MBDGHY', '016-MDSIL', '017-MBDghy', '017-MDSIL', '018-MDSIL', '019-MBDGHY', '019-MDSIL', '020-MDSIL', '021-MBDGHY', '021-MDSIL', '022-MBDGHY', '022-MDSIL', '023-MBDGHY', '023-MDSIL', '024- MDSIL', '026- MDSIL', '027- MDSIL', '028- MDSIL', '030-MBDGHY'] from 2024-04-01 to 2025-05-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 42 | Format: CSV | Time range: 2024–2025
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

/tmp/ipykernel_1345376/186204018.py:2: UserWarning: Fetching CWC data for basin-level input (all stations per basin). Dispatching 3 basins; this may take a long time.
  swift.fetch(
water_level: 100%|██████████| 42/42 [00:00<00:00, 15519.41station/s]
Plotting:   3%|▎         | 1/36 [00:00<00:14,  2.49plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_030-MBDGHY_harangajao.png

Plotting:   6%|▌         | 2/36 [00:00<00:13,  2.48plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_027- MDSIL_kalain.png

Plotting:   8%|▊         | 3/36 [00:01<00:12,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_018-MDSIL_lala.png

Plotting:  11%|█         | 4/36 [00:01<00:12,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_026- MDSIL_sibapur.png

Plotting:  14%|█▍        | 5/36 [00:01<00:11,  2.62plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_001-MIDSHL_dawki.png

Plotting:  17%|█▋        | 6/36 [00:02<00:11,  2.62plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_012-MBDGHY_gharmura.png

Plotting:  19%|█▉        | 7/36 [00:02<00:11,  2.60plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_013-MBDGHY_chotabekra.png

Plotting:  22%|██▏       | 8/36 [00:03<00:10,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_020-MDSIL_kadamtala.png

Plotting:  25%|██▌       | 9/36 [00:03<00:10,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_015-MDSIL_katigorah.png

Plotting:  28%|██▊       | 10/36 [00:03<00:10,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_009-mdsil_monierkhal.png

Plotting:  31%|███       | 11/36 [00:04<00:09,  2.53plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_001-MDSIL_kumarghat_gd_site.png

Plotting:  33%|███▎      | 12/36 [00:04<00:09,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_007-MDSIL_tulargram.png

Plotting:  36%|███▌      | 13/36 [00:05<00:08,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_002-midshl_kharkhana.png

Plotting:  39%|███▉      | 14/36 [00:05<00:08,  2.60plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_010-mdsil_sairang.png

Plotting:  42%|████▏     | 15/36 [00:05<00:08,  2.61plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_011-mdsil_tuirial.png

Plotting:  44%|████▍     | 16/36 [00:06<00:07,  2.62plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_023-MDSIL_sabrum.png

Plotting:  47%|████▋     | 17/36 [00:06<00:07,  2.61plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_019-MBDGHY_amarpur.png

Plotting:  50%|█████     | 18/36 [00:06<00:06,  2.60plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_017-MBDghy_amraghat.png

Plotting:  53%|█████▎    | 19/36 [00:07<00:06,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_003-MDSIL_nutanbazar_gd_site.png

Plotting:  56%|█████▌    | 20/36 [00:07<00:06,  2.56plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_017-MDSIL_muhammedpur.png

Plotting:  58%|█████▊    | 21/36 [00:08<00:05,  2.56plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_022-MBDGHY_manughat.png

Plotting:  61%|██████    | 22/36 [00:08<00:05,  2.63plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_019-MDSIL_patharkandi.png

Plotting:  64%|██████▍   | 23/36 [00:08<00:04,  2.62plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_024- MDSIL_chiripool.png

Plotting:  67%|██████▋   | 24/36 [00:09<00:04,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_012-MDSIL_sonamura.png

Plotting:  69%|██████▉   | 25/36 [00:09<00:04,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_005-mdsil_haora.png

Plotting:  72%|███████▏  | 26/36 [00:10<00:03,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_022-MDSIL_sonamura-ii.png

Plotting:  75%|███████▌  | 27/36 [00:10<00:03,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_016-MDSIL_borkhola.png

Plotting:  78%|███████▊  | 28/36 [00:10<00:03,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_021-MDSIL_kaliganj.png

Plotting:  81%|████████  | 29/36 [00:11<00:02,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_028- MDSIL_neairgram.png

Plotting:  83%|████████▎ | 30/36 [00:11<00:02,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_002-MDSIL_kamalpur.png

Plotting:  86%|████████▌ | 31/36 [00:12<00:01,  2.59plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_021-MBDGHY_karimganj.png

Plotting:  89%|████████▉ | 32/36 [00:12<00:01,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_014-MDSIL_kailashahar_gdsq_site.png

Plotting:  92%|█████████▏| 33/36 [00:12<00:01,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_013-MDSIL_belonia.png

Plotting:  94%|█████████▍| 34/36 [00:13<00:00,  2.58plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_004-mdsil_khowai.png

Plotting:  97%|█████████▋| 35/36 [00:13<00:00,  2.55plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_006-MDSIL_gajaria.png

Plotting: 100%|██████████| 36/36 [00:14<00:00,  2.57plot/s]

Saved: data_fetch_cwc/cwc/barak_and_others/images/CWC_008-MDSIL_anipur.png
Plots generated: 36

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_barak_and_others_2024-04-01_2025-05-07.gpkg (185566 rows)

water_level downloaded in 63.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       36          36          0           63.6
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/barak_and_others/stations
-------------------------------------------------------------
Starting CWC download for station=['013-ERDBWN', '014-ERDBWN', '015-ERDBWN', '016-ERDBWN', '017-ERDBWN', '018-ERDBWN', '019-ERDBWN', '020-ERDBWN', '022-ERDBWN', '023-ERDBWN', '049-ERDBWN', '050-ERDBWN', '051-ERDBWN', '052-ERDBWN', '053-ERDBWN', '055-erdbwn', '061-ERDBWN', '065-ERDBWN', '067-ERDBWN', '068-ERDBWN', '073-ERDBWN'] from 2024-04-01 to 2025-05-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 21 | Format: CSV | Time range: 2024–2025
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 21/21 [00:00<00:00, 17257.13station/s]
Plotting:   5%|▌         | 1/20 [00:00<00:07,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_017-ERDBWN_keonjhar.png

Plotting:  10%|█         | 2/20 [00:00<00:07,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_023-ERDBWN_jenapur.png

Plotting:  15%|█▌        | 3/20 [00:01<00:06,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_018-ERDBWN_altuma.png

Plotting:  20%|██        | 4/20 [00:01<00:06,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_065-ERDBWN_bolani.png

Plotting:  25%|██▌       | 5/20 [00:01<00:05,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_019-ERDBWN_panposh.png

Plotting:  30%|███       | 6/20 [00:02<00:05,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_050-ERDBWN_bonaigarh.png

Plotting:  35%|███▌      | 7/20 [00:02<00:04,  2.61plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_055-erdbwn_salandi_reservoir.png

Plotting:  40%|████      | 8/20 [00:03<00:04,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_051-ERDBWN_gohira.png

Plotting:  45%|████▌     | 9/20 [00:03<00:04,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_013-ERDBWN_swampatna.png

Plotting:  50%|█████     | 10/20 [00:03<00:03,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_022-ERDBWN_talcher.png

Plotting:  55%|█████▌    | 11/20 [00:04<00:03,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_061-ERDBWN_rengali_reservoir.png

Plotting:  60%|██████    | 12/20 [00:04<00:03,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_068-ERDBWN_bhejdih.png

Plotting:  65%|██████▌   | 13/20 [00:05<00:02,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_067-ERDBWN_keshdihi.png

Plotting:  70%|███████   | 14/20 [00:05<00:02,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_053-ERDBWN_purunagarh.png

Plotting:  75%|███████▌  | 15/20 [00:05<00:01,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_049-ERDBWN_bhuban_baji_rout_rd.bridge.png

Plotting:  80%|████████  | 16/20 [00:06<00:01,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_014-ERDBWN_champua.png

Plotting:  85%|████████▌ | 17/20 [00:06<00:01,  2.49plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_016-ERDBWN_akhuapada.png

Plotting:  90%|█████████ | 18/20 [00:07<00:00,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_052-ERDBWN_kamakshya_nagar_rd._bridge.png

Plotting:  95%|█████████▌| 19/20 [00:07<00:00,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_020-ERDBWN_gomlai.png

Plotting: 100%|██████████| 20/20 [00:07<00:00,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmani_and_baitarni/images/CWC_015-ERDBWN_anandpur.png
Plots generated: 20

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_brahmani_and_baitarni_2024-04-01_2025-05-07.gpkg (56603 rows)

water_level downloaded in 23.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       20          20          0           23.8
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/brahmani_and_baitarni/stations
-------------------------------------------------------------
Starting CWC download for station=['001-LBDJPG', '001-MBDGHY', '001-UBDDIB', '002-LBDJPG', '002-MBDGHY', '002-ubddib', '003-LBDJPG', '003-MBDGHY', '003-UBDDIB', '004-LBDJPG', '004-MBDGHY', '004-UBDDIB', '005-LBDJPG', '005-MBDGHY', '005-SIDGTK', '005-UBDDIB', '006-LBDJPG', '006-MBDGHY', '006-UBDDIB', '007-LBDJPG', '007-MBDGHY', '007-UBDDIB', '008-LBDJPG', '008-SIDGTK', '008-ubddib', '009-LBDJPG', '009-UBDDIB', '010-LBDJPG', '010-UBDDIB', '011-LBDJPG', '011-UBDDIB', '012-LBDJPG', '012-ubddib', '013-LBDjPG', '013-UBDDIB', '014-UBDDIB', '015-LBDJPG', '015-UBDDIB', '016-LBDJPG', '016-UBDDIB', '017-LBDJPG', '017-UBDDIB', '018-LBDJPG', '018-ubddib', '019-LBDJPG', '019-UBDDIB', '020-LBDJPG', '020-UBDDIB', '021-LBDJPG', '021-UBDDIB', '022-LBDJPG', '022-UBDDIB', '023-LBDJPG', '023-UBDDIB', '024-LBDJPG', '024-UBDDIB', '025-LBDJPG', '025-MBDGHY', '025-UBDDIB', '026-LBDJPG', '026-UBDDIB', '027-LBDJPG', '027-UBDDIB', '028-LBDJPG', '028-UBDDIB', '029-LBDJPG', '029-UBDDIB', '030-LBDJPG', '030-UBDDIB', '031-UBDDIB', '032-LBDJPG', '032-UBDDIB', '033-LBDJPG', '033-UBDDIB', '034-LBDJPG', '034-UBDDIB', '036-MBDNEW', '037-MBDNEW', '038-MBDNEW', '039-MBDNEW', '040-MBDNEW', '041-MBDNEW', '042-LBDJPG', '042-MBDNEW', '043-LBDJPG', '043-MBDNEW', '044-LBDJPG', '044-MBDNEW', '045-MBDNEW', '045-ubddib', '046-LBDJPG', '046-MBDNEW', '047-LBDJPG', '047-MBDNEW', '048-MBDNEW', '049-MBDNEW', '050-MBDNEW', '051-MBDNEW', '052-UBDDIB', '054-MBDNEW', '054-UBDDIB', '055-MBDNEW', '055-UBDDIB', '056-MBDNEW', '057-MBDNEW', '057-UBDDIB', '058-MBDNEW', '058-UBDDIB', '059-MBDNEW', '059-UBDDIB', '060-MBDNEW', '060-UBDDIB', '061-MBDNEW', '061-UBDDIB', '062-MBDNEW', '062-UBDDIB', '063-MBDNEW', '063-UBDDIB', '064-MBDNEW', '064-UBDDIB', '065-MBDNEW', '065-UBDDIB', '066-MBDNEW', '066-UBDDIB', '067-MBDNEW', '067-UBDDIB', '068-MBDNEW', '068-UBDDIB', '069-MBDNEW', '070-MBDNEW', '070-UBDDIB', '071-MBDNEW', '071-UBDDIB', '072-UBDDIB', '073-UBDDIB', '074-UBDDIB', '075-UBDDIB', '076-UBDDIB', '077-UBDDIB'] from 2024-04-01 to 2025-05-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 139 | Format: CSV | Time range: 2024–2025
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 139/139 [00:00<00:00, 15141.11station/s]
Plotting:   1%|          | 1/137 [00:00<00:54,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_022-UBDDIB_badatighat.png

Plotting:   1%|▏         | 2/137 [00:00<00:53,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_005-UBDDIB_passighat.png

Plotting:   2%|▏         | 3/137 [00:01<00:54,  2.46plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_033-UBDDIB_kampur.png

Plotting:   3%|▎         | 4/137 [00:01<00:53,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_006-UBDDIB_tezu.png

Plotting:   4%|▎         | 5/137 [00:01<00:51,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_065-MBDNEW_chaklagaon.png

Plotting:   4%|▍         | 6/137 [00:02<00:53,  2.47plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_043-MBDNEW_nona.png

Plotting:   5%|▌         | 7/137 [00:02<00:52,  2.46plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_031-UBDDIB_tezpur.png

Plotting:   6%|▌         | 8/137 [00:03<00:52,  2.45plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_002-ubddib_tuting.png

Plotting:   7%|▋         | 9/137 [00:03<00:51,  2.48plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_015-UBDDIB_desangpani.png

Plotting:   7%|▋         | 10/137 [00:04<00:51,  2.47plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_076-UBDDIB_bomjir.png

Plotting:   8%|▊         | 11/137 [00:04<00:50,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_037-MBDNEW_banglabasti.png

Plotting:   9%|▉         | 12/137 [00:04<00:49,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_021-UBDDIB_chouldhowaghat.png

Plotting:   9%|▉         | 13/137 [00:05<00:49,  2.48plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_008-SIDGTK_sankalang.png

Plotting:  10%|█         | 14/137 [00:05<00:48,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_048-MBDNEW_magurgaon.png

Plotting:  11%|█         | 15/137 [00:06<00:48,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_042-MBDNEW_sholmari.png

Plotting:  12%|█▏        | 16/137 [00:06<00:48,  2.49plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_056-MBDNEW_garampani.png

Plotting:  12%|█▏        | 17/137 [00:06<00:48,  2.49plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_007-UBDDIB_dholabazar.png

Plotting:  13%|█▎        | 18/137 [00:07<00:47,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_038-MBDNEW_machaigaon.png

Plotting:  14%|█▍        | 19/137 [00:07<00:46,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_008-ubddib_miao.png

Plotting:  15%|█▍        | 20/137 [00:07<00:46,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_005-LBDJPG_dhubri.png

Plotting:  15%|█▌        | 21/137 [00:08<00:45,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_074-UBDDIB_etalin.png

Plotting:  16%|█▌        | 22/137 [00:08<00:45,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_006-MBDGHY_puthimari_nh_rd_xing.png

Plotting:  17%|█▋        | 23/137 [00:09<00:44,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_016-LBDJPG_sevoke.png

Plotting:  18%|█▊        | 24/137 [00:09<00:44,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_067-MBDNEW_tarabari.png

Plotting:  18%|█▊        | 25/137 [00:09<00:43,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_005-MBDGHY_drf.png

Plotting:  19%|█▉        | 26/137 [00:10<00:43,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_001-UBDDIB_kibithu.png

Plotting:  20%|█▉        | 27/137 [00:10<00:43,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_014-UBDDIB_dillighat.png

Plotting:  20%|██        | 28/137 [00:11<00:42,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_024-LBDJPG_chepan.png

Plotting:  21%|██        | 29/137 [00:11<00:42,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_004-UBDDIB_lemeking.png

Plotting:  22%|██▏       | 30/137 [00:11<00:42,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_044-MBDNEW_kaliajari.png

Plotting:  23%|██▎       | 31/137 [00:12<00:41,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_009-UBDDIB_namsai.png

Plotting:  23%|██▎       | 32/137 [00:12<00:40,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_023-UBDDIB_bokajan.png

Plotting:  24%|██▍       | 33/137 [00:13<00:40,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_022-LBDJPG_domohani.png

Plotting:  25%|██▍       | 34/137 [00:13<00:40,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_004-MBDGHY_pagladiya_n_t_road_crossing.png

Plotting:  26%|██▌       | 35/137 [00:13<00:39,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_054-MBDNEW_silghat.png

Plotting:  26%|██▋       | 36/137 [00:14<00:39,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_068-UBDDIB_murkongselek.png

Plotting:  27%|██▋       | 37/137 [00:14<00:37,  2.64plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_011-LBDJPG_majitar.png

Plotting:  28%|██▊       | 38/137 [00:15<00:38,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_012-ubddib_naharkatia.png

Plotting:  28%|██▊       | 39/137 [00:15<00:38,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_007-LBDJPG_sankosh_lrp.png

Plotting:  29%|██▉       | 40/137 [00:15<00:37,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_034-UBDDIB_dharamtul.png

Plotting:  30%|██▉       | 41/137 [00:16<00:37,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_030-UBDDIB_nt_road_crossing_jia-bharali.png

Plotting:  31%|███       | 42/137 [00:16<00:37,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_025-MBDGHY_pandu.png

Plotting:  31%|███▏      | 43/137 [00:16<00:36,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_064-MBDNEW_rangaphar_siding.png

Plotting:  32%|███▏      | 44/137 [00:17<00:35,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_066-UBDDIB_parshuramkund.png

Plotting:  33%|███▎      | 45/137 [00:17<00:35,  2.60plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_061-MBDNEW_gahampai.png

Plotting:  34%|███▎      | 46/137 [00:18<00:35,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_007-MBDGHY_suklai.png

Plotting:  34%|███▍      | 47/137 [00:18<00:34,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_026-LBDJPG_nagrakata.png

Plotting:  35%|███▌      | 48/137 [00:18<00:33,  2.64plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_045-MBDNEW_kamarpur.png

Plotting:  36%|███▌      | 49/137 [00:19<00:33,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_020-LBDJPG_neora.png

Plotting:  36%|███▋      | 50/137 [00:19<00:33,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_049-MBDNEW_patacharkuchi.png

Plotting:  37%|███▋      | 51/137 [00:20<00:32,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_016-UBDDIB_nanglamoraghat.png

Plotting:  38%|███▊      | 52/137 [00:20<00:32,  2.64plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_044-LBDJPG_shaladang.png

Plotting:  39%|███▊      | 53/137 [00:20<00:32,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_025-LBDJPG_tufanganj.png

Plotting:  39%|███▉      | 54/137 [00:21<00:31,  2.66plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_021-LBDJPG_gazoldoba.png

Plotting:  40%|████      | 55/137 [00:21<00:30,  2.65plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_030-LBDJPG_ghugumari.png

Plotting:  41%|████      | 56/137 [00:21<00:30,  2.64plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_052-UBDDIB_balighat.png

Plotting:  42%|████▏     | 57/137 [00:22<00:30,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_042-LBDJPG_suldaguri.png

Plotting:  42%|████▏     | 58/137 [00:22<00:30,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_010-UBDDIB_dibrugarh.png

Plotting:  43%|████▎     | 59/137 [00:23<00:29,  2.61plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_018-LBDJPG_diana.png

Plotting:  44%|████▍     | 60/137 [00:23<00:27,  2.79plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_012-LBDJPG_sankalan.png

Plotting:  45%|████▍     | 61/137 [00:23<00:28,  2.71plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_017-UBDDIB_bihubar.png

Plotting:  45%|████▌     | 62/137 [00:24<00:28,  2.66plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_070-UBDDIB_tamen.png

Plotting:  46%|████▌     | 63/137 [00:24<00:28,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_018-ubddib_sivasagar.png

Plotting:  47%|████▋     | 64/137 [00:24<00:28,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_058-MBDNEW_krishnai.png

Plotting:  47%|████▋     | 65/137 [00:25<00:28,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_047-LBDJPG_singimari.png

Plotting:  48%|████▊     | 66/137 [00:25<00:28,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_063-MBDNEW_bakalighat.png

Plotting:  49%|████▉     | 67/137 [00:26<00:27,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_036-MBDNEW_diprang_gaon.png

Plotting:  50%|████▉     | 68/137 [00:26<00:27,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_047-MBDNEW_malibari.png

Plotting:  50%|█████     | 69/137 [00:26<00:27,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_041-MBDNEW_ramdia.png

Plotting:  51%|█████     | 70/137 [00:27<00:26,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_002-LBDJPG_beki_road_bridge.png

Plotting:  52%|█████▏    | 71/137 [00:27<00:26,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_027-UBDDIB_seppa.png

Plotting:  53%|█████▎    | 72/137 [00:28<00:25,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_003-MBDGHY_matunga.png

Plotting:  53%|█████▎    | 73/137 [00:28<00:25,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_060-UBDDIB_balijagaon.png

Plotting:  54%|█████▍    | 74/137 [00:28<00:25,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_019-UBDDIB_neamatighat.png

Plotting:  55%|█████▍    | 75/137 [00:29<00:24,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_068-MBDNEW_kusumbil.png

Plotting:  55%|█████▌    | 76/137 [00:29<00:24,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_003-UBDDIB_yinkiang.png

Plotting:  56%|█████▌    | 77/137 [00:30<00:23,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_046-MBDNEW_simultala.png

Plotting:  57%|█████▋    | 78/137 [00:30<00:23,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_045-ubddib_doomdooma.png

Plotting:  58%|█████▊    | 79/137 [00:30<00:22,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_032-UBDDIB_kheronighat.png

Plotting:  58%|█████▊    | 80/137 [00:31<00:22,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_029-UBDDIB_bhalukpong.png

Plotting:  59%|█████▉    | 81/137 [00:31<00:22,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_059-UBDDIB_pagoda.png

Plotting:  60%|█████▉    | 82/137 [00:32<00:22,  2.49plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_033-LBDJPG_aie_nh_xing.png

Plotting:  61%|██████    | 83/137 [00:32<00:21,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_064-UBDDIB_changwanti.png

Plotting:  61%|██████▏   | 84/137 [00:32<00:21,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_059-MBDNEW_biswanath_ghat.png

Plotting:  62%|██████▏   | 85/137 [00:33<00:20,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_051-MBDNEW_satpokholi.png

Plotting:  63%|██████▎   | 86/137 [00:33<00:20,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_066-MBDNEW_khudrakhowa.png

Plotting:  64%|██████▎   | 87/137 [00:34<00:19,  2.63plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_075-UBDDIB_ebranli.png

Plotting:  64%|██████▍   | 88/137 [00:34<00:18,  2.63plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_055-UBDDIB_bogibil.png

Plotting:  65%|██████▍   | 89/137 [00:34<00:18,  2.65plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_043-LBDJPG_ambari.png

Plotting:  66%|██████▌   | 90/137 [00:35<00:18,  2.60plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_061-UBDDIB_jagunghat.png

Plotting:  66%|██████▋   | 91/137 [00:35<00:17,  2.67plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_009-LBDJPG_rangpo.png

Plotting:  67%|██████▋   | 92/137 [00:35<00:17,  2.65plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_055-MBDNEW_polaguri.png

Plotting:  68%|██████▊   | 93/137 [00:36<00:16,  2.66plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_039-MBDNEW_b_g_road.png

Plotting:  69%|██████▊   | 94/137 [00:36<00:16,  2.65plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_050-MBDNEW_changsari.png

Plotting:  69%|██████▉   | 95/137 [00:37<00:15,  2.65plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_063-UBDDIB_chowkhamghat.png

Plotting:  70%|███████   | 96/137 [00:37<00:15,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_020-UBDDIB_daporizo.png

Plotting:  71%|███████   | 97/137 [00:37<00:15,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_070-MBDNEW_kakripara.png

Plotting:  72%|███████▏  | 98/137 [00:38<00:15,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_003-LBDJPG_panbari.png

Plotting:  72%|███████▏  | 99/137 [00:38<00:15,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_040-MBDNEW_ririgaon.png

Plotting:  73%|███████▎  | 100/137 [00:39<00:14,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_058-UBDDIB_doimukh.png

Plotting:  74%|███████▎  | 101/137 [00:39<00:14,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_071-UBDDIB_taliha.png

Plotting:  74%|███████▍  | 102/137 [00:39<00:13,  2.55plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_001-LBDJPG_mathanguri.png

Plotting:  75%|███████▌  | 103/137 [00:40<00:13,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_001-MBDGHY_guwahatid.c.court.png

Plotting:  76%|███████▌  | 104/137 [00:40<00:13,  2.51plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_027-LBDJPG_jaldhaka_nh-31.png

Plotting:  77%|███████▋  | 105/137 [00:41<00:12,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_006-LBDJPG_barabisha.png

Plotting:  77%|███████▋  | 106/137 [00:41<00:12,  2.49plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_034-LBDJPG_bahalpur.png

Plotting:  78%|███████▊  | 107/137 [00:41<00:12,  2.48plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_026-UBDDIB_golaghat.png

Plotting:  79%|███████▉  | 108/137 [00:42<00:11,  2.50plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_062-UBDDIB_gutang.png

Plotting:  80%|███████▉  | 109/137 [00:42<00:11,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_015-LBDJPG_coronation.png

Plotting:  80%|████████  | 110/137 [00:43<00:10,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_032-LBDJPG_murti.png

Plotting:  81%|████████  | 111/137 [00:43<00:10,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_073-UBDDIB_gira_siyum.png

Plotting:  82%|████████▏ | 112/137 [00:43<00:09,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_072-UBDDIB_koloriang.png

Plotting:  82%|████████▏ | 113/137 [00:44<00:09,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_071-MBDNEW_pohumara.png

Plotting:  83%|████████▎ | 114/137 [00:44<00:08,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_025-UBDDIB_gelabil.png

Plotting:  84%|████████▍ | 115/137 [00:44<00:08,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_011-UBDDIB_margherita.png

Plotting:  85%|████████▍ | 116/137 [00:45<00:08,  2.60plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_054-UBDDIB_subansiri_lower_dam.png

Plotting:  85%|████████▌ | 117/137 [00:45<00:07,  2.63plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_062-MBDNEW_mojowari.png

Plotting:  86%|████████▌ | 118/137 [00:46<00:07,  2.58plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_057-UBDDIB_dihingmukh.png

Plotting:  87%|████████▋ | 119/137 [00:46<00:07,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_057-MBDNEW_teok.png

Plotting:  88%|████████▊ | 120/137 [00:46<00:06,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_069-MBDNEW_south_salmara.png

Plotting:  88%|████████▊ | 121/137 [00:47<00:06,  2.54plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_029-LBDJPG_hasimara.png

Plotting:  89%|████████▉ | 122/137 [00:47<00:05,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_013-LBDjPG_khanitar.png

Plotting:  90%|████████▉ | 123/137 [00:48<00:05,  2.67plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_065-UBDDIB_mompani.png

Plotting:  91%|█████████ | 124/137 [00:48<00:04,  2.66plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_017-LBDJPG_chel.png

Plotting:  91%|█████████ | 125/137 [00:48<00:04,  2.64plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_005-SIDGTK_toyum.png

Plotting:  92%|█████████▏| 126/137 [00:49<00:04,  2.62plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_046-LBDJPG_baladoba.png

Plotting:  93%|█████████▎| 127/137 [00:49<00:03,  2.61plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_028-LBDJPG_mathabhanga.png

Plotting:  93%|█████████▎| 128/137 [00:50<00:03,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_019-LBDJPG_ghish.png

Plotting:  94%|█████████▍| 129/137 [00:50<00:03,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_004-LBDJPG_manas_n_h_crossing.png

Plotting:  95%|█████████▍| 130/137 [00:50<00:02,  2.59plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_008-LBDJPG_golokganj.png

Plotting:  96%|█████████▌| 131/137 [00:51<00:02,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_024-UBDDIB_numaligarh.png

Plotting:  96%|█████████▋| 132/137 [00:51<00:01,  2.57plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_060-MBDNEW_langrimukh.png

Plotting:  97%|█████████▋| 133/137 [00:51<00:01,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_002-MBDGHY_goalpara.png

Plotting:  98%|█████████▊| 134/137 [00:52<00:01,  2.52plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_023-LBDJPG_mekhliganj_r-b.png

Plotting:  99%|█████████▊| 135/137 [00:52<00:00,  2.53plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_013-UBDDIB_chenimari_khowang.png

/home/saratchandra_ch/swift/swift_app/plot_station_timeseries.py:215: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())
Plotting:  99%|█████████▉| 136/137 [00:53<00:00,  2.60plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_010-LBDJPG_singlabazar.png

Plotting: 100%|██████████| 137/137 [00:53<00:00,  2.56plot/s]

Saved: data_fetch_cwc/cwc/brahmaputra/images/CWC_067-UBDDIB_jairampur.png
Plots generated: 137

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_brahmaputra_2024-04-01_2025-05-07.gpkg (678615 rows)

water_level downloaded in 89.3 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       137         137         0           89.3
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/brahmaputra/stations
-------------------------------------------------------------

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,010-mdsil,2024-04-05 08:00:00,0.00,-53.00,m,23.811944,92.650000,POINT (92.65 23.81194),Barak and Others
1,010-mdsil,2024-04-12 08:00:00,57.75,4.75,m,23.811944,92.650000,POINT (92.65 23.81194),Barak and Others
2,010-mdsil,2024-04-12 13:00:00,57.75,4.75,m,23.811944,92.650000,POINT (92.65 23.81194),Barak and Others
3,010-mdsil,2024-04-12 18:00:00,57.75,4.75,m,23.811944,92.650000,POINT (92.65 23.81194),Barak and Others
4,010-mdsil,2024-04-13 08:00:00,57.75,4.75,m,23.811944,92.650000,POINT (92.65 23.81194),Barak and Others
...,...,...,...,...,...,...,...,...,...
1348514,055-MBDNEW,2025-04-29 18:00:00,55.17,55.17,m,26.434444,92.312222,POINT (92.31222 26.43444),Brahmaputra
1348515,055-MBDNEW,2025-04-30 08:00:00,55.11,55.11,m,26.434444,92.312222,POINT (92.31222 26.43444),Brahmaputra
1348516,055-MBDNEW,2025-04-30 13:00:00,55.06,55.06,m,26.434444,92.312222,POINT (92.31222 26.43444),Brahmaputra
1348517,055-MBDNEW,2025-05-01 08:00:00,55.11,55.11,m,26.434444,92.312222,POINT (92.31222 26.43444),Brahmaputra
1348518,055-MBDNEW,2025-05-01 13:00:00,55.06,55.06,m,26.434444,92.312222,POINT (92.31222 26.43444),Brahmaputra

In [56]:
# Test fetch() from WRIS basin table
swift.fetch(
    basins_wris[0:3],
    output_dir="data_fetch_cwc",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Starting fetch for stations table (rows=3) from 2024-04-01 to 2025-05-07...

/tmp/ipykernel_1345376/1828648221.py:2: UserWarning: Fetching WRIS data for basin-level input (all stations per basin/variable). Dispatching 3 basin-variable combinations; this may take a long time.
  swift.fetch(

Starting WRIS download for basin='Brahmani and Baitarni', Variables=sediment from 2024-04-01 to 2025-05-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 2/2 [00:06<00:00,  3.48s/station]

Saved GeoPackage: data_fetch_cwc/wris/brahmani and baitarni/Brahmani and Baitarni_sediment_2024-04-01_2025-05-07.gpkg (122 rows)

sediment downloaded in 7.0 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          1           1           0           7.0
-------------------------------------------------------------
Output directory: data_fetch_cwc/wris/brahmani and baitarni
-------------------------------------------------------------

Plot-only mode enabled.

Plotting brahmani and baitarni / sediment (1 stations)
Saved: data_fetch_cwc/wris/brahmani and baitarni/images/sediment/018-ERDBWN_Altuma_SEDIM.png

Plots generated: 1
Starting WRIS download for basin='Cauvery', Variables=sediment from 2024-04-01 to 2025-05-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 18/18 [00:08<00:00,  2.19station/s]

Saved GeoPackage: data_fetch_cwc/wris/cauvery/Cauvery_sediment_2024-04-01_2025-05-07.gpkg (4321 rows)

sediment downloaded in 8.3 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          17          17          0           8.3
-------------------------------------------------------------
Output directory: data_fetch_cwc/wris/cauvery
-------------------------------------------------------------

Plot-only mode enabled.

Plotting cauvery / sediment (17 stations)
Saved: data_fetch_cwc/wris/cauvery/images/sediment/014-srdcbe_NALLAMARANPATTY_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/020-CDBNG_T.K.HALLI_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png
Saved: data_fetch_cwc/wris/cauvery/images/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png

Plots generated: 17
Starting WRIS download for basin='East flowing rivers between Mahanadi and Pennar', Variables=sediment from 2024-04-01 to 2025-05-07...

Dataset: sediment
Using cached station discovery
All stations already downloaded — skipping download step.

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          0           0           0           0.0
-------------------------------------------------------------
Output directory: data_fetch_cwc/wris/east flowing rivers between mahanadi and pennar
-------------------------------------------------------------

,station_code,time,sed,lat,lon,geometry,basin,variable
0,018-ERDBWN,2024-04-01 08:00:00,0.0870,20.9308,85.5192,POINT (85.5192 20.9308),Brahmani and Baitarni,sediment
1,018-ERDBWN,2024-07-01 08:00:00,0.0570,20.9308,85.5192,POINT (85.5192 20.9308),Brahmani and Baitarni,sediment
2,018-ERDBWN,2024-07-02 08:00:00,0.0550,20.9308,85.5192,POINT (85.5192 20.9308),Brahmani and Baitarni,sediment
3,018-ERDBWN,2024-07-03 08:00:00,0.0610,20.9308,85.5192,POINT (85.5192 20.9308),Brahmani and Baitarni,sediment
4,018-ERDBWN,2024-07-04 08:00:00,0.0510,20.9308,85.5192,POINT (85.5192 20.9308),Brahmani and Baitarni,sediment
...,...,...,...,...,...,...,...,...
4438,046-SRDCBE,2025-03-25 08:00:00,0.0206,10.4981,77.9458,POINT (77.9458 10.4981),Cauvery,sediment
4439,046-SRDCBE,2025-03-26 08:00:00,0.0196,10.4981,77.9458,POINT (77.9458 10.4981),Cauvery,sediment
4440,046-SRDCBE,2025-03-27 08:00:00,0.0193,10.4981,77.9458,POINT (77.9458 10.4981),Cauvery,sediment
4441,046-SRDCBE,2025-03-28 08:00:00,0.0208,10.4981,77.9458,POINT (77.9458 10.4981),Cauvery,sediment
4442,046-SRDCBE,2025-03-29 08:00:00,0.0226,10.4981,77.9458,POINT (77.9458 10.4981),Cauvery,sediment

# Test fetch with stations tables

In [13]:
stations = swift.wris.stations(basin=["Godavari", "Narmada"], variable=["solar", "sediment"])
stations

Searching the WRIS database... This might take some time.
The station list returned does not guarantee time series data availability for all time periods.

,station_code,station_name,latitude,longitude,river,basin,variable
0,007-ugdhyd,Pachegaon,19.5353,74.8336,Pravara,Godavari,sediment
1,017-ugdhyd,Saigaon,18.0500,77.0497,Manjira,Godavari,sediment
2,020-ugdhyd,Degloor,18.5456,77.5775,Manjira,Godavari,sediment
3,031-ugdhyd,Saloora,18.7033,77.7958,Manjira,Godavari,sediment
4,7D8FED08,Kovvada kalva reservoir,17.2067,81.5142,Kovvadakalva,Godavari,solar
5,7D901252,Vuyyuru,16.3814,80.8530,Seethapalli Vagu,Godavari,solar
6,7D903A6C,Dowlaiswaram,16.9361,81.7850,Gowthami,Godavari,solar
7,004-NDBHP,Chhidgaon,22.4012,77.3086,Ganjal,Narmada,sediment
8,006-TDSURAT,CHANWADA,22.0500,73.4653,Orsang,Narmada,sediment
9,009-ndbhp,Manot,22.7358,80.5131,Narmada,Narmada,sediment
10,01 02 17 002,Tapi at Burhanpur,21.2994,76.2354,Tapi,Narmada,sediment
11,013 NDBHP,Sandia,22.9167,78.3500,Narmada,Narmada,sediment
12,016-NDBHP,Narmadapuram,22.7560,77.7330,Narmada,Narmada,sediment

In [57]:
# Test fetch() from CWC station table
swift.fetch(
    stations,
    output_dir="data_fetch_wris",
    start_date="2024-04-01",
    end_date="2025-05-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Starting fetch for stations table (rows=13) from 2024-04-01 to 2025-05-07...
Starting WRIS download for basin='Godavari', Variables=sediment from 2024-04-01 to 2025-05-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:07<00:00,  1.75s/station]

Saved GeoPackage: data_fetch_wris/wris/godavari/Godavari_sediment_2024-04-01_2025-05-07.gpkg (38 rows)

sediment downloaded in 7.0 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          1           1           0           7.0
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------

Plot-only mode enabled.

Plotting godavari / sediment (1 stations)
Saved: data_fetch_wris/wris/godavari/images/sediment/007-ugdhyd_Pachegaon_SEDIM.png

Plots generated: 1
Starting WRIS download for basin='Godavari', Variables=solar from 2024-04-01 to 2025-05-07...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:01<00:00,  1.97station/s]

Saved GeoPackage: data_fetch_wris/wris/godavari/Godavari_solar_radiation_2024-04-01_2025-05-07.gpkg (37991 rows)

solar_radiation downloaded in 1.9 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           1.9
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/godavari
-------------------------------------------------------------

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: data_fetch_wris/wris/godavari/images/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plots generated: 3
Starting WRIS download for basin='Narmada', Variables=sediment from 2024-04-01 to 2025-05-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 6/6 [00:07<00:00,  1.18s/station]

Saved GeoPackage: data_fetch_wris/wris/narmada/Narmada_sediment_2024-04-01_2025-05-07.gpkg (1305 rows)

sediment downloaded in 7.1 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          4           4           0           7.1
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/narmada
-------------------------------------------------------------

Plot-only mode enabled.

Plotting narmada / sediment (4 stations)
Saved: data_fetch_wris/wris/narmada/images/sediment/013 NDBHP_ Sandia_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/016-NDBHP_Narmadapuram_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/009-ndbhp_Manot_SEDIM.png
Saved: data_fetch_wris/wris/narmada/images/sediment/006-TDSURAT_CHANWADA_SEDIM.png

Plots generated: 4

,station_code,time,sed,lat,lon,geometry,basin,variable,solar
0,007-ugdhyd,2024-07-29 08:00:00,0.0270,19.5353,74.8336,POINT (74.8336 19.5353),Godavari,sediment,NaN
1,007-ugdhyd,2024-07-30 08:00:00,0.0440,19.5353,74.8336,POINT (74.8336 19.5353),Godavari,sediment,NaN
2,007-ugdhyd,2024-07-31 08:00:00,0.1220,19.5353,74.8336,POINT (74.8336 19.5353),Godavari,sediment,NaN
3,007-ugdhyd,2024-09-02 09:00:00,0.0170,19.5353,74.8336,POINT (74.8336 19.5353),Godavari,sediment,NaN
4,007-ugdhyd,2024-09-03 09:00:00,0.0210,19.5353,74.8336,POINT (74.8336 19.5353),Godavari,sediment,NaN
...,...,...,...,...,...,...,...,...,...
39329,013 NDBHP,2025-05-03 08:00:00,0.0559,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,NaN
39330,013 NDBHP,2025-05-04 08:00:00,0.0558,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,NaN
39331,013 NDBHP,2025-05-05 08:00:00,0.0410,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,NaN
39332,013 NDBHP,2025-05-06 08:00:00,0.0572,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,NaN
39333,013 NDBHP,2025-05-07 08:00:00,0.0571,22.9167,78.3500,POINT (78.35 22.9167),Narmada,sediment,NaN

In [3]:
cwc_for_fetch = swift.cwc.stations(basin=["Godavari", "Krishna"], state = ["Telangana", "Maharashtra"])
cwc_for_fetch

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,001-UKDPUNE,Karad,Krishna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.293611,74.190000,549.915,563.41,567.04,567.162,1976-06-07
1,001-lgdhyd,Somanpally(Seasonal),Maner,Godavari,Telangana,KARIMNAGAR,"Upper Godavari Division(UGD), Hyderabad",18.616667,79.800000,121.000,NaN,NaN,129.020,2023-07-27
2,002-LGDHYD,Kaleswaram,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.820000,79.910000,91.290,103.50,104.75,108.190,2022-07-15
3,002-UKDPUNE,Warunji,Koyna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.272778,74.164722,549.437,562.80,565.20,568.047,1976-06-06
4,003-UKDPUNE,Samdoli (Seasonal),Warna,Krishna,Maharashtra,Sangli,"Upper Krishna Division(UKD), Pune",16.856389,74.496667,528.594,541.95,543.15,546.994,2019-08-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,040-UKDPUNE,Targaon,Krishna,Krishna,Maharashtra,Satara,"Upper Krishna Division(UKD), Pune",17.517778,74.146111,584.000,593.00,594.00,594.850,2019-08-07
83,042-UKD PUNE,NANDRE,Yerala,Krishna,Maharashtra,Sangli,"Upper Krishna Division(UKD), Pune",16.949167,74.529722,532.500,540.17,542.21,548.445,2019-08-08
84,043-UKDPUNE,Rahu,Mula-Mutha,Krishna,Maharashtra,Pune,"Upper Krishna Division(UKD), Pune",18.572222,74.273611,507.000,517.50,518.50,519.550,NaN
85,049-ugdhyd,LAXMI BARRAGE,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.703889,80.089167,0.000,NaN,NaN,NaN,NaN
86,053-UGDHYD,MID MANAIR DAM,Maner,Godavari,Telangana,RAJANNA SIRCILLA,"Upper Godavari Division(UGD), Hyderabad",18.392778,78.961111,0.000,NaN,NaN,NaN,NaN

In [15]:
print(cwc_for_fetch.attrs)

{'source': 'cwc', 'fetch_source': 'cwc', 'basin': ['Godavari', 'Krishna'], 'state': ['Telangana', 'Maharashtra']}

In [4]:
# Test fetch() from CWC station table
swift.fetch(
    cwc_for_fetch,
    output_dir="data_fetch_cwc",
    start_date="2024-01-01",
    end_date="2024-04-01",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Starting fetch for stations table (rows=87) from 2024-01-01 to 2024-04-01...
Starting CWC download for station=['003-ugdhyd', '005-ugdhyd', '005-wgdngp', '006-UGDHYD', '006-WGDNGP', '007-ugdhyd', '008-WGDNGP', '008-ugdhyd', '009-UGDHYD', '009-WGDNGP', '010-ugdhyd', '010-wgdngp', '011-WGDNGP', '012-UGDHYD', '012-wgdngp', '013-UGDHYD', '013-wgdngp', '014-ugdhyd', '015-UGDHYD', '016-WGDNGP', '017-WGDNGP', '018-WGDNGP', '019-WGDNGP', '020-ugdhyd', '020-wgdngp', '021-UGDHYD', '021-wgdngp', '024-wgdngp', '025-WGDNGP', '026-WGDNGP', '032-wgdngp', '034-UGDHYD', '035-UGDHYD', '036-UGDHYD'] from 2024-01-01 to 2024-04-01...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 34 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 34/34 [00:00<00:00, 56210.62station/s]
Plotting:   6%|▌         | 2/34 [00:00<00:04,  6.62plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-WGDNGP_bamni_ballarsha.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-WGDNGP_satrapur.png

Plotting:  12%|█▏        | 4/34 [00:00<00:04,  6.85plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-WGDNGP_salebardi.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-WGDNGP_mangrul.png

Plotting:  18%|█▊        | 6/34 [00:00<00:04,  6.93plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_007-ugdhyd_pachegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_003-ugdhyd_nasik.png

Plotting:  24%|██▎       | 8/34 [00:01<00:03,  7.00plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-ugdhyd_dhalegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-UGDHYD_gangakhed_w-l_station.png

Plotting:  29%|██▉       | 10/34 [00:01<00:03,  7.01plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-wgdngp_wairagarh.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-UGDHYD_kopergaon.png

Plotting:  35%|███▌      | 12/34 [00:01<00:03,  7.08plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-UGDHYD_betmogra.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_035-UGDHYD_manjlegaon.png

Plotting:  41%|████      | 14/34 [00:02<00:02,  6.99plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-WGDNGP_p.g._bridge.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-wgdngp_nandgaon.png

Plotting:  47%|████▋     | 16/34 [00:02<00:02,  7.01plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-WGDNGP_kanhargaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-ugdhyd_nmd-weir.png

Plotting:  53%|█████▎    | 18/34 [00:02<00:02,  6.62plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-wgdngp_ashti.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_036-UGDHYD_yeldari_reservoir.png

Plotting:  59%|█████▉    | 20/34 [00:02<00:02,  6.84plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-WGDNGP_pauni.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-wgdngp_sitekasa.png

Plotting:  65%|██████▍   | 22/34 [00:03<00:01,  6.92plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-WGDNGP_bhandara.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-ugdhyd_purna.png

Plotting:  71%|███████   | 24/34 [00:03<00:01,  6.96plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_032-wgdngp_gosikhurd_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-ugdhyd_lasur.png

Plotting:  76%|███████▋  | 26/34 [00:03<00:01,  6.95plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-UGDHYD_nanded.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_011-WGDNGP_hivra.png

Plotting:  82%|████████▏ | 28/34 [00:04<00:00,  7.00plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_034-UGDHYD_mula_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-wgdngp_ghugus.png

Plotting:  88%|████████▊ | 30/34 [00:04<00:00,  7.02plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-UGDHYD_jaikwadi_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-wgdngp_mirdapalli.png

Plotting:  94%|█████████▍| 32/34 [00:04<00:00,  7.01plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-WGDNGP_sakmur.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-wgdngp_rajoli.png

Plotting: 100%|██████████| 34/34 [00:04<00:00,  6.93plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-ugdhyd_degloor.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-UGDHYD_zari.png
Plots generated: 34

Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_godavari_maharashtra_2024-01-01_2024-04-01.gpkg (8046 rows)

water_level downloaded in 7.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       34          34          0           7.4
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------
Starting CWC download for station=['001-lgdhyd', '002-LGDHYD', '014-lgdhyd', '015-LGDHYD', '016-LGDHYD', '017-LGDHYD', '018-LGDHYD', '018-UGDHYD', '019-UGDHYD', '019-lgdhyd', '022-ugdhyd', '022-wgdngp', '023-UGDHYD', '024-UGDHYD', '025-UGDHYD', '026-ugdhyd', '027-ugdhyd', '028-wgdngp', '030-UGDHYD', '034-LGDHYD', '049-ugdhyd', '053-UGDHYD'] from 2024-01-01 to 2024-04-01...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 22 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 22/22 [00:00<00:00, 36101.21station/s]
Plotting:   4%|▍         | 2/52 [00:00<00:07,  6.42plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_002-LGDHYD_kaleswaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-WGDNGP_bamni_ballarsha.png

Plotting:   8%|▊         | 4/52 [00:00<00:07,  6.55plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-LGDHYD_sangam_kinnerasani.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-WGDNGP_satrapur.png

Plotting:  12%|█▏        | 6/52 [00:00<00:06,  6.81plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-LGDHYD_dummagudem.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-UGDHYD_mancherial.png

Plotting:  15%|█▌        | 8/52 [00:01<00:06,  7.02plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-WGDNGP_salebardi.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-WGDNGP_mangrul.png

Plotting:  19%|█▉        | 10/52 [00:01<00:05,  7.05plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_007-ugdhyd_pachegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_030-UGDHYD_jannepally.png

Plotting:  23%|██▎       | 12/52 [00:01<00:05,  7.08plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-LGDHYD_eturunagaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_003-ugdhyd_nasik.png

Plotting:  27%|██▋       | 14/52 [00:02<00:05,  7.19plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-ugdhyd_dhalegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_023-UGDHYD_sriram_sagar_reservoir.png

Plotting:  31%|███       | 16/52 [00:02<00:05,  6.51plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-UGDHYD_gangakhed_w-l_station.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-wgdngp_wairagarh.png

Plotting:  35%|███▍      | 18/52 [00:02<00:04,  6.81plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-UGDHYD_kopergaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-UGDHYD_betmogra.png

Plotting:  38%|███▊      | 20/52 [00:02<00:04,  6.82plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_035-UGDHYD_manjlegaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-WGDNGP_p.g._bridge.png

Plotting:  42%|████▏     | 22/52 [00:03<00:04,  7.03plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_012-wgdngp_nandgaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-ugdhyd_kaddam_dam.png

Plotting:  46%|████▌     | 24/52 [00:03<00:03,  7.22plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-WGDNGP_kanhargaon.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-UGDHYD_nizamsagar_reservoir.png

Plotting:  50%|█████     | 26/52 [00:03<00:03,  7.23plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-ugdhyd_nmd-weir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_010-wgdngp_ashti.png

Plotting:  54%|█████▍    | 28/52 [00:04<00:03,  7.20plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_036-UGDHYD_yeldari_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-wgdngp_bhatpalli.png

Plotting:  58%|█████▊    | 30/52 [00:04<00:03,  7.13plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_001-lgdhyd_somanpallyseasonal.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-WGDNGP_pauni.png

Plotting:  62%|██████▏   | 32/52 [00:04<00:02,  7.07plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-UGDHYD_gandlapet.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_005-wgdngp_sitekasa.png

Plotting:  65%|██████▌   | 34/52 [00:04<00:02,  7.03plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_006-WGDNGP_bhandara.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-lgdhyd_sangam_murredu.png

Plotting:  69%|██████▉   | 36/52 [00:05<00:02,  6.92plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-ugdhyd_purna.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_032-wgdngp_gosikhurd_dam.png

Plotting:  73%|███████▎  | 38/52 [00:05<00:02,  6.94plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_008-ugdhyd_lasur.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-ugdhyd_bhainsastate_govt._site.png

Plotting:  75%|███████▌  | 39/52 [00:05<00:01,  6.92plot/s]/home/carbform/swift/swift_app/plot_station_timeseries.py:215: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())
Plotting:  77%|███████▋  | 40/52 [00:05<00:01,  7.02plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-UGDHYD_nanded.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_028-wgdngp_sirpur_town.png

Plotting:  81%|████████  | 42/52 [00:06<00:01,  6.91plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_011-WGDNGP_hivra.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-UGDHYD_singur_reservoir.png

Plotting:  85%|████████▍ | 44/52 [00:06<00:01,  6.90plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_034-UGDHYD_mula_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-wgdngp_ghugus.png

Plotting:  88%|████████▊ | 46/52 [00:06<00:00,  7.01plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_009-UGDHYD_jaikwadi_dam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-LGDHYD_bhadrachalam.png

Plotting:  92%|█████████▏| 48/52 [00:06<00:00,  6.86plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-wgdngp_mirdapalli.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-WGDNGP_sakmur.png

Plotting:  96%|█████████▌| 50/52 [00:07<00:00,  6.89plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_021-wgdngp_rajoli.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_020-ugdhyd_degloor.png

Plotting: 100%|██████████| 52/52 [00:07<00:00,  6.95plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-lgdhyd_perur.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_013-UGDHYD_zari.png
Plots generated: 52
Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_godavari_telangana_2024-01-01_2024-04-01.gpkg (4268 rows)

water_level downloaded in 22.7 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       18          18          0           22.7
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------

Starting CWC download for station=['001-UKDPUNE', '002-UKDPUNE', '003-UKDPUNE', '004-UKDPUNE', '005-UKDPUNE', '006-UKDPUNE', '010-ukdpune', '011-ukdpune', '012-UKDPUNE', '016-ukdpune', '025-ukdpune', '028-ukdpune', '029-ukdpune', '032-UKDPUNE', '033-UKDPUNE', '034-UKDPUNE', '035-UKDPUNE', '040-UKDPUNE', '042-UKD PUNE', '043-UKDPUNE'] from 2024-01-01 to 2024-04-01...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 20 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 20/20 [00:00<00:00, 31512.43station/s]
Plotting:  11%|█         | 2/18 [00:00<00:02,  6.46plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_002-UKDPUNE_warunji.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_012-UKDPUNE_wadakbal.png

Plotting:  22%|██▏       | 4/18 [00:00<00:02,  6.52plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_040-UKDPUNE_targaon.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_001-UKDPUNE_karad.png

Plotting:  33%|███▎      | 6/18 [00:00<00:01,  6.72plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_033-UKDPUNE_veer_dam.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_004-UKDPUNE_arjunwad_seasonal.png

Plotting:  44%|████▍     | 8/18 [00:01<00:01,  6.95plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_016-ukdpune_dhond.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_035-UKDPUNE_ujjani_reservoir.png

Plotting:  56%|█████▌    | 10/18 [00:01<00:01,  7.04plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_042-UKD PUNE_nandre.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_025-ukdpune_phulgaon.png

Plotting:  67%|██████▋   | 12/18 [00:01<00:00,  7.06plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_043-UKDPUNE_rahu.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_029-ukdpune_paragaon.png

Plotting:  78%|███████▊  | 14/18 [00:02<00:00,  6.93plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_005-UKDPUNE_kurundwad.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_003-UKDPUNE_samdoli_seasonal.png

Plotting:  89%|████████▉ | 16/18 [00:02<00:00,  6.85plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_006-UKDPUNE_terwad_seasonal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_028-ukdpune_sarati.png

Plotting: 100%|██████████| 18/18 [00:02<00:00,  6.86plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_010-ukdpune_narsingpur.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_011-ukdpune_takli.png
Plots generated: 18
Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_krishna_maharashtra_2024-01-01_2024-04-01.gpkg (4561 rows)

water_level downloaded in 18.0 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       18          18          0           18.0
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------

Starting CWC download for station=['006-LKDHYD', '009-lkdhyd', '015-lkdhyd', '017-lkdhyd', '018-LKDHYD', '019-LKDHYD', '022-LKDHYD', '026-LKDHYD', '029-LKDHYD', '034-LKDHYD', '040-LKDHYD'] from 2024-01-01 to 2024-04-01...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 11 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 11/11 [00:00<00:00, 34302.86station/s]
Plotting:   7%|▋         | 2/29 [00:00<00:03,  6.92plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_015-lkdhyd_k._agraharam.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_002-UKDPUNE_warunji.png

Plotting:  14%|█▍        | 4/29 [00:00<00:03,  6.96plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_012-UKDPUNE_wadakbal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_040-UKDPUNE_targaon.png

Plotting:  21%|██        | 6/29 [00:00<00:03,  6.89plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_009-lkdhyd_p.d._jurala.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_001-UKDPUNE_karad.png

Plotting:  28%|██▊       | 8/29 [00:01<00:03,  6.89plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_018-LKDHYD_wadenepally.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_033-UKDPUNE_veer_dam.png

Plotting:  34%|███▍      | 10/29 [00:01<00:02,  7.48plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_017-lkdhyd_nagarjuna_sagar_dam.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_034-LKDHYD_anantharam.png

Plotting:  41%|████▏     | 12/29 [00:01<00:02,  7.19plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_022-LKDHYD_madhira.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_004-UKDPUNE_arjunwad_seasonal.png

Plotting:  48%|████▊     | 14/29 [00:01<00:02,  7.17plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_016-ukdpune_dhond.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_035-UKDPUNE_ujjani_reservoir.png

Plotting:  55%|█████▌    | 16/29 [00:02<00:01,  6.92plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_042-UKD PUNE_nandre.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_040-LKDHYD_valigonda.png

Plotting:  62%|██████▏   | 18/29 [00:02<00:01,  6.89plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_025-ukdpune_phulgaon.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_043-UKDPUNE_rahu.png

Plotting:  69%|██████▉   | 20/29 [00:02<00:01,  6.99plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_029-ukdpune_paragaon.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_005-UKDPUNE_kurundwad.png

Plotting:  76%|███████▌  | 22/29 [00:03<00:01,  6.96plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_003-UKDPUNE_samdoli_seasonal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_026-LKDHYD_halia.png

Plotting:  83%|████████▎ | 24/29 [00:03<00:00,  6.91plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_029-LKDHYD_suddakal.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_006-UKDPUNE_terwad_seasonal.png

Plotting:  90%|████████▉ | 26/29 [00:03<00:00,  7.10plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_028-ukdpune_sarati.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_010-ukdpune_narsingpur.png

Plotting:  97%|█████████▋| 28/29 [00:03<00:00,  7.03plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_006-LKDHYD_jewangi.png
Saved: data_fetch_cwc/cwc/krishna/images/CWC_019-LKDHYD_dameracherla.png

Plotting: 100%|██████████| 29/29 [00:04<00:00,  7.04plot/s]

Saved: data_fetch_cwc/cwc/krishna/images/CWC_011-ukdpune_takli.png
Plots generated: 29
Saved GeoPackage: data_fetch_cwc/cwc/cwc_waterlevel_krishna_telangana_2024-01-01_2024-04-01.gpkg (3043 rows)

water_level downloaded in 5.4 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       11          11          0           5.4
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc
-------------------------------------------------------------

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin,state
0,042-UKD PUNE,2024-01-01 08:00:00,535.000,2.500,m,16.949167,74.529722,POINT (74.52972 16.94917),Godavari,Maharashtra
1,042-UKD PUNE,2024-01-01 13:00:00,534.910,2.410,m,16.949167,74.529722,POINT (74.52972 16.94917),Godavari,Maharashtra
2,042-UKD PUNE,2024-01-01 18:00:00,534.850,2.350,m,16.949167,74.529722,POINT (74.52972 16.94917),Godavari,Maharashtra
3,042-UKD PUNE,2024-01-02 08:00:00,534.850,2.350,m,16.949167,74.529722,POINT (74.52972 16.94917),Godavari,Maharashtra
4,042-UKD PUNE,2024-01-02 13:00:00,534.850,2.350,m,16.949167,74.529722,POINT (74.52972 16.94917),Godavari,Maharashtra
...,...,...,...,...,...,...,...,...,...,...
77066,026-ugdhyd,2024-03-27 06:00:00,206.014,206.014,m,19.100000,78.790000,POINT (78.79 19.1),Krishna,Telangana
77067,026-ugdhyd,2024-03-28 06:00:00,205.991,205.991,m,19.100000,78.790000,POINT (78.79 19.1),Krishna,Telangana
77068,026-ugdhyd,2024-03-29 06:00:00,205.969,205.969,m,19.100000,78.790000,POINT (78.79 19.1),Krishna,Telangana
77069,026-ugdhyd,2024-03-30 06:00:00,205.740,205.740,m,19.100000,78.790000,POINT (78.79 19.1),Krishna,Telangana
77070,026-ugdhyd,2024-03-31 06:00:00,205.930,205.930,m,19.100000,78.790000,POINT (78.79 19.1),Krishna,Telangana

# Test merge only and plot only

In [18]:
dg = swift.merge_only(mode='cwc',input_dir="data_fetch_cwc/", output_dir='test_merge')

Saved GeoPackage: test_merge/cwc/cwc_waterlevel_godavari.gpkg (12314 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_brahmani_and_baitarni.gpkg (56603 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_krishna.gpkg (7604 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_barak_and_others.gpkg (185566 rows)

In [41]:
dg

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,026-LKDHYD,2024-01-01 08:00:00,128.34,0.44,m,16.788056,79.339722,POINT (79.33972 16.78806),None
1,026-LKDHYD,2024-01-01 13:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
2,026-LKDHYD,2024-01-01 18:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
3,026-LKDHYD,2024-01-02 08:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
4,026-LKDHYD,2024-01-02 13:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
...,...,...,...,...,...,...,...,...,...
262082,009-WGDNGP,2024-03-30 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262083,009-WGDNGP,2024-03-30 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262084,009-WGDNGP,2024-03-31 08:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262085,009-WGDNGP,2024-03-31 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
262086,009-WGDNGP,2024-03-31 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None

In [6]:
swift.merge_only(mode= 'cwc', input_dir="data_fetch_cwc", variable=["solar"], output_dir='test_merge')

/tmp/ipykernel_1297630/2378545228.py:1: UserWarning: swift.merge_only(mode='cwc', ...) ignores variable; CWC data only has water levels.
  swift.merge_only(mode= 'cwc', input_dir="data_fetch_cwc", variable=["solar"], output_dir='test_merge')

Saved GeoPackage: test_merge/cwc/cwc_waterlevel_godavari.gpkg (12314 rows)
Saved GeoPackage: test_merge/cwc/cwc_waterlevel_krishna.gpkg (7604 rows)

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,026-LKDHYD,2024-01-01 08:00:00,128.34,0.44,m,16.788056,79.339722,POINT (79.33972 16.78806),None
1,026-LKDHYD,2024-01-01 13:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
2,026-LKDHYD,2024-01-01 18:00:00,128.32,0.42,m,16.788056,79.339722,POINT (79.33972 16.78806),None
3,026-LKDHYD,2024-01-02 08:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
4,026-LKDHYD,2024-01-02 13:00:00,128.26,0.36,m,16.788056,79.339722,POINT (79.33972 16.78806),None
...,...,...,...,...,...,...,...,...,...
19913,009-WGDNGP,2024-03-30 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19914,009-WGDNGP,2024-03-30 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19915,009-WGDNGP,2024-03-31 08:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19916,009-WGDNGP,2024-03-31 13:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None
19917,009-WGDNGP,2024-03-31 18:00:00,218.97,0.47,m,20.795000,79.649444,POINT (79.64944 20.795),None

In [42]:
dh = swift.merge_only(mode= 'wris', input_dir="data_fetch_wris/", variable=["solar", "sediment"], output_dir='test_merge')
dh

Saved GeoPackage: test_merge/wris/godavari_solar_radiation.gpkg (37991 rows)
Saved GeoPackage: test_merge/wris/godavari_sediment.gpkg (38 rows)
Dataset 'solar_radiation' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'sediment' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'solar_radiation' not found in basin: narmada
Saved GeoPackage: test_merge/wris/narmada_sediment.gpkg (1305 rows)
Dataset 'solar_radiation' not found in basin: cauvery
Saved GeoPackage: test_merge/wris/cauvery_sediment.gpkg (4321 rows)
Dataset 'solar_radiation' not found in basin: brahmani and baitarni
Saved GeoPackage: test_merge/wris/brahmani and baitarni_sediment.gpkg (122 rows)

,station_code,time,sed,lat,lon,geometry,basin,variable,solar,unit
0,018-ERDBWN,2024-04-01 08:00:00,0.0870,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
1,018-ERDBWN,2024-07-01 08:00:00,0.0570,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
2,018-ERDBWN,2024-07-02 08:00:00,0.0550,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
3,018-ERDBWN,2024-07-03 08:00:00,0.0610,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
4,018-ERDBWN,2024-07-04 08:00:00,0.0510,20.9308,85.5192,POINT (85.5192 20.9308),brahmani and baitarni,sediment,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43772,006-TDSURAT,2024-10-27 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43773,006-TDSURAT,2024-10-28 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43774,006-TDSURAT,2024-10-29 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43775,006-TDSURAT,2024-10-30 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L
43776,006-TDSURAT,2024-10-31 08:00:00,0.0012,22.0500,73.4653,POINT (73.4653 22.05),narmada,sediment,NaN,g/L

In [22]:
swift.plot_only(mode = 'wris', input_dir="data_fetch_wris/", variable=["solar", 'sediment'], output_dir='test_plot')

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: test_plot/wris/godavari/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plotting godavari / sediment (1 stations)
Saved: test_plot/wris/godavari/sediment/007-ugdhyd_Pachegaon_SEDIM.png
Dataset 'solar_radiation' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'sediment' not found in basin: east flowing rivers between mahanadi and pennar
Dataset 'solar_radiation' not found in basin: narmada

Plotting narmada / sediment (4 stations)
Saved: test_plot/wris/narmada/sediment/013 NDBHP_ Sandia_SEDIM.png
Saved: test_plot/wris/narmada/sediment/016-NDBHP_Narmadapuram_SEDIM.png
Saved: test_plot/wris/narmada/sediment/009-ndbhp_Manot_SEDIM.png
Saved: test_plot/wris/narmada/sediment/006-TDSURAT_CHANWADA_SEDIM.png
Dataset 'solar_radiation' not found in basin: cauvery

Plotting cauvery / sediment (17 stations)
Saved: test_plot/wris/cauvery/sediment/014-srdcbe_NALLAMARANPATTY_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/020-CDBNG_T.K.HALLI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png
Saved: test_plot/wris/cauvery/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png
Dataset 'solar_radiation' not found in basin: brahmani and baitarni

Plotting brahmani and baitarni / sediment (1 stations)
Saved: test_plot/wris/brahmani and baitarni/sediment/018-ERDBWN_Altuma_SEDIM.png

Plots generated: 26

In [23]:
swift.plot_only(mode = 'cwc', input_dir="data_fetch_cwc/", variable=["solar", 'sediment'], output_dir='test_plot')

Saved: test_plot/cwc/barak_and_others/CWC_017-MDSIL_muhammedpur.png
Saved: test_plot/cwc/barak_and_others/CWC_022-MBDGHY_manughat.png
Saved: test_plot/cwc/barak_and_others/CWC_019-MDSIL_patharkandi.png
Saved: test_plot/cwc/barak_and_others/CWC_024- MDSIL_chiripool.png
Saved: test_plot/cwc/barak_and_others/CWC_012-MDSIL_sonamura.png
Saved: test_plot/cwc/barak_and_others/CWC_005-mdsil_haora.png
Saved: test_plot/cwc/barak_and_others/CWC_022-MDSIL_sonamura-ii.png
Saved: test_plot/cwc/barak_and_others/CWC_016-MDSIL_borkhola.png
Saved: test_plot/cwc/barak_and_others/CWC_021-MDSIL_kaliganj.png
Saved: test_plot/cwc/barak_and_others/CWC_028- MDSIL_neairgram.png
Saved: test_plot/cwc/barak_and_others/CWC_002-MDSIL_kamalpur.png
Saved: test_plot/cwc/barak_and_others/CWC_021-MBDGHY_karimganj.png
Saved: test_plot/cwc/barak_and_others/CWC_014-MDSIL_kailashahar_gdsq_site.png
Saved: test_plot/cwc/barak_and_others/CWC_013-MDSIL_belonia.png
Saved: test_plot/cwc/barak_and_others/CWC_004-mdsil_khowai.png
Saved: test_plot/cwc/barak_and_others/CWC_006-MDSIL_gajaria.png
Saved: test_plot/cwc/barak_and_others/CWC_008-MDSIL_anipur.png

Plots generated: 137

In [24]:
# Sanity check: public Python API surface
import swift_app as swift

public_attrs = [
    "wris",
    "cwc",
    "fetch",
    "merge_only",
    "plot_only",
    "datasets",
    "basins",
    "cite",
    "coffee",
]

api_flags = {name: hasattr(swift, name) for name in public_attrs}
api_flags

{'wris': True,
 'cwc': True,
 'fetch': True,
 'merge_only': True,
 'plot_only': True,
 'datasets': False,
 'basins': False,
 'cite': True,
 'coffee': True}

# Test direct download functions

In [10]:
basins_wris = swift.wris.basins(variable="sediment")
basins_wris

SWIFT Table
Rows: 17 | Columns: 3
----------------------------------------
    id                                              basin  variable
0    1                              Brahmani and Baitarni  sediment
1    2                                            Cauvery  sediment
2    3    East flowing rivers between Mahanadi and Pennar  sediment
3    4  East flowing rivers between Pennar and Kanyaku...  sediment
4    5                                           Godavari  sediment
5    6                                            Krishna  sediment
6    7                                           Mahanadi  sediment
7    8                                               Mahi  sediment
8    9  Minor rivers draining into Myanmar and Bangladesh  sediment
9   10                                            Narmada  sediment
10  11                                             Pennar  sediment
11  12                                          Sabarmati  sediment
12  13                                       Subernarekha  sediment
13  14                                               Tapi  sediment
14  15      West flowing rivers from Tadri to Kanyakumari  sediment
15  16             West flowing rivers from Tapi to Tadri  sediment
16  17  West flowing rivers of Kutch and Saurashtra in...  sediment

In [ ]:
# Test wris download via public namespace API using table (no basin and variable input)
swift.wris.download(basins_wris[0:2],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_wris_download",
    format="xlsx",
    overwrite=False,
    merge=False,
    plot=True,
    quiet=False,
)

Starting fetch for stations table (rows=2) from 2024-01-01 to 2024-01-07...

/home/carbform/swift/swift_app/api.py:996: UserWarning: Fetching WRIS data for basin-level input (all stations per basin/variable). Dispatching 2 basin-variable combinations; this may take a long time.
  return fetch(

Starting WRIS download for basin='Brahmani and Baitarni', Variables=sediment from 2024-01-01 to 2024-01-07...

Dataset: sediment
Using cached station discovery
Stations skipped (already downloaded): 1
Tip: call with overwrite=True to refresh data.

sediment: 100%|██████████| 1/1 [00:06<00:00,  6.52s/station]

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          1           0           1           6.5
-------------------------------------------------------------
Output directory: data_wris_download/wris/brahmani and baitarni
-------------------------------------------------------------
Starting WRIS download for basin='Cauvery', Variables=sediment from 2024-01-01 to 2024-01-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 18/18 [00:07<00:00,  2.41station/s]

Saved GeoPackage: data_wris_download/wris/cauvery/Cauvery_sediment_2024-01-01_2024-01-07.gpkg (93 rows)

sediment downloaded in 7.5 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          15          15          0           7.5
-------------------------------------------------------------
Output directory: data_wris_download/wris/cauvery
-------------------------------------------------------------

Plot-only mode enabled.

Plotting cauvery / sediment (15 stations)
Saved: data_wris_download/wris/cauvery/images/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png

Plots generated: 15

In [3]:
stations_wris = swift.wris.stations(variable="sediment",basin='Cauvery')

Searching the WRIS database... This might take some time.
The station list returned does not guarantee time series data availability for all time periods.

In [4]:
stations_wris

,station_code,station_name,latitude,longitude,river,basin,variable
0,003-SRDCBE,KUDLUR,11.8406,77.4628,Palar,Cauvery,sediment
1,003-SWRDKOCHI,MUTHANKERA,11.8081,76.0842,Kabini,Cauvery,sediment
2,005-srdcbe,THENGUMARAHADA,11.5728,76.9192,Moyar,Cauvery,sediment
3,008-SRDCBE,SAVANDAPUR,11.5200,77.5100,Moyar,Cauvery,sediment
4,010- SRDCBE,NELLITHURAI,11.2878,76.8911,Moyar,Cauvery,sediment
5,011-CDBNG,SAKLESHPUR,12.9433,75.7939,Hemavathi,Cauvery,sediment
6,012-SRDCBE,ELUNUTHIMANGALAM,11.0317,77.8875,Noyyal,Cauvery,sediment
7,013-CDBNG,M.H. HALLI,12.8200,76.1411,Hemavathi,Cauvery,sediment
8,014-srdcbe,NALLAMARANPATTY,10.8808,77.9847,Kodavanar,Cauvery,sediment
9,017-CDBNG,AKKIHEBBAL,12.5986,76.4006,Hemavathi,Cauvery,sediment
10,018-CDBNG,T. NARASIPUR,12.2303,76.8944,Kabini,Cauvery,sediment
11,019-CDBNG,T. BEKKUPE,12.5072,77.4281,Arkavathi,Cauvery,sediment
12,020-CDBNG,T.K.HALLI,12.4119,77.1928,Shimsha,Cauvery,sediment
13,035-SRDCBE,Gandhavayal,11.3742,76.9922,Moyar,Cauvery,sediment
14,036-SRDCBE,Alandurai,10.9519,76.7853,Noyyal,Cauvery,sediment
15,038-SRDCBE,Odendurai,11.3217,76.8928,Moyar,Cauvery,sediment
16,046-SRDCBE,LAKSHMANANPATTI,10.4981,77.9458,Kodavanar,Cauvery,sediment
17,CCN00J5,BENDRAHALLI,12.1289,77.0831,Suvarnavathi,Cauvery,sediment

In [ ]:
# Test wris download via public namespace API using table (no basin and variable input - using station return table)
swift.wris.download(
stations_wris[0:4],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_wris_download",
    format="xlsx",
    overwrite=True,
    merge=False,
    plot=True,
    quiet=False,
)

Starting fetch for stations table (rows=4) from 2024-01-01 to 2024-01-07...
Starting WRIS download for basin='Cauvery', Variables=sediment from 2024-01-01 to 2024-01-07...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:00<00:00,  7.02station/s]

Saved GeoPackage: data_wris_download/wris/cauvery/Cauvery_sediment_2024-01-01_2024-01-07.gpkg (27 rows)

sediment downloaded in 0.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          4           4           0           0.6
-------------------------------------------------------------
Output directory: data_wris_download/wris/cauvery
-------------------------------------------------------------

Plot-only mode enabled.

Plotting cauvery / sediment (15 stations)
Saved: data_wris_download/wris/cauvery/images/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png

Plots generated: 15

In [ ]:
# Test wris download via public namespace API using table (with basin and variable input)
swift.wris.download(
    basin=["Cauvery","Brahmani and Baitarni"],
    variable=["solar", "sediment"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_wris_download",
    format="xlsx",
    overwrite=True,
    merge=False,
    plot=True,
    quiet=False
)

Starting WRIS download for basin='Cauvery', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery
All stations already downloaded — skipping download step.

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 18/18 [00:07<00:00,  2.37station/s]

Saved GeoPackage: data_wris_download/wris/cauvery/Cauvery_sediment_2024-01-01_2024-01-07.gpkg (93 rows)

sediment downloaded in 7.7 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   0           0           0           0.0
sediment          15          15          0           7.7
-------------------------------------------------------------
Output directory: data_wris_download/wris/cauvery
-------------------------------------------------------------

Plot-only mode enabled.

Plotting cauvery / sediment (15 stations)
Saved: data_wris_download/wris/cauvery/images/sediment/011-CDBNG_SAKLESHPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/038-SRDCBE_Odendurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/008-SRDCBE_SAVANDAPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/036-SRDCBE_Alandurai_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SRDCBE_KUDLUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/010- SRDCBE_NELLITHURAI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/018-CDBNG_T. NARASIPUR_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/005-srdcbe_THENGUMARAHADA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/019-CDBNG_T. BEKKUPE_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/003-SWRDKOCHI_MUTHANKERA_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/012-SRDCBE_ELUNUTHIMANGALAM_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/013-CDBNG_M.H. HALLI_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/035-SRDCBE_Gandhavayal_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/017-CDBNG_AKKIHEBBAL_SEDIM.png
Saved: data_wris_download/wris/cauvery/images/sediment/046-SRDCBE_LAKSHMANANPATTI_SEDIM.png

Plots generated: 15
Starting WRIS download for basin='Brahmani and Baitarni', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery
All stations already downloaded — skipping download step.

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 2/2 [00:07<00:00,  3.57s/station]

Saved GeoPackage: data_wris_download/wris/brahmani and baitarni/Brahmani and Baitarni_sediment_2024-01-01_2024-01-07.gpkg (1 rows)

sediment downloaded in 7.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   0           0           0           0.0
sediment          1           1           0           7.2
-------------------------------------------------------------
Output directory: data_wris_download/wris/brahmani and baitarni
-------------------------------------------------------------

Plot-only mode enabled.

Plotting brahmani and baitarni / sediment (1 stations)
Saved: data_wris_download/wris/brahmani and baitarni/images/sediment/018-ERDBWN_Altuma_SEDIM.png

Plots generated: 1

/home/carbform/swift/swift_app/plot_station_timeseries.py:215: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())

In [3]:
basins_cwc = swift.cwc.basins()
basins_cwc

SWIFT Table
Rows: 22 | Columns: 2
----------------------------------------
                                                basin  station_count
0                                    Barak and Others             42
1                               Brahmani and Baitarni             21
2                                         Brahmaputra            139
3                                             Cauvery             53
4     East flowing rivers between Mahanadi and Pennar             21
5   East flowing rivers between Pennar and Kanyaku...             39
6                                               Ganga            537
7                                            Godavari             90
8                                               Indus             18
9                                             Krishna             85
10                                           Mahanadi             60
11                                               Mahi             12
12  Minor rivers draining into Myanmar and Bangladesh              4
13                                            Narmada             26
14                                             Pennar             13
15                                          Sabarmati              6
16                                       Subernarekha             20
17                                               Tapi             25
18      West flowing rivers from Tadri to Kanyakumari             33
19             West flowing rivers from Tapi to Tadri             26
20  West flowing rivers of Kutch and Saurashtra in...             10
21                                       Yamuna Basin              1

In [4]:
# Test CWC download via public namespace API (using basin tables)
swift.cwc.download(
basins_cwc[0:2],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_cwc",
    format="csv",
    overwrite=True,
    merge=False,
    plot=False,
    quiet=False,
)

Starting fetch for stations table (rows=2) from 2024-01-01 to 2024-01-07...
Starting CWC download for station=['001-MDSIL', '001-MIDSHL', '002-MDSIL', '002-midshl', '003-MDSIL', '004-mdsil', '005-mdsil', '006-MDSIL', '007-MDSIL', '008-MDSIL', '009-MBDGHY', '009-mdsil', '010-MBDGHY', '010-mdsil', '011-MBDGHY', '011-mdsil', '012-MBDGHY', '012-MDSIL', '013-MBDGHY', '013-MDSIL', '014-MDSIL', '015-MBDGHY', '015-MDSIL', '016-MBDGHY', '016-MDSIL', '017-MBDghy', '017-MDSIL', '018-MDSIL', '019-MBDGHY', '019-MDSIL', '020-MDSIL', '021-MBDGHY', '021-MDSIL', '022-MBDGHY', '022-MDSIL', '023-MBDGHY', '023-MDSIL', '024- MDSIL', '026- MDSIL', '027- MDSIL', '028- MDSIL', '030-MBDGHY'] from 2024-01-01 to 2024-01-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 42 | Format: CSV | Time range: 2024–2024
Basin filter: Barak and Others
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

/home/carbform/swift/swift_app/api.py:1225: UserWarning: Fetching CWC data for basin-level input (all stations per basin). Dispatching 2 basins; this may take a long time.
  return fetch(
water_level: 100%|██████████| 42/42 [00:00<00:00, 43604.15station/s]

Saved GeoPackage: data_cwc/cwc/cwc_waterlevel_barak_and_others_2024-01-01_2024-01-07.gpkg (648 rows)

water_level downloaded in 16.5 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       36          36          0           16.5
-------------------------------------------------------------
Output directory: data_cwc/cwc
-------------------------------------------------------------
Starting CWC download for station=['013-ERDBWN', '014-ERDBWN', '015-ERDBWN', '016-ERDBWN', '017-ERDBWN', '018-ERDBWN', '019-ERDBWN', '020-ERDBWN', '022-ERDBWN', '023-ERDBWN', '049-ERDBWN', '050-ERDBWN', '051-ERDBWN', '052-ERDBWN', '053-ERDBWN', '055-erdbwn', '061-ERDBWN', '065-ERDBWN', '067-ERDBWN', '068-ERDBWN', '073-ERDBWN'] from 2024-01-01 to 2024-01-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 21 | Format: CSV | Time range: 2024–2024
Basin filter: Brahmani and Baitarni
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 21/21 [00:00<00:00, 53773.13station/s]

Saved GeoPackage: data_cwc/cwc/cwc_waterlevel_brahmani_and_baitarni_2024-01-01_2024-01-07.gpkg (233 rows)

water_level downloaded in 15.3 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       13          13          0           15.3
-------------------------------------------------------------
Output directory: data_cwc/cwc
-------------------------------------------------------------

In [7]:
stations_cwc = swift.cwc.stations(basin="Tapi", state="Maharashtra")
stations_cwc

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,008-TDSURAT,DAHIGAON,Girna,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",20.833611,75.423889,215.798,NaN,NaN,222.100,2006-08-08
1,010-TDSURAT,LAKHPURI,Purna,Tapi,Maharashtra,Amravati,"Executive Engineer, Tapi Division, Surat",20.845556,77.360556,259.000,NaN,NaN,271.015,1979-08-10
2,011-TDSURAT,GOPALKHEDA,Purna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.874167,76.991389,236.000,245.000,NaN,252.450,2015-08-06
3,012-TDSURAT,YERLI,Purna,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.936389,76.474167,213.000,221.000,223.000,233.700,2006-08-07
4,013-ukdpune,Anjanari,Kajvi,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Cauvery Division, Bangaluru",16.934722,73.514167,11.000,16.500,17.500,20.500,2019-08-05
5,014-ukdpune,Badlapur,Ulhas,West flowing rivers from Tapi to Tadri,Maharashtra,Thane,"Upper Krishna Division(UKD), Pune",19.162222,73.254167,9.017,16.500,17.500,26.162,2005-07-26
6,015-ukdpune,Belne Bridge,Gad,West flowing rivers from Tapi to Tadri,Maharashtra,Sindudurg,"Cauvery Division, Bangaluru",16.220833,73.594722,8.500,15.500,16.500,20.010,2021-07-23
7,016-TDSURAT,HATHNUR,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.070000,75.950000,207.000,212.000,214.000,NaN,NaN
8,017-TDSURAT,BHUSAWAL,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.068333,75.780278,174.000,NaN,185.320,184.900,NaN
9,017-ukdpune,Mahad,Savitri,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.092222,73.460278,1.000,10.000,11.000,13.800,2021-07-23
10,020-TDSURAT,SARANGKHEDA,Tapi,Tapi,Maharashtra,Nandurbar,"Executive Engineer, Tapi Division, Surat",21.428333,74.527222,108.000,132.050,132.500,127.080,2006-08-08
11,021-ukdpune,Mangaon,Kal,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.231389,73.283056,3.905,9.255,10.255,10.565,2015-06-15
12,022-ukdpune,Nagothane,Amba,West flowing rivers from Tapi to Tadri,Maharashtra,Raigad,"Upper Krishna Division(UKD), Pune",18.518889,73.156389,2.000,9.255,10.255,13.750,2005-07-25
13,023-ukdpune,Niivali,Bav,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Upper Krishna Division(UKD), Pune",17.066944,73.450833,0.455,9.400,11.000,15.155,2021-07-23
14,027-TDSURAT,OZERKHEDA,Wagh,West flowing rivers from Tapi to Tadri,Maharashtra,Nashik,"Executive Engineer, Tapi Division, Surat",20.100278,73.271111,80.100,NaN,NaN,96.100,2004-08-04
15,035-TDSURAT,DURVESH,Vaitarna,West flowing rivers from Tapi to Tadri,Maharashtra,Thane,"Executive Engineer, Tapi Division, Surat",19.712500,72.930556,0.000,NaN,NaN,16.130,NaN
16,036-TDSURAT,LOHARA,Mun,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.816389,76.763889,0.000,241.400,243.000,242.750,2019-09-17
17,037-TDSURAT,AKOLA,Morna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.708056,76.993056,269.000,279.500,282.450,282.450,NaN
18,038-TDSURAT,KURANKHEDA,Katepurna,Tapi,Maharashtra,Akola,"Executive Engineer, Tapi Division, Surat",20.703056,77.242778,276.000,NaN,NaN,282.900,2022-08-09
19,039-TDSURAT,WANKHED,Tapi,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.988333,76.716667,251.000,253.750,254.900,257.200,2019-08-09
20,040-TDSURAT,PIMPRI,Tapi,Tapi,Maharashtra,Jalgaon,"Executive Engineer, Tapi Division, Surat",21.128333,75.667222,0.000,NaN,NaN,174.000,NaN
21,041-TDSURAT,TALASWADA,Nalganaga,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.946667,76.203056,0.000,NaN,NaN,227.300,2023-07-19
22,041-ukdpune,Muradpur,Vashisti,West flowing rivers from Tapi to Tadri,Maharashtra,Ratnagiri,"Upper Krishna Division(UKD), Pune",17.539722,73.523889,-5.000,5.000,7.000,8.400,2021-07-23
23,042-TDSURAT,DHUPESHWAR,Purna,Tapi,Maharashtra,Buldana,"Executive Engineer, Tapi Division, Surat",20.957500,76.279167,203.000,220.500,222.000,220.400,2023-07-22
24,050-TDSURAT,SHIRPUR,Arunawati,Tapi,Maharashtra,Dhule,"Executive Engineer, Tapi Division, Surat",21.339444,74.890000,141.000,NaN,NaN,149.800,2019-08-09

In [8]:
# Test CWC download via public namespace API (using basin tables)
swift.cwc.download(
stations_cwc[0:2],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_cwc",
    format="csv",
    overwrite=True,
    merge=False,
    plot=False,
    quiet=False,
)

Starting fetch for stations table (rows=2) from 2024-01-01 to 2024-01-07...
Starting CWC download for station=['008-TDSURAT', '010-TDSURAT'] from 2024-01-01 to 2024-01-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 2 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 2/2 [00:00<00:00, 7598.38station/s]

Saved GeoPackage: data_cwc/cwc/cwc_waterlevel_tapi_maharashtra_2024-01-01_2024-01-07.gpkg (33 rows)

water_level downloaded in 0.2 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       2           2           0           0.2
-------------------------------------------------------------
Output directory: data_cwc/cwc
-------------------------------------------------------------

In [4]:
cwc_for_fetch.attrs

{'source': 'cwc', 'basin': 'Godavari', 'state': 'Telangana'}

# test gdf returns

In [9]:
import swift_app as swift
import pandas as pd
import glob

In [10]:
gdf = swift.wris.download(
    basin=["Krishna", "Godavari"],
    variable=["solar", "sediment"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir= 'test_gdf',
    plot=False, overwrite=True, merge=True
)

# gdf is a GeoDataFrame with the merged timeseries

Starting WRIS download for basin='Krishna', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:00<00:00,  5.53station/s]

Saved GeoPackage: test_gdf/wris/krishna/krishna_solar_radiation_2024-01-01_2024-01-07.gpkg (1344 rows)

solar_radiation downloaded in 0.9 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 20/20 [00:13<00:00,  1.47station/s]

Saved GeoPackage: test_gdf/wris/krishna/krishna_sediment_2024-01-01_2024-01-07.gpkg (17 rows)

sediment downloaded in 13.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   5           5           0           0.9
sediment          5           5           0           13.6
-------------------------------------------------------------
Output directory: test_gdf/wris/krishna
-------------------------------------------------------------
Starting WRIS download for basin='Godavari', Variables=solar, sediment from 2024-01-01 to 2024-01-07...

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:00<00:00,  3.47station/s]

Saved GeoPackage: test_gdf/wris/godavari/godavari_solar_radiation_2024-01-01_2024-01-07.gpkg (748 rows)

solar_radiation downloaded in 0.9 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:06<00:00,  1.65s/station]

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           0.9
sediment          0           0           0           6.6
-------------------------------------------------------------
Output directory: test_gdf/wris/godavari
-------------------------------------------------------------

In [11]:
gdf

,station_code,time,solar,lat,lon,geometry,basin,variable,sed
0,Rukadi,2024-01-01 00:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
1,Rukadi,2024-01-01 01:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
2,Rukadi,2024-01-01 02:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
3,Rukadi,2024-01-01 03:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
4,Rukadi,2024-01-01 04:30:00,0.0,16.7200,74.3556,POINT (74.3556 16.72),Krishna,solar,NaN
...,...,...,...,...,...,...,...,...,...
2104,7D901252,2024-01-07 18:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2105,7D901252,2024-01-07 19:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2106,7D901252,2024-01-07 20:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2107,7D901252,2024-01-07 21:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN
2108,7D901252,2024-01-08 00:00:00,0.0,16.3814,80.8530,POINT (80.853 16.3814),Godavari,solar,NaN

In [12]:
gdf = swift.cwc.download(
    basin=["Krishna", "Godavari"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir= 'test_gdf',
    plot=False, overwrite=True, merge=True
)

# gdf is a GeoDataFrame with the merged timeseries

Starting CWC download for station=None from 2024-01-01 to 2024-01-07...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 175 | Format: CSV | Time range: 2024–2024
Basin filter: Krishna, Godavari
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 175/175 [00:00<00:00, 58092.85station/s]

Saved GeoPackage: test_gdf/cwc/cwc_waterlevel_all_stations_2024-01-01_2024-01-07.gpkg (2685 rows)

water_level downloaded in 16.5 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       158         158         0           16.5
-------------------------------------------------------------
Output directory: test_gdf/cwc
-------------------------------------------------------------

In [14]:
gdf

,station_code,time,wse,water_depth,unit,lat,lon,geometry,basin
0,018-ukdpune,2024-01-01 08:00:00,452.00,0.00,m,17.286389,75.637222,POINT (75.63722 17.28639),all_stations
1,018-ukdpune,2024-01-01 13:00:00,452.00,0.00,m,17.286389,75.637222,POINT (75.63722 17.28639),all_stations
2,018-ukdpune,2024-01-01 18:00:00,452.00,0.00,m,17.286389,75.637222,POINT (75.63722 17.28639),all_stations
3,018-ukdpune,2024-01-02 08:00:00,452.00,0.00,m,17.286389,75.637222,POINT (75.63722 17.28639),all_stations
4,018-ukdpune,2024-01-02 13:00:00,452.00,0.00,m,17.286389,75.637222,POINT (75.63722 17.28639),all_stations
...,...,...,...,...,...,...,...,...,...
2680,010-CDBNG,2024-01-05 13:00:00,587.90,2.90,m,13.697222,75.335556,POINT (75.33556 13.69722),all_stations
2681,010-CDBNG,2024-01-05 18:00:00,588.00,3.00,m,13.697222,75.335556,POINT (75.33556 13.69722),all_stations
2682,010-CDBNG,2024-01-06 08:00:00,588.03,3.03,m,13.697222,75.335556,POINT (75.33556 13.69722),all_stations
2683,010-CDBNG,2024-01-06 13:00:00,588.01,3.01,m,13.697222,75.335556,POINT (75.33556 13.69722),all_stations
2684,010-CDBNG,2024-01-06 18:00:00,588.01,3.01,m,13.697222,75.335556,POINT (75.33556 13.69722),all_stations

In [ ]:
gdf = swift.merge_only(mode = 'wris', input_dir="output", variable=["solar", "sediment"])

{('Krishna',
  'solar'):       station_code                 time  solar     unit      lat      lon  \
 0           Rukadi  2024-01-01 00:30:00    0.0  watt/m2  16.7200  74.3556
 1           Rukadi  2024-01-01 01:30:00    0.0  watt/m2  16.7200  74.3556
 2           Rukadi  2024-01-01 02:30:00    0.0  watt/m2  16.7200  74.3556
 3           Rukadi  2024-01-01 03:30:00    0.0  watt/m2  16.7200  74.3556
 4           Rukadi  2024-01-01 04:30:00    0.0  watt/m2  16.7200  74.3556
 ...            ...                  ...    ...      ...      ...      ...
 1339  Patryachiwad  2024-01-07 23:00:00    1.0  watt/m2  16.6161  73.9917
 1340  Patryachiwad  2024-01-07 23:15:00    1.0  watt/m2  16.6161  73.9917
 1341  Patryachiwad  2024-01-07 23:30:00    2.0  watt/m2  16.6161  73.9917
 1342  Patryachiwad  2024-01-07 23:45:00    0.0  watt/m2  16.6161  73.9917
 1343  Patryachiwad  2024-01-08 00:00:00    5.0  watt/m2  16.6161  73.9917

                      geometry
 0       POINT (74.3556 16.72)
 1       POINT (74.3556 16.72)
 2       POINT (74.3556 16.72)
 3       POINT (74.3556 16.72)
 4       POINT (74.3556 16.72)
 ...                       ...
 1339  POINT (73.9917 16.6161)
 1340  POINT (73.9917 16.6161)
 1341  POINT (73.9917 16.6161)
 1342  POINT (73.9917 16.6161)
 1343  POINT (73.9917 16.6161)

 [1344 rows x 7 columns],
 ('Krishna',
  'sediment'):     station_code                 time    sed unit      lat      lon  \
 0    003-UKDPUNE  2024-01-01 08:00:00  0.000  g/L  16.8564  74.4967
 1    003-UKDPUNE  2024-01-02 08:00:00  0.000  g/L  16.8564  74.4967
 2    003-UKDPUNE  2024-01-03 08:00:00  0.000  g/L  16.8564  74.4967
 3    003-UKDPUNE  2024-01-04 08:00:00  0.000  g/L  16.8564  74.4967
 4    003-UKDPUNE  2024-01-05 08:00:00  0.000  g/L  16.8564  74.4967
 5    003-UKDPUNE  2024-01-06 08:00:00  0.000  g/L  16.8564  74.4967
 6    003-UKDPUNE  2024-01-07 08:00:00  0.000  g/L  16.8564  74.4967
 7    002-UKDPUNE  2024-01-01 08:00:00  0.000  g/L  17.2728  74.1647
 8    002-UKDPUNE  2024-01-02 08:00:00  0.000  g/L  17.2728  74.1647
 9    002-UKDPUNE  2024-01-03 08:00:00  0.000  g/L  17.2728  74.1647
 10   002-UKDPUNE  2024-01-04 08:00:00  0.000  g/L  17.2728  74.1647
 11   002-UKDPUNE  2024-01-05 08:00:00  0.000  g/L  17.2728  74.1647
 12   002-UKDPUNE  2024-01-06 08:00:00  0.000  g/L  17.2728  74.1647
 13   002-UKDPUNE  2024-01-07 08:00:00  0.000  g/L  17.2728  74.1647
 14     011-cdbmg  2024-01-01 09:00:00  0.013  g/L  13.5225  75.3036
 15    022-LKDHYD  2024-01-01 08:00:00  0.000  g/L  16.9181  80.3589
 16  042-UKD PUNE  2024-01-01 08:00:00  0.000  g/L  16.9492  74.5297

                    geometry
 0   POINT (74.4967 16.8564)
 1   POINT (74.4967 16.8564)
 2   POINT (74.4967 16.8564)
 3   POINT (74.4967 16.8564)
 4   POINT (74.4967 16.8564)
 5   POINT (74.4967 16.8564)
 6   POINT (74.4967 16.8564)
 7   POINT (74.1647 17.2728)
 8   POINT (74.1647 17.2728)
 9   POINT (74.1647 17.2728)
 10  POINT (74.1647 17.2728)
 11  POINT (74.1647 17.2728)
 12  POINT (74.1647 17.2728)
 13  POINT (74.1647 17.2728)
 14  POINT (75.3036 13.5225)
 15  POINT (80.3589 16.9181)
 16  POINT (74.5297 16.9492)  ,
 ('Godavari',
  ('solar',
   'sediment')):     station_code                 time  solar     unit      lat      lon  \
 0       7D8FED08  2024-01-01 00:00:00    0.0  watt/m2  17.2067  81.5142
 1       7D8FED08  2024-01-01 01:00:00    0.0  watt/m2  17.2067  81.5142
 2       7D8FED08  2024-01-01 02:00:00    0.0  watt/m2  17.2067  81.5142
 3       7D8FED08  2024-01-01 03:00:00    0.0  watt/m2  17.2067  81.5142
 4       7D8FED08  2024-01-01 04:00:00    0.0  watt/m2  17.2067  81.5142
 ..           ...                  ...    ...      ...      ...      ...
 743     7D901252  2024-01-07 18:00:00    0.0  watt/m2  16.3814  80.8530
 744     7D901252  2024-01-07 19:00:00    0.0  watt/m2  16.3814  80.8530
 745     7D901252  2024-01-07 20:00:00    0.0  watt/m2  16.3814  80.8530
 746     7D901252  2024-01-07 21:00:00    0.0  watt/m2  16.3814  80.8530
 747     7D901252  2024-01-08 00:00:00    0.0  watt/m2  16.3814  80.8530

                     geometry
 0    POINT (81.5142 17.2067)
 1    POINT (81.5142 17.2067)
 2    POINT (81.5142 17.2067)
 3    POINT (81.5142 17.2067)
 4    POINT (81.5142 17.2067)
 ..                       ...
 743   POINT (80.853 16.3814)
 744   POINT (80.853 16.3814)
 745   POINT (80.853 16.3814)
 746   POINT (80.853 16.3814)
 747   POINT (80.853 16.3814)

 [748 rows x 7 columns]}

# Test other features

In [ ]:
# Test plot_only() with mode-based API (requires existing WRIS output)
from pathlib import Path

if Path("output").exists():
    swift.plot_only(mode="wris", input_dir="output", output_dir="output")
else:
    print("output/ not found; run a WRIS download cell first.")

In [15]:
# Test cite() and coffee() helpers (side-effect: print to stdout)
import swift_app as swift

swift.cite()
swift.coffee()

====================================================================

SWIFT — Simple Water Information Fetch Tool
Carbform • carbform.github.io

Version: 1.0.0 — Arctic Amsterdam

███████╗██╗    ██╗██╗███████╗████████╗
██╔════╝██║    ██║██║██╔════╝╚══██╔══╝
███████╗██║ █╗ ██║██║█████╗     ██║
╚════██║██║███╗██║██║██╔══╝     ██║
███████║╚███╔███╔╝██║██║        ██║
╚══════╝ ╚══╝╚══╝ ╚═╝╚═╝        ╚═╝

====================================================================


    If you use SWIFT in your research, please cite:

    Sarat, C., Dash, D., & Kumar, A. (2026).
    SWIFT: Automated Retrieval of Hydrological Station Data
    from India-WRIS and CWC Portals.
    Journal of Open Source Software.

    Repository:
    https://github.com/carbform/swift


        ( (
        ) )
        ........
        |      |]
        \      /
        `----'
        TIME FOR A COFFEE BREAK

Many kinds of monkeys have a strong taste for tea, coffee and spirituous liqueurs. - Charles Darwin

In [16]:
swift.help()

SWIFT Python API help
=====================

Namespaces
----------
- swift.wris.download(basin, variable, ...)
- swift.wris.stations(basin, variable, delay=0.25)
- swift.cwc.download(station=None, ...)
- swift.cwc.stations(station=None, basin=None, river=None, state=None, refresh=False)

Core helpers
------------
- swift.fetch(stations_df, ...)
- swift.merge_only(input_dir=None, output_dir=None, mode=None, variable=None)
- swift.plot_only(input_dir=None, output_dir=None, cwc=False, mode=None, variable=None)

Backward-compatible aliases
---------------------------
- swift.merge(...)
- swift.plot(...)

Utility helpers
---------------
- swift.cite()
- swift.coffee()
- swift.wris.variables()  (WRIS variable table)
- swift.wris.basins(variable=...)  (WRIS basin table; optionally expanded by variable)
- swift.cwc.basins()      (CWC basin table from station metadata)

Quick examples
--------------
1) Download WRIS discharge for Krishna:
    swift.wris.download(basin="Krishna", variable="discharge")

2) Query stations then fetch:
    stations = swift.wris.stations(basin=["Godavari", "Krishna"], variable=["solar", "sediment"])
    swift.fetch(stations, output_dir="output", merge=True, plot=True)

3) Download CWC data:
    swift.cwc.download(station=["040-CDJAPR"], start_date="2024-01-01", end_date="2024-01-07")

Need CLI help instead?
----------------------
Use: swift.cli_help()   # equivalent to `swift -h`

In [43]:
import geopandas as gpd
# Let's check dh since we ran merge_only on WRIS
try:
    print("dh columns:", dh.columns)
    print("dg columns:", dg.columns)
except:
    pass

dh columns: Index(['station_code', 'time', 'sed', 'lat', 'lon', 'geometry', 'basin',
       'variable', 'solar', 'unit'],
      dtype='str')
dg columns: Index(['station_code', 'time', 'wse', 'water_depth', 'unit', 'lat', 'lon',
       'geometry', 'basin'],
      dtype='str')

## Additional examples: quick checks + invalid input handling
These examples are lightweight and aligned with current public API behavior in `tests/test_api_public.py`.

In [ ]:
# Positive example 1: WRIS basin-variable expansion (no download)
wris_basin_matrix = swift.wris.basins(variable=["discharge", "solar"])

print("Rows:", len(wris_basin_matrix))
print(wris_basin_matrix.head(6))
print("attrs:", wris_basin_matrix.attrs)

In [ ]:
# Positive example 2: CWC basin summary table (local metadata-backed)
cwc_basin_summary = swift.cwc.basins()
print("Rows:", len(cwc_basin_summary))
print(cwc_basin_summary.head(10))

In [ ]:
# Invalid-input examples: these should raise clear errors
from pathlib import Path

def expect_error(label, fn):
    try:
        fn()
        print(f"❌ {label}: expected an error, but call succeeded")
    except Exception as e:
        print(f"✅ {label}: {type(e).__name__} -> {e}")

expect_error(
    "Unknown WRIS variable",
    lambda: swift.wris.basins(variable="not_a_real_variable"),
)

expect_error(
    "wris.stations() missing variable",
    lambda: swift.wris.stations("Godavari", None),
)

expect_error(
    "fetch() invalid source type",
    lambda: swift.fetch("invalid_source"),
)

missing_dir = Path("_definitely_missing_input_dir_")
expect_error(
    "plot_only() with missing input_dir",
    lambda: swift.plot_only(input_dir=str(missing_dir), output_dir="test_plot_invalid"),
)

## Extra examples: station/basin table flows + edge-case validation
These are additional, low-cost checks based on the current repository behavior and tests.

In [ ]:
# Example A: WRIS variables catalog (schema sanity check)
vars_df = swift.wris.variables()
print("Rows:", len(vars_df))
print(vars_df[["flag", "canonical_name"]].head(10))

In [ ]:
# Example B: CWC basin summary and table-based station filtering
cwc_basin_counts = swift.cwc.basins()
print(cwc_basin_counts.head(8))

if len(cwc_basin_counts) > 0:
    chosen_basins = cwc_basin_counts.head(2)["basin"].tolist()
    cwc_from_basin_filter = swift.cwc.stations(basin=chosen_basins)
    print("Chosen basins:", chosen_basins)
    print("Filtered station rows:", len(cwc_from_basin_filter))
    print(cwc_from_basin_filter[["code", "name", "basin"]].head(10))

In [ ]:
# Example C: table metadata checks from WRIS stations() output
sample_wris_stations = swift.wris.stations(
    basin=["Godavari", "Krishna"],
    variable=["discharge"],
)
print("attrs:", sample_wris_stations.attrs)
print(sample_wris_stations[["station_code", "basin", "variable"]].head(8))

In [ ]:
# Example D: expected failures for invalid combinations

def expect_error_contains(label, fn, contains):
    try:
        fn()
        print(f"❌ {label}: expected error containing {contains!r}, but call succeeded")
    except Exception as e:
        msg = str(e)
        ok = contains.lower() in msg.lower()
        prefix = "✅" if ok else "⚠️"
        print(f"{prefix} {label}: {type(e).__name__} -> {msg}")

expect_error_contains(
    "wris.download missing variable",
    lambda: swift.wris.download(basin="Krishna", variable=None),
    "variable is required",
)

expect_error_contains(
    "cwc.download basin table missing basin column",
    lambda: swift.cwc.download(basin=pd.DataFrame({"name": ["Krishna"]})),
    "must include a 'basin' column",
)

expect_error_contains(
    "fetch WRIS table missing station_code and basin/variable",
    lambda: swift.fetch(pd.DataFrame({"x": [1, 2]})),
    "infer data source",
)

In [ ]:
# Example E: help-text parity check used by tests
import io
from contextlib import redirect_stdout
from swift_app.cli import build_parser

buf = io.StringIO()
with redirect_stdout(buf):
    swift.help()

api_help_text = buf.getvalue()
cli_help_text = build_parser().format_help()
print("swift.help() matches CLI parser help:", api_help_text == cli_help_text)

## Smoke-only playground (fast, low-risk)
This section avoids heavy network/file operations and validates API shape + error behavior.
Run these cells first before trying download examples.

In [2]:
# Smoke utility: pretty assertion runner
import traceback

def smoke_check(name, fn):
    try:
        result = fn()
        print(f"✅ {name}")
        return True, result
    except Exception as e:
        print(f"❌ {name}: {type(e).__name__} -> {e}")
        traceback.print_exc(limit=1)
        return False, None

In [3]:
# Smoke 1: public API surface and namespace methods
required_top = ["wris", "cwc", "fetch", "merge_only", "plot_only", "help", "cli_help", "cite", "coffee"]
required_wris = ["download", "stations", "variables", "basins"]
required_cwc = ["download", "stations", "basins", "reconcile_metadata"]

ok, _ = smoke_check(
    "Top-level API surface",
    lambda: all(hasattr(swift, k) for k in required_top),
)
print("top-level ok:", ok)

print("wris missing:", [k for k in required_wris if not hasattr(swift.wris, k)])
print("cwc missing:", [k for k in required_cwc if not hasattr(swift.cwc, k)])

✅ Top-level API surface
top-level ok: True
wris missing: []
cwc missing: []

In [4]:
# Smoke 2: metadata tables only (no downloads)
ok_wvars, wvars = smoke_check("swift.wris.variables()", lambda: swift.wris.variables())
ok_wbasins, wbasins = smoke_check("swift.wris.basins(variable=['discharge','solar'])", lambda: swift.wris.basins(variable=["discharge", "solar"]))
ok_cbasins, cbasins = smoke_check("swift.cwc.basins()", lambda: swift.cwc.basins())

if ok_wvars:
    print(wvars[["flag", "canonical_name"]].head(8))
if ok_wbasins:
    print(wbasins.head(6))
if ok_cbasins:
    print(cbasins.head(6))

✅ swift.wris.variables()
✅ swift.wris.basins(variable=['discharge','solar'])
✅ swift.cwc.basins()
SWIFT Table
Rows: 8 | Columns: 2
----------------------------------------
    flag   canonical_name
0      q        discharge
1     wl      water_level
2    atm     atm_pressure
3     rf         rainfall
4   temp      temperature
5     rh         humidity
6  solar  solar_radiation
7    sed         sediment
SWIFT Table
Rows: 6 | Columns: 3
----------------------------------------
  id                                            basin   variable
0  1                            Brahmani and Baitarni  discharge
1  1                            Brahmani and Baitarni      solar
2  2                                          Cauvery  discharge
3  2                                          Cauvery      solar
4  3  East flowing rivers between Mahanadi and Pennar  discharge
5  3  East flowing rivers between Mahanadi and Pennar      solar
SWIFT Table
Rows: 6 | Columns: 2
----------------------------------------
                                               basin  station_count
0                                   Barak and Others             42
1                              Brahmani and Baitarni             21
2                                        Brahmaputra            139
3                                            Cauvery             53
4    East flowing rivers between Mahanadi and Pennar             21
5  East flowing rivers between Pennar and Kanyaku...             39

In [8]:
# Smoke 3: expected-invalid inputs (should fail cleanly)
def expect_fail(label, fn):
    try:
        fn()
        print(f"❌ {label}: expected failure, but call succeeded")
    except Exception as e:
        print(f"✅ {label}: {type(e).__name__} -> {e}")

expect_fail("wris.basins unknown variable", lambda: swift.wris.basins(variable="___bad___"))
expect_fail("wris.stations missing variable", lambda: swift.wris.stations(basin="Godavari", variable=None))
expect_fail("fetch invalid type", lambda: swift.fetch("not_a_table"))
expect_fail("plot_only missing input dir", lambda: swift.plot_only(input_dir="_missing_smoke_dir_", output_dir="_x_"))

✅ wris.basins unknown variable: ValueError -> Unknown variable: '___bad___'. Supported values: atm, atm_pressure, atmospheric_pressure, discharge, groundwater, groundwater_level, gwl, humidity, q, rainfall, rf, rh, sed, sediment, solar, solar_radiation, temp, temperature, water_level, wl
✅ wris.stations missing variable: ValueError -> variable is required for swift.wris.stations() (for example: 'discharge' or 'solar').
Starting fetch for stations table (rows=11) from 1950-01-01 to latest...
✅ fetch invalid type: TypeError -> fetch() expects a pandas DataFrame/SwiftTable from swift.wris.stations(...), swift.cwc.stations(...), swift.wris.basins(...), or swift.cwc.basins(...).
✅ plot_only missing input dir: ValueError -> input_dir does not exist

## Formatted sample downloads playground
Small-range examples for trying combinations. Keep `overwrite=False` first; turn it on when you want a refresh.

In [12]:
# Download setup (shared)
DL_START = "2024-01-01"
DL_END = "2024-02-03"

OUT_WRIS = "playground_output_wris"
OUT_CWC = "playground_output_cwc"

In [10]:
# Combo 1: WRIS direct basin+variable download (single basin, dual variables)
wris_combo_1 = swift.wris.download(
    basin="Krishna",
    variable=["discharge", "solar"],
    start_date=DL_START,
    end_date=DL_END,
    output_dir=OUT_WRIS,
    format="csv",
    overwrite=False,
    merge=False,
    plot=False,
    quiet=False,
)
print("Combo 1 done")

Starting WRIS download for basin='Krishna', Variables=discharge, solar from 2024-01-01 to 2024-01-03...

Dataset: discharge
Using cached station discovery

discharge: 100%|██████████| 30/30 [00:14<00:00,  2.04station/s]

Saved GeoPackage: playground_output_wris/wris/krishna/krishna_discharge_2024-01-01_2024-01-03.gpkg (57 rows)

discharge downloaded in 14.9 seconds

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:00<00:00,  6.39station/s]

Saved GeoPackage: playground_output_wris/wris/krishna/krishna_solar_radiation_2024-01-01_2024-01-03.gpkg (571 rows)

solar_radiation downloaded in 0.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
discharge         19          19          0           14.9
solar_radiation   5           5           0           0.8
-------------------------------------------------------------
Output directory: playground_output_wris/wris/krishna
-------------------------------------------------------------
Combo 1 done

In [13]:
# Combo 2: WRIS station-table -> fetch (tiny slice)
wris_station_tbl = swift.wris.stations(
    basin=["Godavari"],
    variable=["sediment"],
)
wris_station_tbl_small = wris_station_tbl.head(2)

swift.fetch(
    wris_station_tbl_small,
    output_dir=OUT_WRIS,
    start_date=DL_START,
    end_date=DL_END,
    format="xlsx",
    overwrite=False,
    merge=False,
    plot=False,
    quiet=False,
)
print("Combo 2 rows used:", len(wris_station_tbl_small))

Searching the WRIS database... This might take some time.
The station list returned does not guarantee time series data availability for all time periods.
Starting fetch for stations table (rows=2) from 2024-01-01 to 2024-02-03...
Starting WRIS download for basin='Godavari', Variables=sediment from 2024-01-01 to 2024-02-03...

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 2/2 [00:07<00:00,  3.60s/station]

No stations found with data in the requested time period; skipping merge for this dataset.

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
sediment          0           0           0           7.2
-------------------------------------------------------------
Output directory: playground_output_wris/wris/godavari
-------------------------------------------------------------
Combo 2 rows used: 2

In [14]:
# Combo 3: CWC basin-table filter -> fetch (tiny basin subset)
cwc_basin_tbl = swift.cwc.basins().head(2)

swift.fetch(
    cwc_basin_tbl,
    output_dir=OUT_CWC,
    start_date=DL_START,
    end_date=DL_END,
    format="csv",
    overwrite=False,
    merge=False,
    plot=False,
    quiet=False,
)
print("Combo 3 basins:", cwc_basin_tbl["basin"].tolist())

Starting fetch for stations table (rows=2) from 2024-01-01 to 2024-02-03...
Starting CWC download for station=['001-MDSIL', '001-MIDSHL', '002-MDSIL', '002-midshl', '003-MDSIL', '004-mdsil', '005-mdsil', '006-MDSIL', '007-MDSIL', '008-MDSIL', '009-MBDGHY', '009-mdsil', '010-MBDGHY', '010-mdsil', '011-MBDGHY', '011-mdsil', '012-MBDGHY', '012-MDSIL', '013-MBDGHY', '013-MDSIL', '014-MDSIL', '015-MBDGHY', '015-MDSIL', '016-MBDGHY', '016-MDSIL', '017-MBDghy', '017-MDSIL', '018-MDSIL', '019-MBDGHY', '019-MDSIL', '020-MDSIL', '021-MBDGHY', '021-MDSIL', '022-MBDGHY', '022-MDSIL', '023-MBDGHY', '023-MDSIL', '024- MDSIL', '026- MDSIL', '027- MDSIL', '028- MDSIL', '030-MBDGHY'] from 2024-01-01 to 2024-02-03...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 42 | Format: CSV | Time range: 2024–2024
Basin filter: Barak and Others
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

/tmp/ipykernel_1487049/1123281592.py:4: UserWarning: Fetching CWC data for basin-level input (all stations per basin). Dispatching 2 basins; this may take a long time.
  swift.fetch(
water_level: 100%|██████████| 42/42 [00:00<00:00, 12973.03station/s]

Saved GeoPackage: playground_output_cwc/cwc/cwc_waterlevel_barak_and_others_2024-01-01_2024-02-03.gpkg (894 rows)

water_level downloaded in 30.9 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       9           9           0           30.9
-------------------------------------------------------------
Output directory: playground_output_cwc/cwc
-------------------------------------------------------------
Starting CWC download for station=['013-ERDBWN', '014-ERDBWN', '015-ERDBWN', '016-ERDBWN', '017-ERDBWN', '018-ERDBWN', '019-ERDBWN', '020-ERDBWN', '022-ERDBWN', '023-ERDBWN', '049-ERDBWN', '050-ERDBWN', '051-ERDBWN', '052-ERDBWN', '053-ERDBWN', '055-erdbwn', '061-ERDBWN', '065-ERDBWN', '067-ERDBWN', '068-ERDBWN', '073-ERDBWN'] from 2024-01-01 to 2024-02-03...

Dataset: water_level (CWC)
Mode: CWC download | Stations: 21 | Format: CSV | Time range: 2024–2024
Basin filter: Brahmani and Baitarni
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 21/21 [00:00<00:00, 20225.12station/s]

Saved GeoPackage: playground_output_cwc/cwc/cwc_waterlevel_brahmani_and_baitarni_2024-01-01_2024-02-03.gpkg (1265 rows)

water_level downloaded in 15.8 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       13          13          0           15.8
-------------------------------------------------------------
Output directory: playground_output_cwc/cwc
-------------------------------------------------------------
Combo 3 basins: ['Barak and Others', 'Brahmani and Baitarni']

In [ ]:
# Combo 4: CWC direct station download + merge return
cwc_station_tbl = swift.cwc.stations(basin=["Godavari"]).head(2)
cwc_codes = cwc_station_tbl["code"].tolist()

cwc_gdf = swift.cwc.download(
    station=cwc_codes,
    start_date=DL_START,
    end_date=DL_END,
    output_dir=OUT_CWC,
    format="csv",
    overwrite=False,
    merge=True,
    plot=False,
    quiet=False,
)

print("Combo 4 station codes:", cwc_codes)
print("Returned object type:", type(cwc_gdf).__name__ if cwc_gdf is not None else None)

In [ ]:
# Combo 5: merge_only / plot_only on generated playground outputs (safe if dirs exist)
from pathlib import Path

for mode, in_dir, out_dir in [
    ("wris", OUT_WRIS, f"{OUT_WRIS}_post"),
    ("cwc", OUT_CWC, f"{OUT_CWC}_post"),
]:
    if Path(in_dir).exists():
        print(f"Running post-process for mode={mode} input={in_dir}")
        try:
            swift.merge_only(mode=mode, input_dir=in_dir, output_dir=out_dir)
            swift.plot_only(mode=mode, input_dir=in_dir, output_dir=out_dir)
            print("  ✅ done")
        except Exception as e:
            print(f"  ⚠️ post-process error: {type(e).__name__} -> {e}")
    else:
        print(f"Skipping mode={mode}: {in_dir} does not exist yet")