In [1]:
import swift_app as swift
import pandas as pd
import glob

In [2]:
import importlib
import swift_app.api as _api
importlib.reload(_api)
importlib.reload(swift)

In [3]:
swift.wris.download(
    basin=['Krishna', 'Godavari'],
    variable=["solar", "sediment"],
    start_date="2025-01-01",
    overwrite=True,
    merge=True,
    plot=True,
    output_dir="data"
)

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 5/5 [00:06<00:00,  1.38s/station]

Saved GeoPackage: data/wris/krishna/Krishna_solar_radiation.gpkg (50483 rows)

solar_radiation downloaded in 7.3 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 20/20 [00:07<00:00,  2.69station/s]

Saved GeoPackage: data/wris/krishna/Krishna_sediment.gpkg (2717 rows)

sediment downloaded in 7.5 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           7.3
sediment          15          15          0           7.5
-------------------------------------------------------------
Output directory: data/wris/krishna
-------------------------------------------------------------

Plot-only mode enabled.

Plotting krishna / solar_radiation (5 stations)
Saved: data/wris/krishna/images/solar_radiation/KK3GMNB291_Deodurga_SOLAR_RD.png
Saved: data/wris/krishna/images/solar_radiation/Patryachiwad_Patryachiwadi_SOLAR_RD.png
Saved: data/wris/krishna/images/solar_radiation/Rukadi_Rukadi_SOLAR_RD.png
Saved: data/wris/krishna/images/solar_radiation/7D90291A_Prakasam Barrage APSW_SOLAR_RD.png
Saved: data/wris/krishna/images/solar_radiation/KK3GMNB353_Sindhanur_SOLAR_RD.png

Plotting krishna / sediment (16 stations)
Saved: data/wris/krishna/images/sediment/009-CDBNG_KUPPELUR_SEDIM.png
Saved: data/wris/krishna/images/sediment/005-cdbng_BYALADAHALLI_SEDIM.png
Saved: data/wris/krishna/images/sediment/002-CDBNG_Honnali_SEDIM.png
Saved: data/wris/krishna/images/sediment/004-CDBNG_Marol_SEDIM.png
Saved: data/wris/krishna/images/sediment/013-lkdhyd_Mantralayam_SEDIM.png
Saved: data/wris/krishna/images/sediment/023-LKDHYD_Paleru Bridge_SEDIM.png
Saved: data/wris/krishna/images/sediment/003-CDBNG_Haralahalli_SEDIM.png
Saved: data/wris/krishna/images/sediment/021-LKDHYD_Keesara_SEDIM.png
Saved: data/wris/krishna/images/sediment/003-UKDPUNE_Samdoli (Seasonal)_SEDIM.png
Saved: data/wris/krishna/images/sediment/011-cdbmg_HARIHARAPURA_SEDIM.png
Saved: data/wris/krishna/images/sediment/014-lkdhyd_Bawapuram_SEDIM.png
Saved: data/wris/krishna/images/sediment/049-CDBNG_LAKKAVALLI_SEDIM.png

/home/carbform/swift/swift_app/plot_station_timeseries.py:196: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())

Saved: data/wris/krishna/images/sediment/042-UKD PUNE_NANDRE_SEDIM.png
Saved: data/wris/krishna/images/sediment/022-LKDHYD_Madhira_SEDIM.png
Saved: data/wris/krishna/images/sediment/002-UKDPUNE_Warunji_SEDIM.png
Saved: data/wris/krishna/images/sediment/001-CDBNG_Shimoga_SEDIM.png

Plots generated: 21

Dataset: solar_radiation
Using cached station discovery

solar_radiation: 100%|██████████| 3/3 [00:04<00:00,  1.34s/station]

Saved GeoPackage: data/wris/godavari/Godavari_solar_radiation.gpkg (29077 rows)

solar_radiation downloaded in 4.2 seconds

Dataset: sediment
Using cached station discovery

sediment: 100%|██████████| 4/4 [00:06<00:00,  1.66s/station]

Saved GeoPackage: data/wris/godavari/Godavari_sediment.gpkg (119 rows)

sediment downloaded in 6.6 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   3           3           0           4.2
sediment          1           1           0           6.6
-------------------------------------------------------------
Output directory: data/wris/godavari
-------------------------------------------------------------

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: data/wris/godavari/images/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: data/wris/godavari/images/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: data/wris/godavari/images/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plotting godavari / sediment (1 stations)
Saved: data/wris/godavari/images/sediment/007-ugdhyd_Pachegaon_SEDIM.png

Plots generated: 4

In [3]:
cwc_for_fetch = swift.cwc.stations(basin="Godavari", state = "Telangana")
cwc_for_fetch

,code,name,river,basin,state,district,division,lat,lon,rl_zero,warning_level,danger_level,hfl,hfl_date
0,001-lgdhyd,Somanpally(Seasonal),Maner,Godavari,Telangana,KARIMNAGAR,"Upper Godavari Division(UGD), Hyderabad",18.616667,79.800000,121.000,NaN,NaN,129.020,2023-07-27
1,002-LGDHYD,Kaleswaram,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.820000,79.910000,91.290,103.500,104.750,108.190,2022-07-15
2,014-lgdhyd,Perur,Godavari,Godavari,Telangana,MULUGU,"Upper Godavari Division(UGD), Hyderabad",18.536667,80.376667,65.000,78.150,81.150,87.420,1986-08-15
3,015-LGDHYD,Eturunagaram,Godavari,Godavari,Telangana,MULUGU,"Upper Godavari Division(UGD), Hyderabad",18.320000,80.460000,58.500,73.320,75.820,77.660,1990-08-24
4,016-LGDHYD,Dummagudem,Godavari,Godavari,Telangana,BHADRADRI,"Lower Godavari Division(LGD), Hyderabad",17.852500,80.880000,40.000,53.000,55.000,60.250,1986-08-16
5,017-LGDHYD,Bhadrachalam,Godavari,Godavari,Telangana,BHADRADRI,"Lower Godavari Division(LGD), Hyderabad",17.669444,80.873889,26.610,45.720,48.770,55.660,1986-08-16
6,018-LGDHYD,Sangam (Kinnerasani),Kinnerasani,Godavari,Telangana,KHAMMAM,"Lower Godavari Division(LGD), Hyderabad",17.599722,80.816389,48.500,NaN,NaN,57.300,1996-06-17
7,018-UGDHYD,Singur Reservoir,Manjira,Godavari,Telangana,SANGA REDDY,"Upper Godavari Division(UGD), Hyderabad",17.750000,77.930000,0.000,NaN,NaN,NaN,NaN
8,019-UGDHYD,Nizamsagar Reservoir,Manjira,Godavari,Telangana,KAMAREDDY,"Upper Godavari Division(UGD), Hyderabad",18.220000,77.960000,0.000,NaN,NaN,NaN,NaN
9,019-lgdhyd,Sangam (Murredu),Murredu,Godavari,Telangana,BHADRADRI,"Lower Godavari Division(LGD), Hyderabad",17.593611,80.821667,50.000,NaN,NaN,57.480,2023-07-27
10,022-ugdhyd,Bhainsa(State Govt. Site),Suddavagu,Godavari,Telangana,NIRMAL,"Upper Godavari Division(UGD), Hyderabad",19.098889,77.960556,346.270,352.770,353.770,354.770,2023-07-27
11,022-wgdngp,Bhatpalli,Peddavagu,Godavari,Telangana,KUMURAM BHEEM,"Wainganga Division(WD), Nagpur",19.329722,79.504167,156.000,NaN,NaN,169.400,1986-08-13
12,023-UGDHYD,Sriram Sagar Reservoir,Godavari,Godavari,Telangana,NIZAMABAD,"Upper Godavari Division(UGD), Hyderabad",18.970000,78.340000,0.000,NaN,NaN,NaN,NaN
13,024-UGDHYD,Gandlapet,Peddavagu,Godavari,Telangana,NIZAMABAD,"Upper Godavari Division(UGD), Hyderabad",18.821111,78.438056,310.000,315.630,316.630,317.630,2023-07-27
14,025-UGDHYD,Mancherial,Godavari,Godavari,Telangana,ADILABAD,"Upper Godavari Division(UGD), Hyderabad",18.850278,79.444444,124.316,133.316,134.816,139.136,2022-07-14
15,026-ugdhyd,Kaddam Dam,Kaddam vagu,Godavari,Telangana,ADILABAD,"Upper Godavari Division(UGD), Hyderabad",19.100000,78.790000,0.000,NaN,NaN,NaN,NaN
16,027-ugdhyd,Sripada Yellampalli Project,Godavari,Godavari,Telangana,KARIMNAGAR,"Upper Godavari Division(UGD), Hyderabad",18.844167,79.372778,0.000,NaN,NaN,NaN,NaN
17,028-wgdngp,Sirpur (Town),Wardha,Godavari,Telangana,KUMURAM BHEEM,"Wainganga Division(WD), Nagpur",19.509722,79.586389,145.160,159.950,160.950,162.740,2023-07-29
18,030-UGDHYD,JANNEPALLY,Poolanvagu,Godavari,Telangana,NIZAMABAD,"Upper Godavari Division(UGD), Hyderabad",18.813611,78.063333,336.655,342.655,343.655,344.655,2022-07-13
19,034-LGDHYD,PVNRao Kantanapally Project,Godavari,Godavari,Telangana,MULUGU,"Upper Godavari Division(UGD), Hyderabad",18.586111,80.393333,64.790,NaN,NaN,NaN,NaN
20,049-ugdhyd,LAXMI BARRAGE,Godavari,Godavari,Telangana,BHUPALPALLY,"Upper Godavari Division(UGD), Hyderabad",18.703889,80.089167,0.000,NaN,NaN,NaN,NaN
21,053-UGDHYD,MID MANAIR DAM,Maner,Godavari,Telangana,RAJANNA SIRCILLA,"Upper Godavari Division(UGD), Hyderabad",18.392778,78.961111,0.000,NaN,NaN,NaN,NaN

In [10]:
# Test fetch() from CWC station table
swift.fetch(
    cwc_for_fetch,
    output_dir="data_fetch_cwc",
    start_date="2024-01-01",
    end_date="2024-01-07",
    merge=True,
    plot=True,
    quiet=False, overwrite=True
)

Dataset: water_level (CWC)
Mode: CWC download | Stations: 22 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 22/22 [00:00<00:00, 33384.47station/s]
Plotting:  12%|█▏        | 2/17 [00:00<00:02,  6.17plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_002-LGDHYD_kaleswaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-LGDHYD_sangam_kinnerasani.png

Plotting:  24%|██▎       | 4/17 [00:00<00:01,  6.58plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-LGDHYD_dummagudem.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-UGDHYD_mancherial.png

Plotting:  35%|███▌      | 6/17 [00:00<00:01,  6.68plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_030-UGDHYD_jannepally.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-LGDHYD_eturunagaram.png

Plotting:  47%|████▋     | 8/17 [00:01<00:01,  6.74plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_023-UGDHYD_sriram_sagar_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-ugdhyd_kaddam_dam.png

Plotting:  59%|█████▉    | 10/17 [00:01<00:01,  6.66plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-UGDHYD_nizamsagar_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-wgdngp_bhatpalli.png

Plotting:  71%|███████   | 12/17 [00:01<00:00,  6.72plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_001-lgdhyd_somanpallyseasonal.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-UGDHYD_gandlapet.png

Plotting:  82%|████████▏ | 14/17 [00:02<00:00,  6.71plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-lgdhyd_sangam_murredu.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-ugdhyd_bhainsastate_govt._site.png

Plotting:  88%|████████▊ | 15/17 [00:02<00:00,  6.77plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-UGDHYD_singur_reservoir.png

Plotting: 100%|██████████| 17/17 [00:02<00:00,  6.50plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-LGDHYD_bhadrachalam.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-lgdhyd_perur.png
Plots generated: 17
Saved GeoPackage: data_fetch_cwc/cwc/cwc_timeseries_telangana_godavari.gpkg (283 rows)

water_level downloaded in 18.1 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       17          17          0           18.1
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/godavari/stations
-------------------------------------------------------------

In [7]:
swift.merge(mode='cwc',input_dir="data_fetch_cwc/", output_dir='test_merge')

No station files found: data_fetch_cwc/cwc/godavari

In [8]:
swift.merge(input_dir="data", basin=['Krishna', 'Godavari', "Narmada"], datasets=["solar"], output_dir='test_merge')

/tmp/ipykernel_120728/3515395378.py:1: UserWarning: Basin 'Krishna' not found in input_dir='data'. Skipping.
  swift.merge(input_dir="data", basin=['Krishna', 'Godavari', "Narmada"], datasets=["solar"], output_dir='test_merge')
/tmp/ipykernel_120728/3515395378.py:1: UserWarning: Basin 'Godavari' not found in input_dir='data'. Skipping.
  swift.merge(input_dir="data", basin=['Krishna', 'Godavari', "Narmada"], datasets=["solar"], output_dir='test_merge')
/tmp/ipykernel_120728/3515395378.py:1: UserWarning: Basin 'Narmada' not found in input_dir='data'. Skipping.
  swift.merge(input_dir="data", basin=['Krishna', 'Godavari', "Narmada"], datasets=["solar"], output_dir='test_merge')

In [4]:
swift.plot(input_dir="data", basin=["krishna", "godavari", "narmada"], datasets=["solar", 'sediment'], output_dir='test_plot')

Plot-only mode enabled.

Plotting krishna / solar_radiation (5 stations)
Saved: test_plot/wris/krishna/solar_radiation/KK3GMNB291_Deodurga_SOLAR_RD.png
Saved: test_plot/wris/krishna/solar_radiation/Patryachiwad_Patryachiwadi_SOLAR_RD.png
Saved: test_plot/wris/krishna/solar_radiation/Rukadi_Rukadi_SOLAR_RD.png
Saved: test_plot/wris/krishna/solar_radiation/7D90291A_Prakasam Barrage APSW_SOLAR_RD.png
Saved: test_plot/wris/krishna/solar_radiation/KK3GMNB353_Sindhanur_SOLAR_RD.png

Plotting krishna / sediment (16 stations)
Saved: test_plot/wris/krishna/sediment/009-CDBNG_KUPPELUR_SEDIM.png
Saved: test_plot/wris/krishna/sediment/005-cdbng_BYALADAHALLI_SEDIM.png
Saved: test_plot/wris/krishna/sediment/002-CDBNG_Honnali_SEDIM.png
Saved: test_plot/wris/krishna/sediment/004-CDBNG_Marol_SEDIM.png
Saved: test_plot/wris/krishna/sediment/013-lkdhyd_Mantralayam_SEDIM.png
Saved: test_plot/wris/krishna/sediment/023-LKDHYD_Paleru Bridge_SEDIM.png
Saved: test_plot/wris/krishna/sediment/003-CDBNG_Haralahalli_SEDIM.png
Saved: test_plot/wris/krishna/sediment/021-LKDHYD_Keesara_SEDIM.png
Saved: test_plot/wris/krishna/sediment/003-UKDPUNE_Samdoli (Seasonal)_SEDIM.png
Saved: test_plot/wris/krishna/sediment/011-cdbmg_HARIHARAPURA_SEDIM.png
Saved: test_plot/wris/krishna/sediment/014-lkdhyd_Bawapuram_SEDIM.png
Saved: test_plot/wris/krishna/sediment/049-CDBNG_LAKKAVALLI_SEDIM.png
Saved: test_plot/wris/krishna/sediment/042-UKD PUNE_NANDRE_SEDIM.png

/home/carbform/swift/swift_app/plot_station_timeseries.py:196: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  ax.set_xlim(df["time"].min(), df["time"].max())

Saved: test_plot/wris/krishna/sediment/022-LKDHYD_Madhira_SEDIM.png
Saved: test_plot/wris/krishna/sediment/002-UKDPUNE_Warunji_SEDIM.png
Saved: test_plot/wris/krishna/sediment/001-CDBNG_Shimoga_SEDIM.png

Plots generated: 21

Plot-only mode enabled.

Plotting godavari / solar_radiation (3 stations)
Saved: test_plot/wris/godavari/solar_radiation/7D903A6C_Dowlaiswaram_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D8FED08_Kovvada kalva reservoir_SOLAR_RD.png
Saved: test_plot/wris/godavari/solar_radiation/7D901252_Vuyyuru_SOLAR_RD.png

Plotting godavari / sediment (1 stations)
Saved: test_plot/wris/godavari/sediment/007-ugdhyd_Pachegaon_SEDIM.png

Plots generated: 4

/tmp/ipykernel_50393/3833945000.py:1: UserWarning: Basin 'narmada' not found in input_dir='data'. Skipping.
  swift.plot(input_dir="data", basin=["krishna", "godavari", "narmada"], datasets=["solar", 'sediment'], output_dir='test_plot')

In [10]:
df = swift.wris.stations(basin="narmada", variable="sediment")
df

SWIFT Table
Rows: 6 | Columns: 5
----------------------------------------
   station_code       station_name  latitude  longitude    river
0     004-NDBHP          Chhidgaon   22.4012    77.3086   Ganjal
1   006-TDSURAT           CHANWADA   22.0500    73.4653   Orsang
2     009-ndbhp              Manot   22.7358    80.5131  Narmada
3  01 02 17 002  Tapi at Burhanpur   21.2994    76.2354     Tapi
4     013 NDBHP             Sandia   22.9167    78.3500  Narmada
5     016-NDBHP       Narmadapuram   22.7560    77.7330  Narmada

In [ ]:
swift.wris.download(
    basin="Krishna",
    variable=["solar", "discharge"],
    overwrite=True,
    merge=True,
    plot=True
)

In [ ]:
import swift_app as swift

In [ ]:
swift.basins()

In [ ]:
stations = swift.wris.stations("Godavari")

In [ ]:
stations

In [ ]:
cwc = swift.cwc.stations()

In [ ]:
cwc

In [ ]:
station_id = cwc.iloc[0]["code"] if len(cwc) else "GDA001"
meta = swift.cwc.stations(station=station_id)

In [ ]:
meta

In [ ]:
# Sanity check: public Python API surface
import swift_app as swift

public_attrs = [
    "wris",
    "cwc",
    "fetch",
    "merge",
    "plot",
    "datasets",
    "basins",
    "cite",
    "coffee",
]

api_flags = {name: hasattr(swift, name) for name in public_attrs}
api_flags

In [ ]:
# Test CWC download via public namespace API
swift.cwc.download(
    station=["040-CDJAPR"],
    start_date="2024-01-01",
    end_date="2024-01-07",
    output_dir="data_cwc",
    format="csv",
    overwrite=False,
    merge=False,
    plot=False,
    quiet=False,
)

In [6]:
stations_for_fetch = swift.wris.stations(basin="Krishna", variable="solar")
stations_for_fetch

SWIFT Table
Rows: 5 | Columns: 5
----------------------------------------
   station_code           station_name  latitude  longitude          river
0      7D90291A  Prakasam Barrage APSW   16.5061    80.6047  Lower Krishna
1    KK3GMNB291               Deodurga   16.4172    76.9281  Lower Krishna
2    KK3GMNB353              Sindhanur   15.7714    76.7578  Lower Krishna
3  Patryachiwad          Patryachiwadi   16.6161    73.9917     Panchganga
4        Rukadi                 Rukadi   16.7200    74.3556     Panchganga

In [5]:
# Test fetch() from WRIS station table
stations_for_fetch = swift.wris.stations(basin="Krishna", variable="solar")
swift.fetch(
    stations_for_fetch,
    output_dir="data_fetch_wris",
    start_date="2024-01-01",
    end_date="2024-01-07",
    merge=True,
    plot=True,
    quiet=False,
)

Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Dataset: solar_radiation
Using cached station discovery
Stations skipped (already downloaded): 5
Tip: use --overwrite to refresh data.
All stations already downloaded — skipping download step.
Saved GeoPackage: data_fetch_wris/wris/krishna/Krishna_solar_radiation.gpkg (1344 rows)

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
solar_radiation   5           0           5           0.1
-------------------------------------------------------------
Output directory: data_fetch_wris/wris/krishna
-------------------------------------------------------------

Plot-only mode enabled.

Plotting krishna / solar_radiation (5 stations)
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/KK3GMNB291_Deodurga_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/Patryachiwad_Patryachiwadi_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/Rukadi_Rukadi_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/7D90291A_Prakasam Barrage APSW_SOLAR_RD.png
Saved: data_fetch_wris/wris/krishna/images/solar_radiation/KK3GMNB353_Sindhanur_SOLAR_RD.png

Plots generated: 5

In [4]:
cwc_for_fetch.attrs

{'source': 'cwc', 'basin': 'Godavari', 'state': 'Telangana'}

Dataset: water_level (CWC)
Mode: CWC download | Stations: 22 | Format: CSV | Time range: 2024–2024
Note: The CWC servers stream full historical datasets at slow speeds (~100 KB/s).
A single station may take 1-2 minutes to appear on the progress bar. Please do not cancel the process.

water_level: 100%|██████████| 22/22 [00:00<00:00, 36143.63station/s]
Plotting:  12%|█▏        | 2/17 [00:00<00:02,  6.07plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_002-LGDHYD_kaleswaram.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-LGDHYD_sangam_kinnerasani.png

Plotting:  24%|██▎       | 4/17 [00:00<00:01,  6.53plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_016-LGDHYD_dummagudem.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_025-UGDHYD_mancherial.png

Plotting:  35%|███▌      | 6/17 [00:00<00:01,  6.74plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_030-UGDHYD_jannepally.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_015-LGDHYD_eturunagaram.png

Plotting:  47%|████▋     | 8/17 [00:01<00:01,  6.83plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_023-UGDHYD_sriram_sagar_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_026-ugdhyd_kaddam_dam.png

Plotting:  59%|█████▉    | 10/17 [00:01<00:01,  6.77plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-UGDHYD_nizamsagar_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-wgdngp_bhatpalli.png

Plotting:  71%|███████   | 12/17 [00:01<00:00,  6.90plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_001-lgdhyd_somanpallyseasonal.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_024-UGDHYD_gandlapet.png

Plotting:  82%|████████▏ | 14/17 [00:02<00:00,  6.57plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_019-lgdhyd_sangam_murredu.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_022-ugdhyd_bhainsastate_govt._site.png

Plotting:  94%|█████████▍| 16/17 [00:02<00:00,  6.85plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_018-UGDHYD_singur_reservoir.png
Saved: data_fetch_cwc/cwc/godavari/images/CWC_017-LGDHYD_bhadrachalam.png

Plotting: 100%|██████████| 17/17 [00:02<00:00,  6.71plot/s]

Saved: data_fetch_cwc/cwc/godavari/images/CWC_014-lgdhyd_perur.png
Plots generated: 17
Saved GeoPackage: data_fetch_cwc/cwc/cwc_timeseries_telangana_godavari.gpkg (283 rows)

water_level downloaded in 18.3 seconds

-------------------------------------------------------------
Download Summary
-------------------------------------------------------------
Dataset           Found       Downloaded  Skipped     Time(s)
-------------------------------------------------------------
water_level       17          17          0           18.3
-------------------------------------------------------------
Output directory: data_fetch_cwc/cwc/godavari/stations
-------------------------------------------------------------

In [ ]:
# Test merge() with mode-based API (requires existing WRIS output)
from pathlib import Path

if Path("output").exists():
    swift.merge(mode="wris", basin="Godavari", output_dir="output_merged")
else:
    print("output/ not found; run a WRIS download cell first.")

In [ ]:
# Test plot() with mode-based API (requires existing WRIS output)
from pathlib import Path

if Path("output").exists():
    swift.plot(mode="wris", basin="Godavari", output_dir="output")
else:
    print("output/ not found; run a WRIS download cell first.")

In [ ]:
# Test cite() and coffee() helpers (side-effect: print to stdout)
import swift_app as swift

swift.cite()
swift.coffee()